const BOARD_SETUP = {
  ladders: 7,
  snakes: 7,
  minSpan: 8,
  maxSpan: 26,
  maxEndpointsPerRow: 4,
  surpriseChance: 0.25,
};

// The scenes the setup screen offers (plus Random, which draws a different one
// every game). Each defines the page backdrop AND the board surface, ladder and
// snake colours together, so the board always sits in the same world as the
// background behind it.
//
// `life` is the scene's ambient wildlife (drifting petals, falling leaves,
// bubbles, butterflies, dust motes, fireflies — drawn in script.js by
// buildSceneLife), and `sunlight` the colour of the slow sunlight/moonlight wash
// over the page. `backdrop`, when set, is a full-bleed photographic scene
// ({ landscape, portrait } image paths) that replaces the tiled photo — see
// scripts/generate-art.mjs, which makes them. `swatch` paints the scene's
// button in the setup picker, `events` names its occasional set pieces
// (shooting stars, sun rays, cloud shadows… buildSceneEvents) and `ambience`
// its synthesised soundscape (AMBIENCES in script.js).
const BOARD_THEMES = {
  romance: {
    label: 'Romance',
    label_id: 'Romantis',
    page: 'radial-gradient(1100px 620px at 50% -12%, #fff7f4 0%, transparent 62%), radial-gradient(900px 520px at 92% 104%, #ecdfff 0%, transparent 58%), linear-gradient(160deg, #fdeef1 0%, #f5e8f7 52%, #ffeef0 100%)',
    pageBase: '#f5e8f7',
    boardBg: 'linear-gradient(155deg, #fffdf9, #fdf1ea)',
    frame: '#ffffff',
    cell: 'linear-gradient(160deg, #fffdfa, #fff8f3)',
    cellAlt: 'linear-gradient(160deg, #fdeff1, #fbe7ec)',
    cellBorder: 'rgba(240, 219, 227, 0.7)',
    cellInk: '#8a7681',
    edge: ['#f0d9dd', '#e9cbd2', '#e0bac4', '#d5a7b4', '#c996a6'],
    dropShadow: 'rgba(120, 40, 80, 0.3)',
    ladder: { dark: '#a85f6d', light: '#f0b9a6', foot: '#d38f88' },
    snake: { body: '#7d4e66', outline: '#3d2233', belly: '#ead5d6', head: '#6f4159' },
    accent: '#d6336c',
    accentDeep: '#a52551',
    pageTexture:
      "<svg xmlns='http://www.w3.org/2000/svg' width='120' height='120'><g fill='#d6336c' fill-opacity='0.07'><path d='M30 26c-4-6-14-5-14 3 0 7 9 12 14 17 5-5 14-10 14-17 0-8-10-9-14-3z'/><path d='M88 74c-3-5-11-4-11 2 0 6 7 10 11 14 4-4 11-8 11-14 0-6-8-7-11-2z'/><circle cx='95' cy='25' r='2.5'/><circle cx='22' cy='92' r='2'/></g></svg>",
    pageTextureSize: '120px 120px',
    cellTexture:
      "<svg xmlns='http://www.w3.org/2000/svg' width='16' height='16'><g stroke='#b07a8e' stroke-opacity='0.09' stroke-width='1'><path d='M0 4h16M0 12h16'/><path d='M4 0v16M12 0v16'/></g></svg>",
    cellTextureSize: '16px 16px',
    photo: 'assets/textures/romance.webp',
    photoPageSize: '420px',
    photoPageOpacity: 0.42,
    photoBoardSize: '180px',
    photoBoardOpacity: 0.14,
    motion: 'twinkle', driftAxis: 'xy', driftDuration: '95s', boardDriftDuration: '150s', twinkleDuration: '7s',
    ornaments: ['💗', '✨', '🌸', '🌹', '🎀', '🍓'],
    life: { kind: 'petal', count: 22, colors: ['#f6b3c6', '#ee9ab3', '#fde0e8', '#f3c1cf'] },
    backdrop: { landscape: 'assets/scenes/romance-landscape.webp', portrait: 'assets/scenes/romance-portrait.webp' },
    // The setup screen's picker swatch, painted to echo the backdrop photo.
    swatch: 'radial-gradient(circle at 30% 24%, #fff3e6 0 14%, transparent 52%), linear-gradient(145deg, #f7d9dd, #eaa8b6 58%, #d98097)',
    ambience: 'cafe',
    events: 'bokeh',
    sunlight: 'rgba(255, 236, 240, 0.9)',
    startIcon: '💌', finishIcon: '💍',
  },
  forest: {
    label: 'Forest',
    label_id: 'Hutan',
    page: 'radial-gradient(1100px 620px at 50% -12%, #f0f8ea 0%, transparent 62%), radial-gradient(900px 520px at 92% 104%, #cfe6d4 0%, transparent 58%), linear-gradient(160deg, #e4f1dc 0%, #d5e9d6 52%, #eaf5e2 100%)',
    pageBase: '#d5e9d6',
    boardBg: 'linear-gradient(155deg, #fbfdf6, #e9f3e0)',
    frame: '#fbfdf7',
    cell: 'linear-gradient(160deg, #fbfdf6, #f2f9ea)',
    cellAlt: 'linear-gradient(160deg, #e7f2de, #dcebd2)',
    cellBorder: 'rgba(200, 224, 190, 0.75)',
    cellInk: '#6d8168',
    edge: ['#d8e8cf', '#cbe0c0', '#bcd6b0', '#a9c99c', '#96bb88'],
    dropShadow: 'rgba(40, 80, 45, 0.32)',
    ladder: { dark: '#8a5a2b', light: '#dca868', foot: '#b07c3f' },
    snake: { body: '#647d3f', outline: '#2c391b', belly: '#d3d9a4', head: '#586f37' },
    accent: '#3f8f4f',
    accentDeep: '#2c6b39',
    pageTexture:
      "<svg xmlns='http://www.w3.org/2000/svg' width='140' height='140'><g fill='#2f5c2c' fill-opacity='0.08'><path d='M20 30c14-12 30-10 34 2-12 12-28 12-34-2z'/><path d='M100 88c12-14 28-14 34-3-10 13-26 15-34 3z'/><path d='M60 118c8-10 20-10 24-2-8 9-19 10-24 2z'/></g><g stroke='#2f5c2c' stroke-opacity='0.07' stroke-width='1.2' fill='none' stroke-linecap='round'><path d='M20 30c11 1 23 2 34 2'/><path d='M100 88c11 0 24 2 34-3'/><path d='M60 118c8 0 17 1 24-2'/></g></svg>",
    pageTextureSize: '140px 140px',
    cellTexture:
      "<svg xmlns='http://www.w3.org/2000/svg' width='60' height='24'><g stroke='#5a7a48' stroke-opacity='0.09' stroke-width='1' fill='none'><path d='M0 6q15-4 30 0t30 0'/><path d='M0 14q15 4 30 0t30 0'/><path d='M0 21q15-3 30 0t30 0'/></g></svg>",
    cellTextureSize: '60px 24px',
    photo: 'assets/textures/forest.webp',
    photoPageSize: '460px',
    photoPageOpacity: 0.40,
    photoBoardSize: '200px',
    photoBoardOpacity: 0.13,
    motion: 'drift', driftAxis: 'xy', driftDuration: '60s', boardDriftDuration: '110s',
    ornaments: ['🍃', '🌲', '🍄', '🌿', '🍂', '🐿️'],
    life: { kind: 'leaf', count: 18, colors: ['#6d8b35', '#8fa846', '#b58a3c', '#a36b2e'] },
    backdrop: { landscape: 'assets/scenes/forest-landscape.webp', portrait: 'assets/scenes/forest-portrait.webp' },
    // The setup screen's picker swatch, painted to echo the backdrop photo.
    swatch: 'radial-gradient(circle at 26% 20%, #f4f1b8 0 10%, transparent 48%), linear-gradient(150deg, #86b35f, #4f7f35 55%, #2f5a26)',
    ambience: 'forest',
    events: 'rays',
    sunlight: 'rgba(255, 244, 205, 0.85)',
    startIcon: '🌱', finishIcon: '🌳',
  },
  ocean: {
    label: 'Ocean',
    label_id: 'Pantai',
    page: 'radial-gradient(1100px 620px at 50% -12%, #eaf7fb 0%, transparent 62%), radial-gradient(900px 520px at 92% 104%, #c9e2f2 0%, transparent 58%), linear-gradient(160deg, #ddeff7 0%, #cfe4f2 52%, #e8f5fb 100%)',
    pageBase: '#cfe4f2',
    boardBg: 'linear-gradient(155deg, #f9fdff, #e2f0f9)',
    frame: '#f9fdff',
    cell: 'linear-gradient(160deg, #f9fdff, #eef8fd)',
    cellAlt: 'linear-gradient(160deg, #e0eff8, #d3e6f3)',
    cellBorder: 'rgba(190, 217, 232, 0.75)',
    cellInk: '#5f8194',
    edge: ['#cfe4ef', '#bcd9e9', '#a8cde0', '#93bed4', '#7eb0c8'],
    dropShadow: 'rgba(20, 70, 100, 0.32)',
    ladder: { dark: '#9a7b45', light: '#e8cc95', foot: '#c2a068' },
    snake: { body: '#407b86', outline: '#1b414a', belly: '#c3dcd8', head: '#386d78' },
    accent: '#2b8ca6',
    accentDeep: '#1d6b80',
    pageTexture:
      "<svg xmlns='http://www.w3.org/2000/svg' width='120' height='60'><g stroke='#1c5f6a' stroke-opacity='0.1' stroke-width='1.6' fill='none' stroke-linecap='round'><path d='M0 16q15-10 30 0t30 0 30 0 30 0'/><path d='M0 40q15-10 30 0t30 0 30 0 30 0'/></g></svg>",
    pageTextureSize: '120px 60px',
    cellTextureSize: '40px 20px',
    photo: 'assets/textures/ocean.webp',
    photoPageSize: '440px',
    photoPageOpacity: 0.45,
    photoBoardSize: '190px',
    photoBoardOpacity: 0.15,
    motion: 'drift', driftAxis: 'x', driftDuration: '26s', boardDriftDuration: '38s',
    ornaments: ['🐚', '⭐', '🫧', '🐠', '🌊', '🦀'],
    life: { kind: 'bubble', count: 22, colors: ['#ffffff'] },
    backdrop: { landscape: 'assets/scenes/ocean-landscape.webp', portrait: 'assets/scenes/ocean-portrait.webp' },
    // The setup screen's picker swatch, painted to echo the backdrop photo.
    swatch: 'linear-gradient(118deg, #4fc2d2 0 36%, #b9ecef 49%, #f6f1e6 61%, #ece2d0)',
    ambience: 'shore',
    events: 'caustics',
    sunlight: 'rgba(225, 248, 255, 0.85)',
    startIcon: '⚓', finishIcon: '🏝️',
    cellTexture:
      "<svg xmlns='http://www.w3.org/2000/svg' width='40' height='20'><g stroke='#2f8f9c' stroke-opacity='0.1' stroke-width='1' fill='none' stroke-linecap='round'><path d='M0 10q10-6 20 0t20 0'/></g></svg>",
  },
  meadow: {
    label: 'Meadow',
    label_id: 'Taman bunga',
    page: 'radial-gradient(1100px 620px at 50% -12%, #f8fce9 0%, transparent 62%), radial-gradient(900px 520px at 92% 104%, #e0eec4 0%, transparent 58%), linear-gradient(160deg, #eff8dd 0%, #e6f2d4 52%, #f7fbe8 100%)',
    pageBase: '#e6f2d4',
    boardBg: 'linear-gradient(155deg, #fdfef7, #eef6dd)',
    frame: '#fdfef8',
    cell: 'linear-gradient(160deg, #fdfef7, #f6fbe8)',
    cellAlt: 'linear-gradient(160deg, #ecf6da, #e2efcb)',
    cellBorder: 'rgba(214, 230, 184, 0.75)',
    cellInk: '#77875c',
    edge: ['#e0ecc8', '#d3e4b6', '#c4daa4', '#b3cf90', '#a2c47c'],
    dropShadow: 'rgba(70, 90, 30, 0.3)',
    ladder: { dark: '#9c7b3a', light: '#ebcf88', foot: '#c0a05a' },
    snake: { body: '#8b9a3b', outline: '#474f1f', belly: '#e4e7aa', head: '#7e8d33' },
    accent: '#7ba337',
    accentDeep: '#5b7d26',
    pageTexture:
      "<svg xmlns='http://www.w3.org/2000/svg' width='100' height='100'><g stroke='#4f6b22' stroke-opacity='0.11' stroke-width='1.4' fill='none' stroke-linecap='round'><path d='M12 94c0-12 4-20 8-26'/><path d='M18 94c0-10-2-18-6-24'/><path d='M62 98c0-12 5-20 9-26'/><path d='M68 98c0-10-2-18-6-24'/><path d='M38 48c0-10 4-16 7-21'/><path d='M44 48c0-9-2-15-6-20'/></g></svg>",
    pageTextureSize: '100px 100px',
    cellTexture:
      "<svg xmlns='http://www.w3.org/2000/svg' width='24' height='24'><g fill='#5b7d26' fill-opacity='0.09'><circle cx='6' cy='7' r='1.4'/><circle cx='18' cy='16' r='1.2'/><circle cx='12' cy='3' r='1'/><circle cx='3' cy='19' r='1'/></g></svg>",
    cellTextureSize: '24px 24px',
    photo: 'assets/textures/meadow.webp',
    photoPageSize: '400px',
    photoPageOpacity: 0.42,
    photoBoardSize: '175px',
    photoBoardOpacity: 0.14,
    motion: 'drift', driftAxis: 'x', driftDuration: '42s', boardDriftDuration: '70s',
    ornaments: ['🌼', '🦋', '🌿', '🐞', '🌾', '🌷'],
    life: { kind: 'butterfly', count: 8, colors: ['#f2b233', '#e98a3a', '#f7e27a', '#9ec4f0'] },
    backdrop: { landscape: 'assets/scenes/meadow-landscape.webp', portrait: 'assets/scenes/meadow-portrait.webp' },
    // The setup screen's picker swatch, painted to echo the backdrop photo.
    swatch: 'radial-gradient(circle at 68% 30%, #fffdf0 0 8%, transparent 9%), radial-gradient(circle at 32% 68%, #ffe14f 0 8%, transparent 9%), linear-gradient(160deg, #acd672, #6fa83d)',
    ambience: 'meadow',
    events: 'clouds',
    sunlight: 'rgba(255, 249, 214, 0.9)',
    startIcon: '🌻', finishIcon: '🐝',
  },
  sunset: {
    label: 'Sunset',
    label_id: 'Senja',
    page: 'radial-gradient(1100px 620px at 50% -12%, #fff3e4 0%, transparent 62%), radial-gradient(900px 520px at 92% 104%, #f0d6ea 0%, transparent 58%), linear-gradient(160deg, #ffe9db 0%, #f8dde6 52%, #f4e2f2 100%)',
    pageBase: '#f8dde6',
    boardBg: 'linear-gradient(155deg, #fffaf3, #fbe9db)',
    frame: '#fffaf4',
    cell: 'linear-gradient(160deg, #fffaf3, #fef2e7)',
    cellAlt: 'linear-gradient(160deg, #fbe8da, #f7ddcc)',
    cellBorder: 'rgba(240, 214, 194, 0.75)',
    cellInk: '#a2806c',
    edge: ['#f5d9c4', '#efcbb2', '#e7bb9e', '#dca786', '#cf9370'],
    dropShadow: 'rgba(130, 60, 40, 0.32)',
    ladder: { dark: '#9c5a30', light: '#f4bf8c', foot: '#c98b55' },
    snake: { body: '#a8683f', outline: '#54301e', belly: '#f1d4b3', head: '#985a30' },
    accent: '#e2703a',
    accentDeep: '#b4531f',
    pageTexture:
      "<svg xmlns='http://www.w3.org/2000/svg' width='160' height='120'><g fill='#b4531f' fill-opacity='0.055'><ellipse cx='40' cy='28' rx='34' ry='9'/><ellipse cx='120' cy='76' rx='40' ry='10'/><ellipse cx='74' cy='104' rx='26' ry='7'/></g><g stroke='#b4531f' stroke-opacity='0.05' stroke-width='1.2' fill='none'><path d='M0 52h160'/><path d='M0 92h160'/></g></svg>",
    pageTextureSize: '160px 120px',
    cellTexture:
      "<svg xmlns='http://www.w3.org/2000/svg' width='20' height='20'><g fill='#9c5a30' fill-opacity='0.08'><circle cx='4' cy='5' r='1'/><circle cx='14' cy='12' r='1.1'/><circle cx='9' cy='17' r='0.9'/></g></svg>",
    cellTextureSize: '20px 20px',
    photo: 'assets/textures/sunset.webp',
    photoPageSize: '450px',
    photoPageOpacity: 0.42,
    photoBoardSize: '195px',
    photoBoardOpacity: 0.14,
    motion: 'drift', driftAxis: 'x', driftDuration: '75s', boardDriftDuration: '120s',
    ornaments: ['🌇', '🕊️', '☁️', '🌅', '🐦', '✨'],
    life: { kind: 'mote', count: 26, colors: ['#ffd9a0', '#ffc27a', '#fff0d0'] },
    backdrop: { landscape: 'assets/scenes/sunset-landscape.webp', portrait: 'assets/scenes/sunset-portrait.webp' },
    // The setup screen's picker swatch, painted to echo the backdrop photo.
    swatch: 'linear-gradient(172deg, #ffe0b0 0%, #f7ad6f 44%, #dc7c4c 70%, #b65c3b)',
    ambience: 'dunes',
    events: 'sand',
    sunlight: 'rgba(255, 214, 170, 0.9)',
    startIcon: '🌤️', finishIcon: '🌆',
  },
  night: {
    label: 'Night',
    label_id: 'Malam',
    // The one dark scene: white frost over it turns grey and unreadable, so the
    // UI glass flips to a dark tint with light text (see [data-glass] in style.css).
    glass: 'dark',
    page:'radial-gradient(1100px 620px at 50% -12%, #333c63 0%, transparent 62%), radial-gradient(900px 520px at 92% 104%, #3a2a5c 0%, transparent 58%), linear-gradient(160deg, #1e2438 0%, #262040 52%, #1a2032 100%)',
    pageBase: '#262040',
    boardBg: 'linear-gradient(155deg, #303858, #242a44)',
    frame: '#3c4468',
    cell: 'linear-gradient(160deg, #333c5e, #2c3452)',
    cellAlt: 'linear-gradient(160deg, #2a3150, #242b46)',
    cellBorder: 'rgba(90, 100, 145, 0.5)',
    cellInk: '#9aa4ca',
    edge: ['#262d4a', '#212843', '#1c223a', '#171d31', '#131828'],
    dropShadow: 'rgba(0, 0, 0, 0.55)',
    ladder: { dark: '#5f6890', light: '#cdd6f5', foot: '#98a1c8' },
    snake: { body: '#5a639b', outline: '#20264c', belly: '#c8cef1', head: '#4f588d' },
    accent: '#8b6ee8',
    accentDeep: '#6a4fd0',
    pageTexture:
      "<svg xmlns='http://www.w3.org/2000/svg' width='140' height='140'><g fill='#ffffff' fill-opacity='0.5'><circle cx='20' cy='28' r='1.3'/><circle cx='96' cy='18' r='1'/><circle cx='124' cy='62' r='1.4'/><circle cx='58' cy='76' r='1'/><circle cx='34' cy='112' r='1.2'/><circle cx='108' cy='120' r='1'/><circle cx='78' cy='44' r='0.8'/><circle cx='8' cy='66' r='0.9'/></g><g fill='#cbbcff' fill-opacity='0.6'><path d='M62 14l1.4 3.6L67 19l-3.6 1.4L62 24l-1.4-3.6L57 19l3.6-1.4z'/><path d='M116 92l1.2 3 3 1.2-3 1.2-1.2 3-1.2-3-3-1.2 3-1.2z'/></g></svg>",
    pageTextureSize: '140px 140px',
    cellTexture:
      "<svg xmlns='http://www.w3.org/2000/svg' width='30' height='30'><g fill='#9aa4ca' fill-opacity='0.18'><circle cx='7' cy='8' r='0.9'/><circle cx='22' cy='19' r='0.7'/><circle cx='16' cy='27' r='0.6'/></g></svg>",
    cellTextureSize: '30px 30px',
    photo: 'assets/textures/night.webp',
    photoPageSize: '480px',
    photoPageOpacity: 0.55,
    photoBoardSize: '210px',
    photoBoardOpacity: 0.20,
    motion: 'twinkle', driftAxis: 'x', driftDuration: '140s', boardDriftDuration: '190s', twinkleDuration: '4.5s',
    ornaments: ['✨', '🌙', '⭐', '🦉', '🌌', '🔭'],
    life: { kind: 'firefly', count: 26, colors: ['#f8f2a0', '#d8f59a', '#fff6c8'] },
    backdrop: { landscape: 'assets/scenes/night-landscape.webp', portrait: 'assets/scenes/night-portrait.webp' },
    // The setup screen's picker swatch, painted to echo the backdrop photo.
    swatch: 'radial-gradient(circle at 70% 28%, #fffbe0 0 5%, transparent 6%), radial-gradient(circle at 30% 62%, #cfd8ff 0 4%, transparent 5%), linear-gradient(160deg, #2e3868, #1b1d3c 60%, #0f1226)',
    ambience: 'night',
    events: 'stars',
    sunlight: 'rgba(170, 190, 255, 0.5)',
    startIcon: '🌠', finishIcon: '🌕',
  },
};

// The game is played in one of two modes, chosen on the setup screen. Mode
// decides which questions, dares and surprises are in play, and what the AI is
// told about who is sitting at the table — a group of friends should never be
// handed "give your partner a shoulder massage", and the model should never
// write a romantic prompt for people who aren't a couple.
const MODES = {
  couples: {
    label: 'Couples',
    label_id: 'Pasangan',
    hint: 'Questions and dares written for two partners.',
    hint_id: 'Pertanyaan sama tantangan khusus buat kalian berdua.',
    subject: 'Two partners are playing a board game designed to bring them closer together.',
    guard: '',
    points: 'Love Points',
  },
  friends: {
    label: 'Friends',
    label_id: 'Teman',
    hint: 'Nothing romantic — written for friends playing together.',
    hint_id: 'Nggak ada yang romantis-romantis — pas buat main bareng teman.',
    subject:
      'A group of friends is playing a board game designed to help them know each other better.',
    guard:
      'They are friends, not romantic partners. Never imply romance, dating, flirting or physical intimacy.',
    points: 'points',
  },
};

// `friendsLabel` renames a theme in Friends mode where the couples wording
// would be wrong. `color` marks the topic's swatch on its chip and question card.
const QUESTION_THEMES = {
  general: { label: 'General', label_id: 'Santai', color: '#3b7dd8' },
  love: { label: 'Love', label_id: 'Cinta', friendsLabel_id: 'Akrab', friendsLabel: 'Closeness', color: '#d6336c' },
  money: { label: 'Money', label_id: 'Duit', color: '#2f9e5b' },
  dreams: { label: 'Dreams', label_id: 'Impian', color: '#8b5fbf' },
  dare: { label: 'Fun & Dare', label_id: 'Tantangan', color: '#e08a2c' },
  deep: { label: 'Deep Talk', label_id: 'Deep talk', color: '#2c7a7b' },
  memories: { label: 'Memories', label_id: 'Kenangan', color: '#b5763a' },
  home: { label: 'Home & Family', label_id: 'Keluarga', color: '#4a7f9e' },
  growth: { label: 'Growth', label_id: 'Naik level', color: '#5c9e46' },
  gratitude: { label: 'Gratitude', label_id: 'Bersyukur', color: '#c2811f' },
  adventure: { label: 'Adventure', label_id: 'Petualangan', color: '#3d8f8f' },
  everyday: { label: 'Everyday', label_id: 'Sehari-hari', color: '#8a6a9e' },
};

// Each theme is `shared` (works for anyone at the table) plus one list per
// mode. The pool for a game is shared + that mode's list — see questionPool()
// in script.js. Splitting them this way rather than keeping two whole banks
// means the ~60% of questions that were already neutral are written once.
const QUESTIONS = {
  general: {
    shared: [
      "Okay, what's one skill we should totally learn together?",
      "What should we binge-watch together this month?",
      "If we swapped lives for a day, what's the first thing you'd do?",
      "Which of our inside jokes do you love the most?",
      "What surprised you about me when we first met?",
      "What song screams 'us' to you?",
      "Best meal we've ever had together — go.",
      "Which of my habits have you picked up without noticing?",
      "What's one small thing I could do this week that would make your day?",
      "Zombie apocalypse: who survives longer, and why?",
      "What's a tiny thing that instantly puts you in a good mood?",
      "If you could replay one totally normal day, which one would it be?",
      "What's one rule you think everybody should live by?",
      "What's the last thing you learned that kind of blew your mind?",
      "If you got a free extra hour today, what would you do with it?",
      "What do people always get wrong about you?",
      "What's a question you wish people asked you more often?",
      "What's the best advice you totally ignored?",
    ],
    couples: [
      "What's a little thing your partner does that always makes you smile?",
      "If we could go on a date anywhere right now, where are we going?",
      "What's something you find hilarious that your partner just doesn't get?",
      "If we got a pet tomorrow, what are we naming it?",
      "If our life was a movie, what genre would it be?",
      "What's your favorite spot in our place?",
      "Which of your partner's habits did you not expect to fall for?",
      "What do you two argue about that's actually kind of funny?",
      "What's a rule you two have that nobody else would get?",
      "If our relationship was a weather forecast today, what would it say?",
      "What do you do differently now that you're with your partner?",
      "Which chore have you quietly claimed as 'yours'?",
      "What did your partner do lately that you're still thinking about?",
      "If your partner narrated your life, what would the opening line be?",
      "What food could only your partner talk you into trying?",
      "What's a tiny tradition that's just yours as a couple?",
      "What would your partner say is your most annoying habit? Be honest.",
      "What's something you two used to disagree on but now totally agree on?",
      "What's the weirdest thing you two have bonded over?",
      "If you could freeze one ordinary moment with your partner, which one?",
      "What's a compliment you give your partner that you mean every single time?",
      "Which TV character reminds you most of your partner?",
      "What's your partner way better at than they realize?",
      "What's the most 'so us' thing you two have ever done?",
      "If our relationship had a theme song, what would it be?",
      "What's a small annoyance you'd happily put up with forever for your partner?",
      "What's something you've never told your partner but probably should?",
      "What's a nickname you secretly call your partner in your head?",
      "What's the best part of doing absolutely nothing together?",
      "What's that plan you two keep talking about but never actually do?",
      "What has your partner taught you without even trying?",
      "How do you love spending a lazy Sunday together?",
      "What's a running joke between you two that nobody else gets?",
      "What's one thing you want your partner to know before this game ends?",
    ],
    friends: [
      "What's your most useless talent? Show us.",
      "Who here are you calling first in an emergency, and why?",
      "What show would you make everyone here sit through?",
      "If we started a band tomorrow, who plays what?",
      "What's a rumor about you that turned out to be true?",
      "Who here has changed the most since you met them?",
      "What's a rule this group has that outsiders would find weird?",
      "Who here gives the worst directions — and why do we still follow them?",
      "What's the most chaotic plan this group actually pulled off?",
      "If this group had a group chat name, what should it be?",
      "What food does everyone here fight about?",
      "Who's most likely to reply to a 3am text from the group?",
      "What have you only ever laughed about with people in this room?",
      "If we all went on a game show together, which one?",
      "Honestly, who here has the worst taste in music?",
      "What tradition should this group actually start?",
      "Who does everyone secretly copy without admitting it?",
      "What's the most 'us' thing this group has ever done?",
      "If someone made a movie about this friend group, what genre?",
      "What little thing does someone here do that always cracks you up?",
      "Who here would last longest without their phone?",
      "Who here needs a nickname, and what should it be?",
      "What's this group's unofficial motto?",
      "Who's always late, and what's the usual excuse?",
      "What's the best part of doing absolutely nothing with this group?",
      "What's that plan we keep talking about but never actually do?",
      "Who here taught you something without even realizing it?",
      "What's your favorite way to spend a lazy day with this crew?",
      "What's a running joke here that nobody outside gets?",
      "What's one thing you want this group to know before tonight's over?",
      "Who's the designated planner here, whether they like it or not?",
      "What's the most trouble this group has ever gotten into?",
      "If this group had a mascot, what would it be?",
      "Who's the peacemaker when this group starts arguing?",
    ],
  },
  love: {
    shared: [
      "When you're sad, what actually helps you feel better?",
      "What's something you've never said out loud but want me to know?",
      "Give someone here a real compliment. Right now.",
      "How do we usually make up after a fight?",
      "What's one thing you never want us to stop doing together?",
      "What makes you feel loved that most people wouldn't guess?",
      "What does love look like on a random Tuesday?",
      "Who showed you what love's supposed to feel like?",
      "What's a small sweet gesture you never get tired of?",
      "What's something weird you connect with the word 'love'?",
      "How can you tell when someone really cares, not just being nice?",
      "What love language did you only recently find out you have?",
      "Is being loved different from being understood? How?",
      "When did you last feel totally loved, no explanation needed?",
      "What makes you feel a bit unlovable, even for a moment?",
      "How do you show love in a way people usually miss?",
      "What's the bravest thing you've ever done for love?",
      "What does loving someone on their worst day look like to you?",
    ],
    couples: [
      "What made you fall for your partner in the first place?",
      "Describe your partner in three words — out loud.",
      "What small thing makes you feel the most loved?",
      "What do you love most about how your partner treats you?",
      "When do you feel closest to your partner?",
      "What's one promise you want to make to each other tonight?",
      "When did you know you loved me?",
      "What's the best thing about us as a couple?",
      "How has loving me changed you?",
      "If our love was a color, what color and why?",
      "What does being loved by me feel like?",
      "When did you realize this relationship was different?",
      "What do you think your partner needs to hear more often?",
      "What's the most romantic thing your partner's done, even if it was tiny?",
      "How does your partner make bad days easier?",
      "What surprised you about loving your partner?",
      "What do you never want your partner to doubt about your love?",
      "What fear about love has your partner helped you get over?",
      "How has your idea of love changed since being with your partner?",
      "What soft side of your partner do only you get to see?",
      "What does your partner do that makes you feel chosen?",
      "How do you two show love without saying a word?",
      "If you could redo one thing in how you've loved your partner, what would it be?",
      "What part of your love story still gives you butterflies?",
      "What's the bravest thing love has asked of you in this relationship?",
      "How do you want to be loved when things go wrong?",
      "What's a quiet way your partner loves you that you've never mentioned?",
      "What does 'forever' mean to you in this relationship?",
      "What do you love about loving your partner — not just about them?",
      "When did your partner love you exactly as you were, flaws and all?",
      "How do you want our love to feel ten years from now?",
      "How does your partner love you better than anyone before?",
      "What do you hope your partner never forgets about how much you love them?",
      "What has loving your partner taught you about yourself?",
    ],
    friends: [
      "When did you decide I was a real friend, not just someone you knew?",
      "Describe me in three words — out loud.",
      "What do you need from a friend but find hard to ask for?",
      "When have you felt most looked after by someone here?",
      "What do you appreciate about me that I probably don't know?",
      "What makes someone a good friend, in your book?",
      "Who here would you want next to you on your worst day?",
      "What's the kindest thing anyone here has done for you?",
      "When did you realize this friendship was different?",
      "What do you think I need to hear more often?",
      "What's the kindest thing someone here did without being asked?",
      "How does this group make bad days easier?",
      "What surprised you about caring for the people here?",
      "What do you never want people here to doubt about your loyalty?",
      "What fear about friendship has someone here helped you get over?",
      "How has your idea of a good friend changed over the years?",
      "What soft side of you do only close friends get to see?",
      "What do people here do that makes you feel chosen?",
      "How do friends show they care without saying it?",
      "If you could redo one thing in how you've shown up for a friend, what would it be?",
      "What friendship memory still gives you that warm feeling?",
      "What's the bravest thing friendship has asked of you?",
      "When things go wrong for you, how do you want your friends to show up?",
      "What's a quiet way someone here cares for you that you've never mentioned?",
      "What does 'ride or die' mean in this group?",
      "What do you love about caring for people — not just about them?",
      "When did someone here accept you exactly as you were, flaws and all?",
      "How do you want this friendship to feel ten years from now?",
      "How has someone here shown up for you better than anyone before?",
      "What do you hope this group never forgets about how much you care?",
      "What has this friendship taught you about yourself?",
      "Who here would you trust with something you've never told anyone?",
      "How has this group taught you to love people better?",
      "What do you appreciate that nobody here has ever said out loud?",
    ],
  },
  money: {
    shared: [
      "Which money habit from your family are you keeping — and which one's gotta go?",
      "What does feeling safe with money look like for you?",
      "You get a big chunk of cash tomorrow: save it, spend it, or split it?",
      "What fun thing would you happily overspend on?",
      "What's the best money move you've ever made?",
      "What money talk do you keep putting off?",
      "What skill would you actually pay good money to learn?",
      "What's a pricey thing you bought and zero regrets?",
      "Is money more about freedom or security for you?",
      "What money habit did you pick up from watching someone else struggle?",
      "Right now, would you rather have more time or more money?",
      "What's the most impulsive thing you've ever bought?",
      "What subscription do you keep meaning to cancel?",
      "What does 'rich' actually mean to you — besides the number?",
      "What would you never cut from your budget, no matter what?",
      "What money lesson did you learn the hard way?",
      "Secretly loaded or openly comfortable — which would you pick?",
      "What's the cheapest thing that made you ridiculously happy?",
    ],
    couples: [
      "What's one money goal we should set this year?",
      "If we had an extra $500 this month, what are we doing with it?",
      "Which of your partner's money habits do you actually like?",
      "Honestly, how do you feel about our savings plan?",
      "What big thing should we start saving for?",
      "Are we on the same page about splitting bills?",
      "What could we cut back on to save for something bigger?",
      "Where do you see us money-wise in five years?",
      "Are we saving enough for fun, or too focused on later?",
      "Should we each get some 'no questions asked' spending money?",
      "What did you buy that your partner still doesn't get?",
      "How do we handle a big surprise expense together?",
      "What money thing are you proud we figured out together?",
      "Do we feel like a team with money yet, or still figuring it out?",
      "What money conversation have we been dodging?",
      "What would you do differently if we merged all our money tomorrow?",
      "What pricey thing would you love us to save up for as a couple?",
      "How do you feel about surprise gifts that cost real money?",
      "Honest reaction: me making a big purchase without asking first?",
      "Which of my money habits would you gently change?",
      "What shared money goal would make you really proud of us?",
      "Retire early and live simple, or work longer and live big?",
      "What's the most generous thing you've seen me do with money?",
      "What if one of us ends up earning way more than the other?",
      "What do we spend on that's worth every cent?",
      "What money worry do you have that I might not know about?",
      "What money win should we have celebrated more?",
      "How do we want to teach our future selves — or kids — about money?",
      "What would you give up money-wise for us, no questions asked?",
      "What's something we should buy together, not separately?",
      "Debt: avoid at all costs, or just a normal tool?",
      "What money habit are you trying to break for us?",
      "What would 'enough' money look like for our life together?",
      "What's the most romantic thing anyone's ever done with money, in your opinion?",
    ],
    friends: [
      "Splitting the bill with friends: easy, or low-key awkward?",
      "Would you lend a friend money?",
      "What's the most you've spent on something nobody else understood?",
      "Do your friends roughly know how much you earn?",
      "If money fell from the sky tomorrow, what trip are we taking?",
      "What did you waste money on at 20 that you'd never buy now?",
      "What did you buy that your friends still don't get?",
      "How do you feel when a friend suddenly has way more money than you?",
      "What money thing are you proud you figured out on your own?",
      "What money conversation have you dodged with a friend?",
      "Would you ever lend a big amount to someone in this room?",
      "What pricey thing would you want to save up for with people here?",
      "Chipping in for a group gift — love it or hate it?",
      "Honest reaction when a friend buys something big you never would?",
      "Which friend's money habit would you gently change?",
      "What group goal would take real money to pull off?",
      "Retire early and live simple, or work longer and live big?",
      "What's the most generous thing you've seen someone here do with money?",
      "What should friends do when one earns way more than the rest?",
      "What does this group spend on that's worth every cent?",
      "What money worry do you have that people here might not know about?",
      "What money win of yours deserved a bigger celebration?",
      "What would you give up money-wise for a friend, no questions asked?",
      "What would you only buy if someone here talked you into it?",
      "Debt: avoid at all costs, or just a normal tool?",
      "What money habit are you trying to break right now?",
      "What would 'enough' money look like for your life?",
      "What's the most generous gift you've given someone in this room?",
      "Who here's most likely to get rich, and how?",
      "What money mistake would you warn everyone here about?",
      "Everyone here knows your salary, or nobody ever does — pick one.",
      "What's the best free thing this group has ever done?",
      "What splurge would you only justify with this group?",
      "If this group started a business, who's handling the money?",
    ],
  },
  dreams: {
    shared: [
      "What skill do you want to be really good at before you're 60?",
      "If money didn't matter, how would you spend next year?",
      "What would a perfect, totally normal Tuesday look like for you?",
      "What dream did you give up on that you'd love to pick back up?",
      "What adventure haven't we tried yet that you're dying to?",
      "If we could live in another country for a year, where and why?",
      "What's on your list that we should do together this year?",
      "If we started a business together, what would it be?",
      "What's a dream you've never told anyone about?",
      "If you could master any skill overnight, what are you picking?",
      "What future version of yourself are you excited to become?",
      "What would you regret never trying?",
      "With unlimited courage for one day, what would you do?",
      "What dream scares you a little because it actually matters?",
      "What bucket-list thing could you actually do this year?",
      "What would you do if you weren't scared of failing?",
      "What childhood dream still quietly matters to you?",
      "If success was guaranteed, what would you finally go for?",
    ],
    couples: [
      "What's a dream trip you want us to take someday?",
      "Where do you picture us living in ten years?",
      "What does your dream life with your partner look like?",
      "What tradition should we start as a couple?",
      "What do you hope never changes about us?",
      "What goal are you working on that you'd love your partner's help with?",
      "What kind of old couple do you want us to be?",
      "What do you want people saying about us in 30 years?",
      "What's a dream you haven't fully shared with your partner yet?",
      "How can your partner back you up on a goal you're chasing right now?",
      "What do you dream of building together, not just experiencing?",
      "If we designed our dream home from scratch, what's non-negotiable?",
      "What version of 'us' in ten years excites you the most?",
      "What dream did you drop that your partner could help you pick back up?",
      "What do you want the two of us to leave behind?",
      "What do you want us to pull off together before a certain age?",
      "What shared dream feels a bit out of reach right now?",
      "Realistically, how do you want us to grow old together?",
      "What's your partner's dream that you really want to help make happen?",
      "What risk would we take together if failing wasn't possible?",
      "What does your ideal retirement with your partner look like?",
      "What skill do you wish you two could learn together?",
      "Where do you dream of calling home together someday?",
      "What's something about our future you've never said out loud?",
      "Sum up our shared dream in one sentence.",
      "Which of your partner's goals do you quietly cheer for the most?",
      "What dream for this relationship haven't you dared to say yet?",
      "What would we build together if money and time weren't a thing?",
      "What kind of adventure do you want your partner to experience with you?",
      "When you forget your dreams, how should your partner remind you?",
      "What do you hope we're still dreaming about together in 20 years?",
      "What dream are you scared to admit you want?",
      "What promise about our future would you make right now?",
      "What's one thing we have to do together before it's too late?",
    ],
    friends: [
      "Where do you want to be living in ten years — and who's nearby?",
      "What trip should this group actually book instead of just talking about?",
      "What do you want to be known for by the people who know you?",
      "What goal are you working on that someone here could help with?",
      "What kind of old person do you want to be?",
      "What tradition should this group start?",
      "What do you hope never changes about your friends?",
      "What's a dream you haven't fully shared with anyone here yet?",
      "How can this group back you up on a goal you're chasing right now?",
      "What would you love to build with people here, not just experience?",
      "If this group started a project from scratch, what would it be?",
      "What version of this friend group in ten years excites you most?",
      "What dream did you drop that someone here could help you pick back up?",
      "What do you want this friend group to leave behind?",
      "What do you want to achieve by a certain age, with this group cheering you on?",
      "What group dream feels a bit out of reach right now?",
      "How do you want to stay close to this group as you get older?",
      "Whose dream here do you really want to help make happen?",
      "What risk would you take with this group if failing wasn't possible?",
      "What does your ideal reunion with this group look like in 20 years?",
      "What skill do you wish this group could learn together?",
      "Where do you dream of getting this whole group together someday?",
      "What's something about your future you've never told anyone here?",
      "Sum up your biggest dream in one sentence.",
      "Whose goal here do you quietly cheer for the most?",
      "What dream for this friendship haven't you dared to say yet?",
      "What would you build with this group if money and time weren't a thing?",
      "What kind of adventure do you want to have with people here?",
      "When you forget your dreams, how should this group remind you?",
      "What do you hope you're still doing with this group in 20 years?",
      "What dream are you scared to admit you want?",
      "What promise about the future would you make to this group right now?",
      "What's one thing you have to do with this group before it's too late?",
      "Whose dream here deserves way more support than it's getting?",
    ],
  },
  dare: {
    shared: [
      "Take the silliest selfie together. Right now.",
      "Swap phones and change each other's wallpaper.",
      "Sing the chorus of a song everyone here knows.",
      "Talk for 30 seconds about something you love. No 'umm' allowed.",
      "Talk in an accent until your next turn.",
      "Bust out your best dance move for 10 seconds. No excuses.",
      "Say the alphabet backwards. Everyone's watching.",
      "Let the others pick a silly nickname for you for the rest of the game.",
      "Try to lick your elbow. Just try.",
      "Do a celebrity impression until someone guesses who it is.",
      "Balance something on your head for 15 seconds.",
      "Send a random emoji to the last person you texted. No explaining.",
      "Hold a plank for 20 seconds while telling a joke.",
      "Let someone else do your hair for the next round.",
      "Only talk in questions until your next turn.",
      "Act out how you woke up this morning.",
      "Show the weirdest photo in your camera roll.",
      "Freeze in a dramatic pose for 10 seconds. No laughing.",
    ],
    couples: [
      "Give your partner a 10-second hug. Right now.",
      "Do your best impression of your partner.",
      "Say 'I love you' in a ridiculous accent.",
      "Whisper something sweet in your partner's ear.",
      "Slow dance for 15 seconds. Music optional.",
      "Feed your partner a snack or give them a sip of your drink.",
      "Act out how you two met, movie-scene style.",
      "Hold hands and stare into each other's eyes for 20 seconds. Don't laugh.",
      "Compliment your partner using only your hands. No talking.",
      "Give your partner a 30-second shoulder massage.",
      "Make your partner laugh in 15 seconds without touching them.",
      "Sing the chorus of 'your' song together.",
      "Draw something on your partner's palm with your finger. They guess.",
      "Say three things you love about your partner — no repeating words.",
      "Recreate your first photo together, pose and all.",
      "Trace your partner's name on their back. They have to guess it.",
      "Give your partner a nickname based on how they acted today.",
      "Tell your partner the exact moment you knew you wanted to date them.",
      "Do a 10-second slow-mo replay of how you met.",
      "Let your partner pick your outfit for tomorrow, no vetoes.",
      "Serenade your partner with the worst song you can think of. Straight face.",
      "Look your partner in the eye and tell them one thing you adore about them.",
      "Draw a heart on your hand and 'give' it to your partner.",
      "Whisper your favorite memory of your partner in their ear.",
      "Act out your partner's morning routine — exaggerate it.",
      "Hold eye contact with your partner for three seconds, then kiss their hand.",
      "Guess what your partner's thinking right now, out loud.",
      "Tell your partner one thing about them that's funny, one that's hot, and one that feels like home.",
      "Copy your partner's signature facial expression.",
      "Give your partner a heartfelt toast, wedding-speech style.",
      "Let your partner pick the next question topic for both of you.",
      "Do your partner's laugh as accurately as you can.",
      "Hold hands and describe your partner's hands out loud. Be nice.",
      "Tell your partner what you'd miss most about them after a week apart.",
    ],
    friends: [
      "Do your best impression of someone in this room.",
      "Show the last photo in your camera roll and explain it.",
      "Say three genuine things about the player on your right. No repeats.",
      "Read your last sent message out loud, super dramatically.",
      "Do 10 push-ups or tell an embarrassing story. Choose now.",
      "Let someone here pick the next song. No complaining.",
      "Make the whole group laugh in 15 seconds without saying a word.",
      "Let the player on your left give you a new nickname for the rest of the game.",
      "Reenact how you met the player on your right — exaggerate it.",
      "Guess the last thing someone here searched on their phone.",
      "Give the player across from you a nickname based on tonight.",
      "Act out how someone here reacts when they lose.",
      "Tell the group the real reason you were late last time.",
      "Let the group pick your profile picture for a week.",
      "Do your best impression of the group's biggest drama queen.",
      "Guess exactly how someone would react if you told them a secret right now.",
      "Draw the person across from you in 15 seconds.",
      "Whisper the nicest thing you can think of to the person on your left.",
      "Act out how someone here orders at a restaurant.",
      "Give a heartfelt toast to this group, reunion-style.",
      "Guess what someone here is thinking right now, out loud.",
      "Tell the group one thing about you they'd never guess.",
      "Do someone's catchphrase, perfectly.",
      "Let the group choose your nickname for the rest of the night.",
      "Do the loudest laugh of someone in this room.",
      "Hold out your hand and let someone here read your palm. Badly.",
      "Tell the group what you'd miss most about them after a month apart.",
      "Pick someone and say the first word that pops into your head about them.",
      "Do your worst impression of yourself.",
      "Let someone here answer your next question for you.",
      "Show the group your camera roll from the last 24 hours.",
      "Give a one-sentence toast to the person on your right.",
      "Reenact your last argument with anyone — for laughs.",
      "Let the group vote on a new nickname for you. No vetoes.",
    ],
  },
  deep: {
    shared: [
      "What does 'home' mean to you, really?",
      "What part of yourself are you still working on?",
      "When you're stressed, how do you actually like to be helped?",
      "What does forgiving someone mean to you?",
      "How do you want people to treat you when you mess up?",
      "What's been hard for you lately?",
      "What do you want to remember about this chapter of your life?",
      "When did you last feel really understood?",
      "What are you carrying around that nobody knows about?",
      "What does peace feel like in your body?",
      "What belief about yourself are you trying to unlearn?",
      "When do you feel the most like yourself?",
      "What did you need to hear as a kid but never did?",
      "What's a fear you've never said out loud?",
      "What does truly trusting someone mean to you?",
      "What are you quietly grieving right now?",
      "What do you wish people got about how your mind works?",
      "What moment changed how you see yourself?",
    ],
    couples: [
      "What's been hard for you lately that I could help with?",
      "Do you have any worries about us?",
      "What do you need more of from me lately?",
      "How have you grown since we got together?",
      "Is there anything unsaid between us you want to talk about?",
      "What has being with me taught you about love?",
      "What are you scared to ask me for?",
      "What from your past still shapes how you love?",
      "What should I remember if we ever have a really bad fight?",
      "What part of yourself have you only ever shown your partner?",
      "What are you scared of losing in this relationship?",
      "How has your partner helped you understand yourself better?",
      "What old wound from before us still pops up sometimes?",
      "What do you need from me on your worst days?",
      "What have you forgiven me for that we never talked about?",
      "What does feeling safe with me actually feel like?",
      "What truth about yourself are you still scared to tell me?",
      "When you're grieving something, how do you want me to show up?",
      "What about love still scares you, even now?",
      "What part of you do you think I still don't fully get?",
      "What moment with me changed how you see yourself?",
      "What do you need to hear from me that I don't say enough?",
      "What are you proud you got through, with my help?",
      "What does feeling truly known by someone mean to you?",
      "What side of you are you afraid I'll eventually see?",
      "What do you wish I understood about how your mind works during a fight?",
      "What did you need from a partner that took you a while to ask for?",
      "When words don't help, how do you want to be comforted?",
      "What fear about our future haven't you said out loud?",
      "What does 'unconditional' look like day to day?",
      "What are you still healing from that shows up in how you love?",
      "What do you want me to never give up on, even when it's hard?",
      "When have I made you feel the safest?",
      "What's something true about you that only I really know?",
    ],
    friends: [
      "Is there anything unsaid between you and anyone here?",
      "What do you need more of from your friends lately?",
      "What are you scared to ask people for?",
      "How have you changed since this group met you?",
      "What friendship did you lose that you still think about?",
      "What's the hardest thing for you to say out loud?",
      "When do you feel lonely even with people around?",
      "If someone here upset you, what should they do?",
      "What part of yourself have you only shown close friends?",
      "What are you scared of losing in this friendship?",
      "How has this friendship helped you understand yourself better?",
      "What old wound from before this group still pops up sometimes?",
      "What do you need from friends on your worst days?",
      "What have you forgiven someone here for that was never talked about?",
      "What does feeling safe with people here actually feel like?",
      "What truth about yourself are you still scared to tell this group?",
      "When you're grieving something, how do you want people here to show up?",
      "What about friendship still scares you, even now?",
      "What part of you do you think this group still doesn't fully get?",
      "What moment with someone here changed how you see yourself?",
      "What do you need to hear from this group that doesn't get said enough?",
      "What are you proud you got through, with someone here's help?",
      "What does feeling truly known by a friend mean to you?",
      "What side of you are you afraid this group will eventually see?",
      "What do you wish this group understood about how your mind works during a fight?",
      "What did you need from a friend that took you a while to ask for?",
      "When words don't help, how do you want to be comforted?",
      "What fear about the future of this friendship haven't you said out loud?",
      "What does unconditional support look like day to day?",
      "What are you still healing from that shows up in how you are with friends?",
      "What do you want this group to never give up on, even when it's hard?",
      "When has someone here made you feel the safest?",
      "What's something true about you that only close friends really know?",
      "What rough patch did someone here help you through without even realizing?",
    ],
  },
  memories: {
    shared: [
      "What's the most spontaneous thing we've ever done together?",
      "What did you think of me the very first time you saw me?",
      "What tiny, normal moment with me do you still remember?",
      "What trip of ours do you still think about?",
      "What was our best celebration ever?",
      "What did we used to do that we should totally bring back?",
      "What story about us do you love telling people?",
      "What moment with me would you love to relive?",
      "What's your earliest memory of me?",
      "What memory still makes you laugh out loud every time?",
      "What smell or sound instantly takes you back to a memory of us?",
      "What photo of us is the most 'us', and why?",
      "What memory didn't feel special until later?",
      "What did we do once and never talk about again?",
      "What memory of us would surprise people who only know us now?",
      "What's the last thing you want to think about before you fall asleep tonight?",
      "What memory of me have you never actually told me about?",
      "What stretch of our time together would you relive exactly as it was?",
    ],
    couples: [
      "What's your favorite memory from our first few months?",
      "What's your favorite photo of us?",
      "Tell the story of our first date — your version.",
      "What's the hardest thing we've been through?",
      "What's the funniest fight we've ever had?",
      "Which gift from me meant the most to you?",
      "When did you first feel like we were a real team?",
      "What's the first thing you told your friends about me?",
      "When did this relationship first feel serious?",
      "What fight can you laugh about now?",
      "When were you the most nervous around your partner?",
      "What memory of your partner have you never told anyone?",
      "What's the best surprise your partner ever pulled off?",
      "When did your partner prove they really know you?",
      "What's the silliest thing you two ever fought about?",
      "What hard time made you love your partner even more?",
      "What's the most spontaneous thing you two have done?",
      "What memory of your partner's family stuck with you?",
      "What's the first compliment your partner ever gave you?",
      "What memory still gives you butterflies?",
      "What's your biggest 'this is it' moment with your partner?",
      "What do you remember about getting ready for a date together?",
      "What's the funniest thing that went wrong on a trip together?",
      "When did you two comfort each other in a way you're proud of?",
      "When did you know your partner's friends liked you?",
      "What do you remember about meeting your partner's family?",
      "What's the best 'nothing special' day you've had together?",
      "What memory still feels like a movie scene?",
      "When did you realize you'd choose your partner all over again?",
      "When did your partner surprise you with how well they know you?",
      "What's your favorite gift-giving moment between you two?",
      "What memory do you never want to forget?",
      "What memory best sums up why you love your partner?",
      "What memory do you two still argue about the details of?",
    ],
    friends: [
      "What's your favorite memory with someone in this room?",
      "Tell the story of how you met someone here — your version.",
      "What's the funniest thing that's ever happened to this group?",
      "What's the worst idea we all went along with?",
      "What photo of us would you never delete?",
      "When did you first feel like you really belonged in this group?",
      "What did you think of me before you actually knew me?",
      "What night should none of us have survived?",
      "When did you first feel like this friendship would last?",
      "What fight can you laugh about now?",
      "When were you the most nervous meeting someone here?",
      "What memory of someone here have you never told anyone?",
      "What's the best surprise someone here ever pulled off?",
      "When did someone here prove they really know you?",
      "What's the silliest thing this group ever argued about?",
      "What hard time made you appreciate this group more?",
      "What's the most spontaneous thing this group has done?",
      "What memory of someone's family stuck with you?",
      "What's the first compliment someone here ever gave you?",
      "What memory still makes you smile?",
      "What's your biggest 'real friends' moment with this group?",
      "What do you remember about getting ready for a night out together?",
      "What's the funniest thing that went wrong on a trip with this group?",
      "When did you all comfort each other in a way you're proud of?",
      "When did you know you truly belonged here?",
      "What do you remember about meeting someone's family for the first time?",
      "What's the best 'nothing special' day you've had with this group?",
      "What memory still feels like a movie scene?",
      "When did you realize you'd choose this friendship all over again?",
      "When did someone surprise you with how well they know you?",
      "What's the best gift-giving moment in this group?",
      "What memory do you want this group to never forget?",
      "What memory best sums up why this group matters to you?",
      "What memory do you all still argue about the details of?",
    ],
  },
  home: {
    shared: [
      "What does a perfect weekend at home look like for you?",
      "Which chore do you secretly not mind?",
      "What childhood tradition do you want to keep going?",
      "What about how I grew up explains a lot about me?",
      "If we threw a dinner party tomorrow, who's on the guest list?",
      "What does a chill morning look like for you?",
      "What would you change about your daily routine if you could?",
      "How much people time versus alone time do you actually need?",
      "What smell instantly says 'home' to you?",
      "What rule from your childhood home have you kept — or broken?",
      "What's the messiest your room has ever gotten, and why?",
      "Describe your dream home in one sentence.",
      "What's in your place that has a story behind it?",
      "What home habit of yours turned out to be weird once someone pointed it out?",
      "What does feeling settled somewhere actually look like for you?",
      "What house did you visit once that you still think about?",
      "What's the loudest your household ever gets, and over what?",
      "What little ritual makes any place feel like home?",
    ],
    couples: [
      "How do we split the chores nobody notices?",
      "What would make our place feel more like 'ours'?",
      "How do you want holidays to feel for us?",
      "What should we do when one of us needs some space?",
      "What do you wish we did more at home?",
      "Who in my family are you closest to?",
      "What boundary with family do we need to set?",
      "How do you want us to handle guests at our place?",
      "What little thing about our place makes it feel like 'ours'?",
      "What chore would you take off my plate forever if you could?",
      "Honestly, what do you think of how we've decorated?",
      "What home argument of ours seems silly now?",
      "How do you want guests to feel at our place?",
      "How do you feel about how we spend our evenings at home?",
      "Which of my habits at home do you secretly find cute?",
      "What would you change about our mornings together?",
      "Which of my family traditions have you made your own?",
      "What's our ideal rainy day indoors?",
      "What about my family helped you understand me better?",
      "How do you want our home to feel different from the ones we grew up in?",
      "What house rule should we make official?",
      "What's your favorite sound in our home?",
      "What should we do more at home, just the two of us?",
      "What's the best lazy 'do-nothing' day we've had at home?",
      "Which chore do you low-key resent doing alone?",
      "What do you love — or hate — about hosting together?",
      "What moving-in-together memory still makes you laugh?",
      "If money was no issue, what one home upgrade would you make?",
      "What small thing I do at home makes you feel taken care of?",
      "How involved do you want our families to be in our home life?",
      "What boundary with in-laws should we set together?",
      "What's your version of a perfect Sunday at home?",
      "What about how I keep house would you gently change?",
      "What corner of our place feels the most 'you'?",
    ],
    friends: [
      "Whose place does this group always end up at, and why?",
      "What's your family like when everyone's in one room?",
      "What do you wish your friends knew about where you grew up?",
      "Are you usually the host or the guest?",
      "What family tradition would you bring into this group?",
      "Who in your family would get along best with people here?",
      "What's the one house rule you'd never break?",
      "What little thing about someone's place makes it so 'them'?",
      "What chore would you never volunteer for when crashing at someone's place?",
      "Honestly, what do you think of how someone here decorates?",
      "What argument at a shared place seems silly now?",
      "How do you want a friend's place to feel when you visit?",
      "Crashing at someone's place without warning — cool or not cool?",
      "What roommate or friend habit do you secretly find cute?",
      "What would you change about how this group hangs out at someone's place?",
      "What family tradition of yours would you share with this group?",
      "What's this group's ideal rainy day indoors?",
      "What about someone's family helped you understand them better?",
      "How do you want our hangouts to feel different from the ones you grew up with?",
      "What house rule should this group make official?",
      "What's your favorite sound from a place that feels like home?",
      "What should this group do more — just chilling at someone's place?",
      "What's the best lazy 'do-nothing' day you've had at someone's place?",
      "What chore do you low-key resent when you're hosting?",
      "What do you love — or hate — about hosting this group?",
      "What sleepover or hangout memory still makes you laugh?",
      "If money was no issue, what one home upgrade would you make?",
      "What small thing does a friend do at their place that makes you feel welcome?",
      "How involved do you want your family to be in your friendships?",
      "What boundary with roommates or family should this group respect?",
      "What's your version of a perfect Sunday hangout?",
      "What about how someone here keeps house surprised you?",
      "What corner of someone's place feels the most 'them'?",
      "If you had to pick, whose place would you least want to leave?",
    ],
  },
  growth: {
    shared: [
      "What are you proud of yourself for this year?",
      "How have you changed in the last five years?",
      "What used to scare you that doesn't anymore?",
      "What do you want to be better at a year from now?",
      "What have you totally changed your mind about?",
      "Where do you feel stuck right now?",
      "What does success mean to you these days?",
      "What habit would make your life way better if you actually stuck with it?",
      "What do you want to try but feel too old or too late for?",
      "What part of your work actually gives you energy?",
      "When did you last do something that scared you?",
      "What do you need to say no to more often?",
      "What would ten-years-ago you think of you now?",
      "What mistake taught you more than any win ever did?",
      "What used to embarrass you that doesn't anymore?",
      "What old version of yourself are you glad you let go of?",
      "What's the hardest thing you've had to unlearn?",
      "What compliment about how you've grown would you love to hear right now?",
    ],
    couples: [
      "What feedback from me has actually helped you?",
      "What feedback do you wish I gave a bit more gently?",
      "How do you want me to help keep you on track?",
      "What have you changed about yourself because of this relationship?",
      "What habit did your partner help you build without lecturing?",
      "What version of you has your partner never met — and are they missing out?",
      "What are you working on that your partner doesn't fully know about?",
      "Has your partner made you more patient — or less?",
      "What compliment about how you've grown would you love to hear from your partner?",
      "What do you handle better now than when you two first met?",
      "What fear have you gotten over partly thanks to your partner?",
      "How does your partner push you to be better, even when it stings?",
      "What does your partner do that quietly makes you a better person?",
      "What belief about relationships have you unlearned since being with your partner?",
      "What goal did you set because your partner believed you could do it?",
      "What did you use to struggle with that your partner helped you through?",
      "How do you want us to grow together this next year?",
      "Who are you trying to become that your partner already sees in you?",
      "What hard truth from your partner ended up helping you?",
      "What are you proud you didn't give up on, with your partner's support?",
      "How has this relationship made you grow up?",
      "What skill have you picked up just from being around your partner?",
      "What are you two better at now when it comes to fighting?",
      "How has your partner stretched your comfort zone for the better?",
      "What are you still working on that you need your partner's patience with?",
      "When did your partner see potential in you before you saw it yourself?",
      "What habit did you drop that your partner is secretly grateful for?",
      "What do you want to get better at for your partner's sake, not just yours?",
      "How has being loved made you braver?",
      "What personal win did your partner notice that you should've celebrated more?",
      "What have you forgiven yourself for, with your partner's help?",
      "How has your partner taught you to be kinder — even to yourself?",
      "What mistake in this relationship did you grow the most from?",
      "What's the biggest way you want us to grow together this year?",
    ],
    friends: [
      "What's the most useful thing a friend has told you about yourself?",
      "Who here would tell you the truth when nobody else would?",
      "What do you want your friends to hold you accountable for?",
      "What have you changed about yourself because of this friend group?",
      "What habit did a friend help you build without lecturing?",
      "What version of you has this group never met — and are they missing out?",
      "What are you working on that people here don't fully know about?",
      "Has this group made you more patient — or less?",
      "What compliment about how you've grown would you love to hear from someone here?",
      "What do you handle better now than when this group first met?",
      "What fear have you gotten over partly thanks to someone here?",
      "How does this group push you to be better, even when it stings?",
      "What does a friend do that quietly makes you a better person?",
      "What belief about friendship have you unlearned because of this group?",
      "What goal did you set because someone here believed you could do it?",
      "What did you use to struggle with that this group helped you through?",
      "How do you want to grow alongside this group this next year?",
      "Who are you trying to become that this group already sees in you?",
      "What hard truth from someone here ended up helping you?",
      "What are you proud you didn't give up on, with this group's support?",
      "How has this friendship made you grow up?",
      "What skill have you picked up just from hanging out with this group?",
      "What are you better at now when it comes to disagreements, thanks to this group?",
      "How has someone here stretched your comfort zone for the better?",
      "What are you still working on that you need this group's patience with?",
      "When did someone here see potential in you before you saw it yourself?",
      "What habit did you drop that this group is secretly grateful for?",
      "What do you want to get better at for this group's sake, not just yours?",
      "How has having these people around made you braver?",
      "What personal win did someone here notice that you should've celebrated more?",
      "What have you forgiven yourself for, with this group's help?",
      "How has this group taught you to be kinder — even to yourself?",
      "What mistake in this friendship did you grow the most from?",
      "What's the biggest way you want to grow with this group this year?",
    ],
  },
  gratitude: {
    shared: [
      "What are you thankful for today?",
      "Who outside this room are you grateful for?",
      "What tough thing happened that you're actually glad about now?",
      "What about your body are you thankful for?",
      "Name three good things that happened this week.",
      "Who taught you something you're still thankful for?",
      "What about right now is worth being grateful for?",
      "What part of my personality are you glad I have?",
      "What did you learn from me that you're grateful for?",
      "What ordinary thing would you miss the most if it vanished?",
      "Who have you never properly thanked?",
      "What comfort in your life do you take for granted?",
      "What specifically about today are you grateful for?",
      "What rough patch ended up giving you something good?",
      "What talent of yours are you quietly thankful for?",
      "What small thing did someone do for you lately that you really appreciated?",
      "What place are you grateful exists in your life?",
      "What about your own resilience are you thankful for?",
    ],
    couples: [
      "What's one thing you're thankful for about us right now?",
      "What do I do that you've never really thanked me for?",
      "What little comfort in our life do you never want to lose?",
      "What did I do this week that made your life easier?",
      "What are you grateful your partner puts up with about you?",
      "What in our home are you most glad we have?",
      "What's actually good about the way we argue?",
      "What about your partner's patience are you thankful for?",
      "What hard time together are you now grateful we went through?",
      "What does your partner do every day that you've never properly thanked them for?",
      "How has your partner made you a better person?",
      "What has your partner's family given you that you're thankful for?",
      "What comfort does your partner give you that you'd be lost without?",
      "What about this relationship don't you say thank you for enough?",
      "What sacrifice did your partner make for you that you're really grateful for?",
      "What did your partner teach you that you're glad you learned?",
      "How does your partner show up that you never want to take for granted?",
      "Which of your partner's flaws are you weirdly grateful for?",
      "When did your partner's support mean more than they knew?",
      "What moment in your life together would you freeze out of pure gratitude?",
      "What quality in your partner do you wish you thanked them for more?",
      "What about how your partner argues are you secretly grateful for?",
      "How has your partner made your family better — or the other way around?",
      "What money sacrifice did your partner make that you're thankful for?",
      "What about growing older with your partner are you already grateful for?",
      "What hard truth from your partner are you thankful for now?",
      "What at home are you most thankful your partner brings?",
      "Which of your partner's little daily habits are you grateful for?",
      "What did your partner forgive you for that you're still grateful about?",
      "How did your partner show up for your family in a way you appreciated?",
      "What about your partner's sense of humor gets you through hard days?",
      "When did you feel really lucky to have this partner?",
      "What about your partner's drive are you glad rubs off on you?",
      "What's the one thing you want to thank your partner for right now?",
    ],
    friends: [
      "What did someone here do for you that you never properly thanked them for?",
      "What are you grateful your friends put up with about you?",
      "What little thing about this group would you miss the most?",
      "Who here made a hard time easier without even knowing it?",
      "What did you learn from someone in this room that you're grateful for?",
      "What's actually good about the way this group disagrees?",
      "Whose patience here are you thankful for?",
      "What hard time with this group are you now grateful you went through?",
      "What does a friend do regularly that you've never properly thanked them for?",
      "How has this group made you a better person?",
      "What has someone's family shared with you that you're thankful for?",
      "What comfort does a friend give you that you'd be lost without?",
      "What about this friendship don't you say thank you for enough?",
      "What sacrifice did a friend make for you that you're really grateful for?",
      "What did a friend teach you that you're glad you learned?",
      "How does someone here show up that you never want to take for granted?",
      "Which of a friend's flaws are you weirdly grateful for?",
      "When did someone's support mean more than they knew?",
      "What moment with this group would you freeze out of pure gratitude?",
      "What quality in someone here do you wish you thanked them for more?",
      "What about how someone here argues are you secretly grateful for?",
      "How has this group made your family life better — or the other way around?",
      "What sacrifice did a friend make — money or otherwise — that you're thankful for?",
      "What about growing older with this group are you already grateful for?",
      "What hard truth from someone here are you thankful for now?",
      "What about your social life are you most thankful this group brings?",
      "Which of someone's little habits here are you grateful for?",
      "What did a friend forgive you for that you're still grateful about?",
      "How did this group show up for your family in a way you appreciated?",
      "What about this group's humor gets you through hard days?",
      "When did you feel really lucky to have these friends?",
      "Whose drive here are you glad rubs off on you?",
      "What's the one thing you want to thank someone here for right now?",
      "What memory with this group are you quietly thankful you got to have?",
    ],
  },
  adventure: {
    shared: [
      "What's the biggest thing you'd try if you knew you couldn't fail?",
      "Mountains, beach, or city — where do you feel most alive?",
      "Where has none of us been that we totally should go?",
      "Plan every detail, or just go with zero plan?",
      "If we had two free weeks starting tomorrow, what are we doing?",
      "What outdoorsy thing should we try together this year?",
      "What food do you want to eat in the country it comes from?",
      "Road trip or flight — and who's driving?",
      "What spot near us have we never checked out?",
      "Move somewhere new every year, or settle down in one place?",
      "What adventurous thing did you do once and never again?",
      "If we took a whole year off together, what would we do?",
      "What sound, smell or place instantly makes you feel free?",
      "What mini adventure could we have this weekend?",
      "What adventure turned out totally different from what you expected?",
      "What's the most spontaneous call you've made while traveling?",
      "What physical challenge would you love to try together?",
      "If you could teleport anywhere for one hour, where to?",
    ],
    couples: [
      "What's the best trip you took before we met?",
      "What would our dream anniversary trip look like?",
      "What's the wildest place you'd want to go together?",
      "Slow scenic trip or action-packed adventure with your partner?",
      "What travel disaster did you two survive that you laugh about now?",
      "What adventure did your partner talk you into that you're glad you did?",
      "What's the most romantic view you two have ever shared?",
      "What trip changed how you see each other?",
      "What would you never try solo but would with your partner?",
      "What's the scariest thing you'd do together if you both said yes right now?",
      "What country would you want to live in together for a year?",
      "What's the best random find you two stumbled on during a trip?",
      "What adventure do you want before you're too old to enjoy it?",
      "Camping under the stars or a fancy hotel — together?",
      "What adventurous thing would your partner surprise people by agreeing to?",
      "What trip would you redo together exactly the same way?",
      "What adventure would test you as a couple — in a good way?",
      "What's the most 'us' way to spend a surprise day off?",
      "What bucket-list thing do you want your partner there for?",
      "When were you most nervous trying something new together?",
      "What adventure would be worth the money, no matter what?",
      "What skill would you learn together purely for the adventure?",
      "What's the farthest you two have traveled together?",
      "What adventure would make a great story for your grandkids?",
      "What road have you two always wanted to just drive, no destination?",
      "What's the most out-of-character thing your partner did on a trip?",
      "What adventure would you relive exactly as it happened?",
      "What fear would you face together once, just to say you did?",
      "What's the best souvenir from a trip together, and why?",
      "What adventure has your partner always wanted that you've never asked about?",
      "What's the wildest 'yes' you two said to each other on a trip?",
      "What trip do you two keep almost planning but never book?",
      "What's the most beautiful place you've seen with your partner?",
      "What adventure taught you something new about your partner?",
    ],
    friends: [
      "What's the best trip you've taken without anyone here?",
      "Who in this room is the best travel buddy? Be honest.",
      "What's the wildest place this group should go together?",
      "Slow scenic trip or action-packed adventure with this group?",
      "What travel disaster did this group survive that you laugh about now?",
      "What adventure did someone here talk you into that you're glad you did?",
      "What's the most memorable view this group has shared?",
      "What trip changed how you see someone here?",
      "What would you never try solo but would with this group?",
      "What's the scariest thing this group would do if everyone said yes right now?",
      "What country should this group live in together for a summer?",
      "What's the best random find this group stumbled on during a trip?",
      "What adventure do you want with this group before you're too old to enjoy it?",
      "Camping under the stars or a fancy villa — with this group?",
      "What adventurous thing would someone here surprise people by agreeing to?",
      "What group trip would you redo exactly the same way?",
      "What adventure would test this friendship — in a good way?",
      "What's the most 'this group' way to spend a surprise day off?",
      "What bucket-list thing do you want someone here there for?",
      "When were you most nervous trying something new with this group?",
      "What adventure would be worth the money, no matter what?",
      "What skill should this group learn together purely for the adventure?",
      "What's the farthest this group has traveled together?",
      "What adventure would make a great story for your grandkids?",
      "What road has this group always wanted to just drive, no destination?",
      "What's the most out-of-character thing someone here did on a trip?",
      "What adventure would you relive exactly as it happened?",
      "What fear would you face with this group once, just to say you did?",
      "What's the best souvenir from a trip with this group, and why?",
      "What adventure has someone here always wanted that nobody's asked about?",
      "What's the wildest 'yes' this group has said on a trip?",
      "What trip does this group keep almost planning but never book?",
      "What's the most beautiful place you've seen with people from this group?",
      "What adventure taught you something new about someone here?",
    ],
  },
  everyday: {
    shared: [
      "What's the best part of a normal day for you?",
      "How do you take your coffee or tea?",
      "What's your favorite way to waste an hour?",
      "What's been on your mind the most lately?",
      "What chore would you happily pay someone to do forever?",
      "What do you look forward to most on a regular weekday?",
      "What's your go-to comfort food when things go wrong?",
      "How do you actually like being woken up?",
      "What's the last thing that made you laugh out loud?",
      "What's your phone stealing time from?",
      "What's your favorite thing we do that costs nothing?",
      "How are you really doing? Not the quick answer.",
      "What little thing I do bugs you? Be honest — and nice.",
      "What tiny daily ritual would you never give up?",
      "What boring task is weirdly satisfying for you?",
      "What ordinary thing instantly lifts your mood?",
      "Honestly, what's your energy level right now, out of 10?",
      "What tiny daily annoyance gets you every single time?",
    ],
    couples: [
      "How do you like to be greeted when I get home?",
      "Early bird or night owl?",
      "What does a good, normal night together look like?",
      "Which of your partner's little daily habits do you secretly love?",
      "What's the most 'old married couple' thing you two do?",
      "What texting habit of your partner's says a lot about them?",
      "What boring task do you actually enjoy doing with your partner?",
      "What about your partner's morning routine surprised you?",
      "What food combo does your partner eat that you'll never understand?",
      "What was the last totally normal moment with your partner that you loved?",
      "What chore have you two silently agreed never to talk about?",
      "What's your partner's go-to phrase — cute or annoying?",
      "What part of your partner's daily routine have you started copying?",
      "How does your partner solve problems in a way you admire?",
      "What do you two do on repeat that never gets old?",
      "Which of your partner's habits took some getting used to?",
      "What errand is the most 'us' thing you two do together?",
      "What about your partner's daily energy rubs off on you?",
      "What little comfort do you two share every single day?",
      "What weird thing became normal once you got together?",
      "What's your partner's go-to answer to 'what do you want for dinner?'",
      "What tiny disagreement do you two keep having that never gets serious?",
      "What do your partner's phone habits say about them?",
      "What's the most predictable thing your partner does every day?",
      "What Sunday-morning habit do you two share?",
      "What small thing does your partner do that you'd notice right away if it stopped?",
      "What's the most low-key way you two show affection on a normal day?",
      "What daily errand is secretly your favorite part of the day?",
      "What part of your partner's routine do you find weirdly charming?",
      "What did your partner say recently that's still stuck in your head?",
      "What normal Tuesday thing would you pick over something 'exciting'?",
      "What about your daily rhythm only works because of your partner?",
      "What little joke do you two make almost every day without noticing?",
      "What totally ordinary thing does your partner do that you'd really miss?",
    ],
    friends: [
      "What is the group chat actually for?",
      "Who here takes forever to reply, and what's the excuse?",
      "What does a good, normal night out with friends look like to you?",
      "Which little daily habit of someone here do you secretly love?",
      "What's the most 'grumpy old roommates' thing this group does?",
      "What texting habit of someone here says a lot about them?",
      "What boring task do you actually enjoy doing with this group?",
      "What about someone's morning routine surprised you?",
      "What food combo does someone here eat that you'll never understand?",
      "What was the last totally normal moment with this group that you loved?",
      "What group habit have we silently agreed never to talk about?",
      "What's someone's go-to phrase — cute or annoying?",
      "What part of someone's daily routine have you started copying?",
      "How does someone here solve problems in a way you admire?",
      "What do you all do on repeat that never gets old?",
      "Which habit of someone here took some getting used to?",
      "What errand is the most 'this group' thing you do together?",
      "Whose daily energy here rubs off on you?",
      "What little comfort does this group share all the time?",
      "What weird thing became normal once you met this group?",
      "Who always says 'whatever, I'm fine with anything' when we pick food?",
      "What tiny disagreement does this group keep having that never gets serious?",
      "What do someone's phone habits say about them?",
      "What's the most predictable thing someone here does every day?",
      "What weekend-morning habit does this group share?",
      "What small thing does someone here do that you'd notice right away if it stopped?",
      "What's the most low-key way this group shows they care on a normal day?",
      "What daily errand is secretly your favorite part of the day?",
      "What part of someone's routine do you find weirdly charming?",
      "What did someone here say recently that's still stuck in your head?",
      "What normal weekday thing would you pick over something 'exciting'?",
      "What about your daily rhythm only works because of this group?",
      "What little joke does this group make almost every day without noticing?",
      "What totally ordinary thing does someone here do that you'd really miss?",
    ],
  },
};

// type: 'moveSelf' | 'swapPositions' | 'joinPartner' | 'skipTurn' | 'extraTurn'
//     | 'lovePoints' | 'bothPoints' | 'action' | 'giftPoints'
//
// `friends` is the wording used in Friends mode — most of these are mechanical
// and only need "your partner" swapped for "another player". `text_id` and
// `friends_id` are the Indonesian versions of each. `only` restricts
// a card to one mode, which is how the romantic dares stay out of a game
// between friends.
const SURPRISES = [
  {
    icon: '🔀',
    text: 'Swap places with your partner!',
    friends: 'Swap places with another player!',
    text_id: 'Tukeran tempat sama pasanganmu!',
    friends_id: 'Tukeran tempat sama pemain lain!',
    type: 'swapPositions',
  },
  { icon: '⬆️', text: 'Lucky you — jump ahead 4.', text_id: 'Lagi hoki — maju 4 kotak.', type: 'moveSelf', value: 4 },
  { icon: '⬇️', text: 'Oops, tripped — back 3.', text_id: 'Ups, kesandung — mundur 3.', type: 'moveSelf', value: -3 },
  { icon: '🔁', text: 'Roll again!', text_id: 'Kocok sekali lagi!', type: 'extraTurn' },
  { icon: '⏸️', text: 'Take a breather — skip your next turn.', text_id: 'Rehat dulu — giliran berikutnya kamu skip.', type: 'skipTurn', target: 'self' },
  {
    icon: '🚫',
    text: 'Your partner sits out their next turn!',
    friends: 'Another player sits out their next turn!',
    text_id: 'Giliran pasanganmu berikutnya di-skip!',
    friends_id: 'Giliran pemain lain berikutnya di-skip!',
    type: 'skipTurn',
    target: 'opponent',
  },
  {
    icon: '💞',
    text: '+5 Love Points. Nice.',
    friends: '+5 points. Nice.',
    text_id: '+5 Poin Cinta. Mantap!',
    friends_id: '+5 poin. Mantap!',
    type: 'lovePoints',
    value: 5,
    target: 'self',
  },
  {
    icon: '💔',
    text: 'Ouch — lose 3 Love Points.',
    friends: 'Ouch — lose 3 points.',
    text_id: 'Aduh — Poin Cinta kamu kurang 3.',
    friends_id: 'Aduh — poinmu kurang 3.',
    type: 'lovePoints',
    value: -3,
    target: 'self',
  },
  {
    icon: '🤗',
    text: 'Go hug your partner. Right now.',
    friends: 'Hug the player on your left.',
    text_id: 'Peluk pasanganmu. Sekarang juga!',
    friends_id: 'Peluk pemain di sebelah kirimu.',
    type: 'action',
    bonus: 2,
  },
  { icon: '😘', text: 'Kiss your partner on the cheek.', text_id: 'Cium pipi pasanganmu, dong.', type: 'action', bonus: 2, only: 'couples' },
  { icon: '📸', text: 'Snap a photo together.', text_id: 'Foto bareng, yuk!', type: 'action', bonus: 2 },
  {
    icon: '🎁',
    text: 'Give 3 Love Points to your partner.',
    friends: 'Give 3 points to another player.',
    text_id: 'Kasih 3 Poin Cinta ke pasanganmu.',
    friends_id: 'Kasih 3 poin ke pemain lain.',
    type: 'giftPoints',
    value: 3,
  },
  { icon: '🍀', text: "You're on a roll — forward 6.", text_id: 'Lagi beruntung — maju 6.', type: 'moveSelf', value: 6 },
  { icon: '🎯', text: 'Forward 2.', text_id: 'Maju 2.', type: 'moveSelf', value: 2 },
  { icon: '🌪️', text: 'Whoosh — blown back 5.', text_id: 'Wusss — ketiup angin, mundur 5.', type: 'moveSelf', value: -5 },
  {
    icon: '🧲',
    text: "Magnet! Zip over to your partner's square.",
    friends: "Magnet! Zip over to another player's square.",
    text_id: 'Magnet! Langsung nempel ke kotak pasanganmu.',
    friends_id: 'Magnet! Langsung nempel ke kotak pemain lain.',
    type: 'joinPartner',
  },
  {
    // "You BOTH" was wrong from three players up — this card has always paid
    // everyone at the table.
    icon: '🤝',
    text: 'Everyone gets 3 Love Points.',
    friends: 'Everyone gets 3 points.',
    text_id: 'Semua dapat 3 Poin Cinta.',
    friends_id: 'Semua dapat 3 poin.',
    type: 'bothPoints',
    value: 3,
  },
  {
    icon: '💌',
    text: 'Your partner gets 4 Love Points — tell them why.',
    friends: 'Another player gets 4 points — tell them why.',
    text_id: 'Pasanganmu dapat 4 Poin Cinta — kasih tahu alasannya.',
    friends_id: 'Pemain lain dapat 4 poin — kasih tahu alasannya.',
    type: 'lovePoints',
    value: 4,
    target: 'opponent',
  },
  {
    icon: '💐',
    text: 'Name three things you love about your partner.',
    friends: 'Name three things you like about the player on your right.',
    text_id: 'Sebutin tiga hal yang kamu suka dari pasanganmu.',
    friends_id: 'Sebutin tiga hal yang kamu suka dari pemain di sebelah kananmu.',
    type: 'action',
    bonus: 3,
  },
  {
    icon: '🎵',
    text: 'Play a song that reminds you of your partner.',
    friends: 'Play a song that reminds you of someone here.',
    text_id: 'Setel lagu yang bikin kamu inget pasanganmu.',
    friends_id: 'Setel lagu yang bikin kamu inget seseorang di sini.',
    type: 'action',
    bonus: 3,
  },
  {
    icon: '☕',
    text: 'Coffee date this week — pick the day now.',
    friends: 'Group hangout — pick the date now.',
    text_id: 'Ngopi berdua minggu ini — tentuin harinya sekarang.',
    friends_id: 'Nongkrong bareng — tentuin tanggalnya sekarang.',
    type: 'action',
    bonus: 2,
  },
  {
    icon: '🎭',
    text: "Act out your partner's go-to phrase.",
    friends: "Act out another player's go-to phrase.",
    text_id: 'Tiruin kata-kata andalan pasanganmu.',
    friends_id: 'Tiruin kata-kata andalan pemain lain.',
    type: 'action',
    bonus: 2,
  },
  { icon: '🕯️', text: 'Hold hands, no talking, for 20 seconds.', text_id: 'Pegangan tangan tanpa ngomong selama 20 detik.', type: 'action', bonus: 3, only: 'couples' },
  {
    icon: '🙈',
    text: "Close your eyes and describe your partner's face.",
    text_id: 'Tutup mata, terus gambarin wajah pasanganmu.',
    type: 'action',
    bonus: 2,
    only: 'couples',
  },
  {
    icon: '⭐',
    text: 'Name one thing your partner nailed today.',
    friends: 'Name one thing another player nailed today.',
    text_id: 'Sebutin satu hal keren yang pasanganmu lakuin hari ini.',
    friends_id: 'Sebutin satu hal keren yang pemain lain lakuin hari ini.',
    type: 'action',
    bonus: 2,
  },
  {
    icon: '🎤',
    text: 'The group gets to ask you one question. No dodging.',
    text_id: 'Grup boleh nanya satu hal ke kamu. Nggak boleh ngeles!',
    type: 'action',
    bonus: 3,
    only: 'friends',
  },
  {
    icon: '👀',
    text: 'Tell the player on your left your honest first impression of them.',
    text_id: 'Bilang kesan pertamamu yang jujur ke pemain di sebelah kirimu.',
    type: 'action',
    bonus: 3,
    only: 'friends',
  },
  { icon: '🌈', text: 'Forward 3.', text_id: 'Maju 3.', type: 'moveSelf', value: 3 },
  { icon: '🐢', text: 'Slow and steady — back 2.', text_id: 'Pelan-pelan asal selamat — mundur 2.', type: 'moveSelf', value: -2 },
  { icon: '🔥', text: "You're on fire — forward 5.", text_id: 'Lagi on fire — maju 5!', type: 'moveSelf', value: 5 },
  { icon: '🧊', text: 'Cold feet — back 4.', text_id: 'Mendadak galau — mundur 4.', type: 'moveSelf', value: -4 },
  {
    icon: '🎈',
    text: '+2 Love Points.',
    friends: '+2 points.',
    text_id: '+2 Poin Cinta.',
    friends_id: '+2 poin.',
    type: 'lovePoints',
    value: 2,
    target: 'self',
  },
  {
    icon: '🥶',
    text: 'Brr — lose 2 Love Points.',
    friends: 'Brr — lose 2 points.',
    text_id: 'Brr — Poin Cinta kamu kurang 2.',
    friends_id: 'Brr — poinmu kurang 2.',
    type: 'lovePoints',
    value: -2,
    target: 'self',
  },
  {
    icon: '🎊',
    text: 'Everyone gets 2 Love Points.',
    friends: 'Everyone gets 2 points.',
    text_id: 'Semua dapat 2 Poin Cinta.',
    friends_id: 'Semua dapat 2 poin.',
    type: 'bothPoints',
    value: 2,
  },
  {
    icon: '🫶',
    text: 'Give 5 Love Points to your partner.',
    friends: 'Give 5 points to another player.',
    text_id: 'Kasih 5 Poin Cinta ke pasanganmu.',
    friends_id: 'Kasih 5 poin ke pemain lain.',
    type: 'giftPoints',
    value: 5,
  },
  {
    icon: '🔗',
    text: "Chain reaction — hop to your partner's square.",
    friends: "Chain reaction — hop to another player's square.",
    text_id: 'Reaksi berantai — lompat ke kotak pasanganmu.',
    friends_id: 'Reaksi berantai — lompat ke kotak pemain lain.',
    type: 'joinPartner',
  },
  { icon: '🕺', text: 'Dance for 10 seconds. Music optional.', text_id: 'Joget 10 detik. Musik nggak wajib.', type: 'action', bonus: 2 },
  { icon: '🤳', text: 'Take a selfie together and describe it out loud.', text_id: 'Selfie bareng, terus ceritain fotonya.', type: 'action', bonus: 2 },
  {
    icon: '🎶',
    text: 'Hum a song — your partner has to guess it.',
    friends: 'Hum a song — the group has to guess it.',
    text_id: 'Senandungin satu lagu — pasanganmu harus nebak.',
    friends_id: 'Senandungin satu lagu — grup harus nebak.',
    type: 'action',
    bonus: 2,
  },
  {
    icon: '🙋',
    text: 'Ask your partner anything — they have to answer honestly.',
    friends: 'Ask anyone here anything — they have to answer honestly.',
    text_id: 'Tanya apa aja ke pasanganmu — dia wajib jawab jujur.',
    friends_id: 'Tanya apa aja ke siapa pun di sini — dia wajib jawab jujur.',
    type: 'action',
    bonus: 3,
  },
  {
    icon: '💭',
    text: "Guess what your partner's thinking right now.",
    text_id: 'Tebak apa yang lagi dipikirin pasanganmu sekarang.',
    type: 'action',
    bonus: 2,
    only: 'couples',
  },
  {
    icon: '🦜',
    text: 'Do your best impression of your partner.',
    friends: 'Do your best impression of someone here.',
    text_id: 'Tiruin gaya pasanganmu semirip mungkin.',
    friends_id: 'Tiruin gaya seseorang di sini semirip mungkin.',
    type: 'action',
    bonus: 2,
  },
];
