const BOARD_SETUP = {
  ladders: 7,
  snakes: 7,
  minSpan: 8,
  maxSpan: 26,
  maxEndpointsPerRow: 4,
  surpriseChance: 0.25,
};

// One of these is picked at random for every new game. Each defines the page
// backdrop AND the board surface, ladder and snake colours together, so the
// board always sits in the same world as the background behind it.
const BOARD_THEMES = {
  romance: {
    label: 'Romance',
    page: 'radial-gradient(1100px 620px at 50% -12%, #fff7f4 0%, transparent 62%), radial-gradient(900px 520px at 92% 104%, #ecdfff 0%, transparent 58%), linear-gradient(160deg, #fdeef1 0%, #f5e8f7 52%, #ffeef0 100%)',
    boardBg: 'linear-gradient(155deg, #fffdf9, #fdf1ea)',
    frame: '#ffffff',
    cell: 'linear-gradient(160deg, #fffdfa, #fff8f3)',
    cellAlt: 'linear-gradient(160deg, #fdeff1, #fbe7ec)',
    cellBorder: 'rgba(240, 219, 227, 0.7)',
    cellInk: '#8a7681',
    edge: ['#f0d9dd', '#e9cbd2', '#e0bac4', '#d5a7b4', '#c996a6'],
    dropShadow: 'rgba(120, 40, 80, 0.3)',
    ladder: { dark: '#a85f6d', light: '#f0b9a6', foot: '#d38f88' },
    snake: { body: '#8b5a9c', outline: '#5d3569', belly: '#e2c2ec', head: '#7d4f8c' },
    accent: '#d6336c',
    accentDeep: '#a52551',
    pageTexture:
      "<svg xmlns='http://www.w3.org/2000/svg' width='120' height='120'><g fill='#d6336c' fill-opacity='0.07'><path d='M30 26c-4-6-14-5-14 3 0 7 9 12 14 17 5-5 14-10 14-17 0-8-10-9-14-3z'/><path d='M88 74c-3-5-11-4-11 2 0 6 7 10 11 14 4-4 11-8 11-14 0-6-8-7-11-2z'/><circle cx='95' cy='25' r='2.5'/><circle cx='22' cy='92' r='2'/></g></svg>",
    pageTextureSize: '120px 120px',
    cellTexture:
      "<svg xmlns='http://www.w3.org/2000/svg' width='16' height='16'><g stroke='#b07a8e' stroke-opacity='0.09' stroke-width='1'><path d='M0 4h16M0 12h16'/><path d='M4 0v16M12 0v16'/></g></svg>",
    cellTextureSize: '16px 16px',
    photo: 'assets/textures/romance.jpg',
    photoPageSize: '420px',
    photoPageOpacity: 0.42,
    photoBoardSize: '180px',
    photoBoardOpacity: 0.14,
    motion: 'twinkle', driftAxis: 'xy', driftDuration: '95s', boardDriftDuration: '150s', twinkleDuration: '7s',
  },
  forest: {
    label: 'Forest',
    page: 'radial-gradient(1100px 620px at 50% -12%, #f0f8ea 0%, transparent 62%), radial-gradient(900px 520px at 92% 104%, #cfe6d4 0%, transparent 58%), linear-gradient(160deg, #e4f1dc 0%, #d5e9d6 52%, #eaf5e2 100%)',
    boardBg: 'linear-gradient(155deg, #fbfdf6, #e9f3e0)',
    frame: '#fbfdf7',
    cell: 'linear-gradient(160deg, #fbfdf6, #f2f9ea)',
    cellAlt: 'linear-gradient(160deg, #e7f2de, #dcebd2)',
    cellBorder: 'rgba(200, 224, 190, 0.75)',
    cellInk: '#6d8168',
    edge: ['#d8e8cf', '#cbe0c0', '#bcd6b0', '#a9c99c', '#96bb88'],
    dropShadow: 'rgba(40, 80, 45, 0.32)',
    ladder: { dark: '#8a5a2b', light: '#dca868', foot: '#b07c3f' },
    snake: { body: '#4f8f4a', outline: '#2f5c2c', belly: '#bfe0a8', head: '#437f3f' },
    accent: '#3f8f4f',
    accentDeep: '#2c6b39',
    pageTexture:
      "<svg xmlns='http://www.w3.org/2000/svg' width='140' height='140'><g fill='#2f5c2c' fill-opacity='0.08'><path d='M20 30c14-12 30-10 34 2-12 12-28 12-34-2z'/><path d='M100 88c12-14 28-14 34-3-10 13-26 15-34 3z'/><path d='M60 118c8-10 20-10 24-2-8 9-19 10-24 2z'/></g><g stroke='#2f5c2c' stroke-opacity='0.07' stroke-width='1.2' fill='none' stroke-linecap='round'><path d='M20 30c11 1 23 2 34 2'/><path d='M100 88c11 0 24 2 34-3'/><path d='M60 118c8 0 17 1 24-2'/></g></svg>",
    pageTextureSize: '140px 140px',
    cellTexture:
      "<svg xmlns='http://www.w3.org/2000/svg' width='60' height='24'><g stroke='#5a7a48' stroke-opacity='0.09' stroke-width='1' fill='none'><path d='M0 6q15-4 30 0t30 0'/><path d='M0 14q15 4 30 0t30 0'/><path d='M0 21q15-3 30 0t30 0'/></g></svg>",
    cellTextureSize: '60px 24px',
    photo: 'assets/textures/forest.jpg',
    photoPageSize: '460px',
    photoPageOpacity: 0.40,
    photoBoardSize: '200px',
    photoBoardOpacity: 0.13,
    motion: 'drift', driftAxis: 'xy', driftDuration: '60s', boardDriftDuration: '110s',
  },
  ocean: {
    label: 'Ocean',
    page: 'radial-gradient(1100px 620px at 50% -12%, #eaf7fb 0%, transparent 62%), radial-gradient(900px 520px at 92% 104%, #c9e2f2 0%, transparent 58%), linear-gradient(160deg, #ddeff7 0%, #cfe4f2 52%, #e8f5fb 100%)',
    boardBg: 'linear-gradient(155deg, #f9fdff, #e2f0f9)',
    frame: '#f9fdff',
    cell: 'linear-gradient(160deg, #f9fdff, #eef8fd)',
    cellAlt: 'linear-gradient(160deg, #e0eff8, #d3e6f3)',
    cellBorder: 'rgba(190, 217, 232, 0.75)',
    cellInk: '#5f8194',
    edge: ['#cfe4ef', '#bcd9e9', '#a8cde0', '#93bed4', '#7eb0c8'],
    dropShadow: 'rgba(20, 70, 100, 0.32)',
    ladder: { dark: '#9a7b45', light: '#e8cc95', foot: '#c2a068' },
    snake: { body: '#2f8f9c', outline: '#1c5f6a', belly: '#a8e0e6', head: '#28808c' },
    accent: '#2b8ca6',
    accentDeep: '#1d6b80',
    pageTexture:
      "<svg xmlns='http://www.w3.org/2000/svg' width='120' height='60'><g stroke='#1c5f6a' stroke-opacity='0.1' stroke-width='1.6' fill='none' stroke-linecap='round'><path d='M0 16q15-10 30 0t30 0 30 0 30 0'/><path d='M0 40q15-10 30 0t30 0 30 0 30 0'/></g></svg>",
    pageTextureSize: '120px 60px',
    cellTextureSize: '40px 20px',
    photo: 'assets/textures/ocean.jpg',
    photoPageSize: '440px',
    photoPageOpacity: 0.45,
    photoBoardSize: '190px',
    photoBoardOpacity: 0.15,
    motion: 'drift', driftAxis: 'x', driftDuration: '26s', boardDriftDuration: '38s',
    cellTexture:
      "<svg xmlns='http://www.w3.org/2000/svg' width='40' height='20'><g stroke='#2f8f9c' stroke-opacity='0.1' stroke-width='1' fill='none' stroke-linecap='round'><path d='M0 10q10-6 20 0t20 0'/></g></svg>",
  },
  meadow: {
    label: 'Meadow',
    page: 'radial-gradient(1100px 620px at 50% -12%, #f8fce9 0%, transparent 62%), radial-gradient(900px 520px at 92% 104%, #e0eec4 0%, transparent 58%), linear-gradient(160deg, #eff8dd 0%, #e6f2d4 52%, #f7fbe8 100%)',
    boardBg: 'linear-gradient(155deg, #fdfef7, #eef6dd)',
    frame: '#fdfef8',
    cell: 'linear-gradient(160deg, #fdfef7, #f6fbe8)',
    cellAlt: 'linear-gradient(160deg, #ecf6da, #e2efcb)',
    cellBorder: 'rgba(214, 230, 184, 0.75)',
    cellInk: '#77875c',
    edge: ['#e0ecc8', '#d3e4b6', '#c4daa4', '#b3cf90', '#a2c47c'],
    dropShadow: 'rgba(70, 90, 30, 0.3)',
    ladder: { dark: '#9c7b3a', light: '#ebcf88', foot: '#c0a05a' },
    snake: { body: '#7fa63c', outline: '#4f6b22', belly: '#dff0a8', head: '#71962f' },
    accent: '#7ba337',
    accentDeep: '#5b7d26',
    pageTexture:
      "<svg xmlns='http://www.w3.org/2000/svg' width='100' height='100'><g stroke='#4f6b22' stroke-opacity='0.11' stroke-width='1.4' fill='none' stroke-linecap='round'><path d='M12 94c0-12 4-20 8-26'/><path d='M18 94c0-10-2-18-6-24'/><path d='M62 98c0-12 5-20 9-26'/><path d='M68 98c0-10-2-18-6-24'/><path d='M38 48c0-10 4-16 7-21'/><path d='M44 48c0-9-2-15-6-20'/></g></svg>",
    pageTextureSize: '100px 100px',
    cellTexture:
      "<svg xmlns='http://www.w3.org/2000/svg' width='24' height='24'><g fill='#5b7d26' fill-opacity='0.09'><circle cx='6' cy='7' r='1.4'/><circle cx='18' cy='16' r='1.2'/><circle cx='12' cy='3' r='1'/><circle cx='3' cy='19' r='1'/></g></svg>",
    cellTextureSize: '24px 24px',
    photo: 'assets/textures/meadow.jpg',
    photoPageSize: '400px',
    photoPageOpacity: 0.42,
    photoBoardSize: '175px',
    photoBoardOpacity: 0.14,
    motion: 'drift', driftAxis: 'x', driftDuration: '42s', boardDriftDuration: '70s',
  },
  sunset: {
    label: 'Sunset',
    page: 'radial-gradient(1100px 620px at 50% -12%, #fff3e4 0%, transparent 62%), radial-gradient(900px 520px at 92% 104%, #f0d6ea 0%, transparent 58%), linear-gradient(160deg, #ffe9db 0%, #f8dde6 52%, #f4e2f2 100%)',
    boardBg: 'linear-gradient(155deg, #fffaf3, #fbe9db)',
    frame: '#fffaf4',
    cell: 'linear-gradient(160deg, #fffaf3, #fef2e7)',
    cellAlt: 'linear-gradient(160deg, #fbe8da, #f7ddcc)',
    cellBorder: 'rgba(240, 214, 194, 0.75)',
    cellInk: '#a2806c',
    edge: ['#f5d9c4', '#efcbb2', '#e7bb9e', '#dca786', '#cf9370'],
    dropShadow: 'rgba(130, 60, 40, 0.32)',
    ladder: { dark: '#9c5a30', light: '#f4bf8c', foot: '#c98b55' },
    snake: { body: '#a44f7a', outline: '#6d2f52', belly: '#f0bcd8', head: '#94456d' },
    accent: '#e2703a',
    accentDeep: '#b4531f',
    pageTexture:
      "<svg xmlns='http://www.w3.org/2000/svg' width='160' height='120'><g fill='#b4531f' fill-opacity='0.055'><ellipse cx='40' cy='28' rx='34' ry='9'/><ellipse cx='120' cy='76' rx='40' ry='10'/><ellipse cx='74' cy='104' rx='26' ry='7'/></g><g stroke='#b4531f' stroke-opacity='0.05' stroke-width='1.2' fill='none'><path d='M0 52h160'/><path d='M0 92h160'/></g></svg>",
    pageTextureSize: '160px 120px',
    cellTexture:
      "<svg xmlns='http://www.w3.org/2000/svg' width='20' height='20'><g fill='#9c5a30' fill-opacity='0.08'><circle cx='4' cy='5' r='1'/><circle cx='14' cy='12' r='1.1'/><circle cx='9' cy='17' r='0.9'/></g></svg>",
    cellTextureSize: '20px 20px',
    photo: 'assets/textures/sunset.jpg',
    photoPageSize: '450px',
    photoPageOpacity: 0.42,
    photoBoardSize: '195px',
    photoBoardOpacity: 0.14,
    motion: 'drift', driftAxis: 'x', driftDuration: '75s', boardDriftDuration: '120s',
  },
  night: {
    label: 'Night',
    page: 'radial-gradient(1100px 620px at 50% -12%, #333c63 0%, transparent 62%), radial-gradient(900px 520px at 92% 104%, #3a2a5c 0%, transparent 58%), linear-gradient(160deg, #1e2438 0%, #262040 52%, #1a2032 100%)',
    boardBg: 'linear-gradient(155deg, #303858, #242a44)',
    frame: '#3c4468',
    cell: 'linear-gradient(160deg, #333c5e, #2c3452)',
    cellAlt: 'linear-gradient(160deg, #2a3150, #242b46)',
    cellBorder: 'rgba(90, 100, 145, 0.5)',
    cellInk: '#9aa4ca',
    edge: ['#262d4a', '#212843', '#1c223a', '#171d31', '#131828'],
    dropShadow: 'rgba(0, 0, 0, 0.55)',
    ladder: { dark: '#5f6890', light: '#cdd6f5', foot: '#98a1c8' },
    snake: { body: '#7b5bd6', outline: '#452b93', belly: '#cbbcff', head: '#6d4fc4' },
    accent: '#8b6ee8',
    accentDeep: '#6a4fd0',
    pageTexture:
      "<svg xmlns='http://www.w3.org/2000/svg' width='140' height='140'><g fill='#ffffff' fill-opacity='0.5'><circle cx='20' cy='28' r='1.3'/><circle cx='96' cy='18' r='1'/><circle cx='124' cy='62' r='1.4'/><circle cx='58' cy='76' r='1'/><circle cx='34' cy='112' r='1.2'/><circle cx='108' cy='120' r='1'/><circle cx='78' cy='44' r='0.8'/><circle cx='8' cy='66' r='0.9'/></g><g fill='#cbbcff' fill-opacity='0.6'><path d='M62 14l1.4 3.6L67 19l-3.6 1.4L62 24l-1.4-3.6L57 19l3.6-1.4z'/><path d='M116 92l1.2 3 3 1.2-3 1.2-1.2 3-1.2-3-3-1.2 3-1.2z'/></g></svg>",
    pageTextureSize: '140px 140px',
    cellTexture:
      "<svg xmlns='http://www.w3.org/2000/svg' width='30' height='30'><g fill='#9aa4ca' fill-opacity='0.18'><circle cx='7' cy='8' r='0.9'/><circle cx='22' cy='19' r='0.7'/><circle cx='16' cy='27' r='0.6'/></g></svg>",
    cellTextureSize: '30px 30px',
    photo: 'assets/textures/night.jpg',
    photoPageSize: '480px',
    photoPageOpacity: 0.55,
    photoBoardSize: '210px',
    photoBoardOpacity: 0.20,
    motion: 'twinkle', driftAxis: 'x', driftDuration: '140s', boardDriftDuration: '190s', twinkleDuration: '4.5s',
  },
};

// The game is played in one of two modes, chosen on the setup screen. Mode
// decides which questions, dares and surprises are in play, and what the AI is
// told about who is sitting at the table — a group of friends should never be
// handed "give your partner a shoulder massage", and the model should never
// write a romantic prompt for people who aren't a couple.
const MODES = {
  couples: {
    label: 'Couples',
    hint: 'Questions and dares written for two partners.',
    subject: 'Two partners are playing a board game designed to bring them closer together.',
    guard: '',
    points: 'Love Points',
  },
  friends: {
    label: 'Friends',
    hint: 'Nothing romantic — written for friends playing together.',
    subject:
      'A group of friends is playing a board game designed to help them know each other better.',
    guard:
      'They are friends, not romantic partners. Never imply romance, dating, flirting or physical intimacy.',
    points: 'points',
  },
};

// `friendsLabel` / `friendsIcon` rename a theme in Friends mode where the
// couples wording would be wrong. Everything else is shared.
const QUESTION_THEMES = {
  general: { label: 'General', icon: '💬', color: '#3b7dd8' },
  love: { label: 'Love', friendsLabel: 'Closeness', icon: '❤️', friendsIcon: '💛', color: '#d6336c' },
  money: { label: 'Money', icon: '💰', color: '#2f9e5b' },
  dreams: { label: 'Dreams', icon: '✨', color: '#8b5fbf' },
  dare: { label: 'Fun & Dare', icon: '🎲', color: '#e08a2c' },
  deep: { label: 'Deep Talk', icon: '🌙', color: '#2c7a7b' },
  memories: { label: 'Memories', icon: '📸', color: '#b5763a' },
  home: { label: 'Home & Family', icon: '🏡', color: '#4a7f9e' },
  growth: { label: 'Growth', icon: '🌱', color: '#5c9e46' },
  gratitude: { label: 'Gratitude', icon: '🙏', color: '#c2811f' },
  adventure: { label: 'Adventure', icon: '🧭', color: '#3d8f8f' },
  everyday: { label: 'Everyday', icon: '☕', color: '#8a6a9e' },
};

// Each theme is `shared` (works for anyone at the table) plus one list per
// mode. The pool for a game is shared + that mode's list — see questionPool()
// in script.js. Splitting them this way rather than keeping two whole banks
// means the ~60% of questions that were already neutral are written once.
const QUESTIONS = {
  general: {
    shared: [
      "What's one skill you wish we could learn together?",
      "What's a movie or show we should watch together this month?",
      'If we traded lives for a day, what would you do first?',
      "What's a nickname or inside joke of ours you love?",
      'What surprised you about me when we first met?',
      'What song reminds you of us?',
      "What's the best meal we've ever shared?",
      "What's a habit of mine that you now do too?",
      "What's one small thing I could do this week to make you happy?",
      'Who would survive a zombie attack better, and why?',
    ],
    couples: [
      "What's a small thing your partner does that makes you smile?",
      'If we could go anywhere right now for a date, where would we go?',
      "What's something funny to you that your partner doesn't get?",
      'If we got a pet tomorrow, what would we name it?',
      'If our life was a movie, what type would it be?',
      "What's your favorite corner of our home?",
    ],
    friends: [
      "What's the most useless talent you have?",
      'Who here would you call first in an emergency, and why?',
      'What show would you make everyone here sit through?',
      'If we started a band tomorrow, who plays what?',
      "What's a rumour about you that turned out to be true?",
      'Who here has changed the most since you met them?',
    ],
  },
  love: {
    shared: [
      "What's the best way to comfort you when you're sad?",
      "What's something you've never said out loud, but want me to know?",
      'Give someone here a real compliment right now.',
      "What's the best way we say sorry to each other?",
      "What's one thing you never want us to stop doing together?",
    ],
    couples: [
      'What made you fall for your partner at first?',
      'Describe your partner in three words — say them out loud.',
      'What small thing makes you feel most loved?',
      'What do you love most about how your partner treats you?',
      'When do you feel closest to your partner?',
      'What promise do you want to make to each other tonight?',
      'When did you know you loved me?',
      "What's the best thing about us as a couple?",
      'How has loving me changed you?',
      'If our love was a color, what would it be, and why?',
      'What does being loved by me feel like?',
    ],
    friends: [
      'What made you decide I was a real friend, not just someone you knew?',
      'Describe me in three words — say them out loud.',
      'What do you need from a friend that you find hard to ask for?',
      'When have you felt most looked after by someone here?',
      "What's something you appreciate about me that I probably don't know?",
      'What makes someone a good friend, to you?',
      'Who here would you want beside you on the worst day of your life?',
      "What's the kindest thing anyone here has done for you?",
    ],
  },
  money: {
    shared: [
      'What money habit from your family do you want to keep or drop?',
      'What does feeling safe with money look like to you?',
      'If you got a lot of extra money tomorrow, save it, spend it, or split it?',
      "What's something fun you'd happily spend too much on?",
      "What's the best money decision you've ever made?",
      "What's one money talk you keep putting off?",
      "What's a skill you'd pay real money to learn?",
    ],
    couples: [
      "What's one money goal we should set this year?",
      'If we had an extra $500 this month, what would we do with it?',
      "What money habit of your partner's do you like?",
      'How do you feel about our savings plan? Anything to change?',
      "What's a big thing we should start saving for?",
      "Do we agree on how we split bills? What's working, what's not?",
      'What could we spend less on to save for something bigger?',
      'Where do you see us with money in 5 years?',
      'Are we saving enough for fun, or too focused on later?',
      'Should we each get money to spend with no questions asked? How much?',
    ],
    friends: [
      'Is splitting a bill with friends easy for you, or quietly awkward?',
      'Would you lend a friend money? Does it change the friendship?',
      "What's the most you've spent on something nobody else understood?",
      'Do your friends know roughly what you earn? Should they?',
      "What's a trip you'd take with people here if money appeared tomorrow?",
      "What did you waste money on at 20 that you'd never buy now?",
    ],
  },
  dreams: {
    shared: [
      "What's a skill you want to learn well before you turn 60?",
      "If money didn't matter, how would you spend next year?",
      'What would a perfect normal Tuesday look like for you?',
      "What's a dream you gave up that you'd like to start again?",
      "What's one adventure we haven't tried that you want to?",
      'If we could live in another country for a year, where and why?',
      "What's something on your list we should do together this year?",
      'If we could start a business together, what would it be?',
    ],
    couples: [
      "What's a dream trip you want us to take together someday?",
      'Where do you see us living in 10 years?',
      'What does your dream life with your partner look like?',
      "What's a tradition you'd like us to start as a couple?",
      "What's something you hope never changes about us?",
      "What goal are you working on that you want your partner's help with?",
      'What kind of older couple do you want us to become?',
      'What do you want people to say about us in 30 years?',
    ],
    friends: [
      "Where do you want to be living in ten years — and who's nearby?",
      "What's a trip this group should actually book, not just talk about?",
      'What do you want to be known for by the people who know you?',
      'What goal are you working on that someone here could help with?',
      'What kind of old person do you want to be?',
      "What's a tradition you'd like this group to start?",
      'What do you hope never changes about your friends?',
    ],
  },
  dare: {
    shared: [
      'Take a silly selfie together right now.',
      "Swap phones and change each other's wallpaper.",
      'Sing the chorus of a song everyone here knows.',
      'Talk for 30 seconds about something you love. No "um".',
      'Speak in an accent until your next turn.',
    ],
    couples: [
      'Give your partner a 10-second hug right now.',
      'Do your best impression of your partner.',
      'Say "I love you" in a funny accent.',
      "Whisper something sweet in your partner's ear.",
      'Slow dance for 15 seconds. No music needed.',
      'Feed your partner a snack or a sip of a drink.',
      'Act out how you two met, like a movie scene.',
      "Hold hands and look into each other's eyes for 20 seconds. Don't laugh.",
      'Give your partner a compliment with your hands only. No talking.',
      'Give your partner a 30-second shoulder massage.',
      'Try to make your partner laugh in 15 seconds without touching them.',
      'Sing the chorus of "your" song together.',
      "Draw something on your partner's palm with your finger. They guess it.",
      "Say three things you love about your partner. Don't repeat a word.",
    ],
    friends: [
      'Do your best impression of someone else in this room.',
      'Show the last photo in your camera roll and explain it.',
      'Say three genuine things about the player on your right. No repeats.',
      'Read your last sent message out loud, in a dramatic voice.',
      'Do 10 push-ups, or tell an embarrassing story. Choose now.',
      'Let someone here pick the next song. No complaints.',
      'Try to make the group laugh in 15 seconds without saying a word.',
      'Let the player on your left give you a new nickname for the rest of the game.',
    ],
  },
  deep: {
    shared: [
      'What does "home" mean to you?',
      "What's a part of yourself you're still working on?",
      'How do you like to be helped when things are stressful?',
      'What does it mean to forgive someone, to you?',
      'How do you want to be treated when you make a mistake?',
      "What's something hard for you right now?",
      'What do you want to remember about this time in your life?',
      'When did you last feel truly understood?',
    ],
    couples: [
      "What's something hard for you right now that I could help with?",
      'Do you have any fear about our relationship? What is it?',
      'What do you need more of from me lately?',
      "How have you grown since we've been together?",
      'Is there anything unsaid between us you want to talk about?',
      "What's something you've learned about love from us?",
      "What's something you're afraid to ask me for?",
      'What from your past still affects how you love?',
      'What should I remember if we ever have a bad fight?',
    ],
    friends: [
      'Is there anything unsaid between you and anyone here?',
      'What do you need more of from your friends lately?',
      "What's something you're afraid to ask people for?",
      'How have you changed since this group met you?',
      "What's a friendship you lost that you still think about?",
      'What do you find hardest to say out loud?',
      'When do you feel lonely even with people around?',
      "What should someone do if they've upset you?",
    ],
  },
  memories: {
    shared: [
      "What's the most unplanned thing we've ever done together?",
      'What did you think of me the first time you saw me?',
      "What's a small, normal moment with me that you never forgot?",
      "What's a trip we took that you still think about?",
      'What was our best celebration together?',
      "What's something we used to do that we should start doing again?",
      'What story about us do you love telling other people?',
      'What moment with me would you love to live again?',
    ],
    couples: [
      "What's your favorite memory from our first few months together?",
      "What's your favorite photo of us? Why that one?",
      'Tell our first date story from your side.',
      "What's the hardest thing we've been through? How did we get past it?",
      "What's the funniest fight we've ever had?",
      'Which gift from me meant the most to you? Why?',
      'When did you first feel like we were really a team?',
      "What's the first thing you told your friends about me?",
    ],
    friends: [
      "What's your favourite memory with someone in this room?",
      'Tell the story of how you two met, from your side.',
      "What's the funniest thing that's ever happened to this group?",
      'What was the worst idea we all agreed to?',
      "What's a photo of us you'd never delete?",
      'When did you first feel properly part of this group?',
      'What did you think of me before you actually knew me?',
      "What's a night none of us should have survived?",
    ],
  },
  home: {
    shared: [
      'What does a perfect weekend at home look like to you?',
      'What chore do you secretly not mind doing?',
      'What tradition from your childhood do you want to keep?',
      "What's one thing about how I was raised that explains who I am?",
      'If we hosted a dinner tomorrow, who would we invite?',
      'What does a calm morning look like for you?',
      'What would you change about your daily routine if you could?',
      'How much time with people, and how much alone, do you actually need?',
    ],
    couples: [
      'How do we split the work no one sees? Is it fair?',
      'What would make our home feel more like ours?',
      'How do you want holidays to feel for us?',
      'How should we handle it when one of us needs space?',
      'What do you wish we did more of at home?',
      'Who in my family are you closest to? Why?',
      'What limit with family do we need to set?',
      'How do you want us to handle guests at our home?',
    ],
    friends: [
      "Whose place does this group always end up at, and why?",
      "What's your family like when everyone's in one room?",
      'What do you wish your friends knew about where you grew up?',
      'Are you the host or the guest? Which do you prefer?',
      "What's a family tradition you'd bring into this group?",
      'Who in your family would get on best with people here?',
      "What's the house rule you'd never break?",
    ],
  },
  growth: {
    shared: [
      "What's something you're proud of yourself for this year?",
      'How have you changed in the last five years?',
      "What's a fear you don't have anymore?",
      'What do you want to be better at a year from now?',
      "What's a belief you've changed your mind about?",
      'Where do you feel stuck right now?',
      'What does success mean to you these days?',
      'What habit would help your life most if you kept doing it?',
      "What's something you want to try but feel too old or late for?",
      'What part of your work gives you energy?',
      'When did you last do something that scared you?',
      'What do you need to say no to more often?',
      'What would you, ten years ago, think of you now?',
    ],
    couples: [
      'What has feedback from me actually helped you with?',
      'What feedback do you wish I gave more kindly?',
      'How do you want me to help keep you on track?',
    ],
    friends: [
      "What's the most useful thing a friend has told you about yourself?",
      'Who here would tell you the truth when nobody else would?',
      'What do you want your friends to hold you to?',
    ],
  },
  gratitude: {
    shared: [
      'What are you thankful for about today?',
      'Who outside this room are you grateful for?',
      "What's a hard thing that happened that you're now glad it did?",
      "What's something about your body you're thankful for?",
      'Name three good things that happened this week.',
      "Who taught you something you're still thankful for?",
      'What about right now is worth being thankful for?',
      "What's a part of my personality you're glad I have?",
      "What's something you're grateful you learned from me?",
    ],
    couples: [
      "What's one thing you're thankful for about us right now?",
      "What's something I do that you've never really thanked me for?",
      'What small comfort in our life do you never want to lose?',
      'What did I do this week that made your life easier?',
      'What are you thankful your partner puts up with about you?',
      'What in our home are you most glad we own?',
      "What's good about the way we argue?",
    ],
    friends: [
      "What did someone here do for you that you never properly thanked them for?",
      'What are you thankful your friends put up with about you?',
      "What's a small thing about this group you'd miss most?",
      'Who here made a hard time easier without knowing it?',
      "What's something you're grateful you learned from someone in this room?",
      "What's good about the way this group disagrees?",
    ],
  },
  adventure: {
    shared: [
      "What's the biggest thing you'd try if you knew you couldn't fail?",
      'Mountains, ocean, or city — where do you feel most alive?',
      "What's a place none of us has been that we should go?",
      'Would you rather plan every detail, or just go with no plan?',
      'If we had two free weeks starting tomorrow, what would we do?',
      'What outdoor thing should we try together this year?',
      "What's a food you want to eat in the country it's from?",
      'Road trip or flight — and who drives?',
      "What's a place near us we've never checked out?",
      'Would you rather move every year, or settle in one place?',
      "What's something adventurous you did that you'd never do again?",
      'If we could take one year off together, what would we do with it?',
      'What sound, smell, or place instantly makes you feel free?',
      "What's a small adventure we could have this weekend?",
    ],
    couples: [
      "What's the best trip you took before we met?",
      'What would our ideal anniversary trip look like?',
    ],
    friends: [
      "What's the best trip you've taken without anyone here?",
      'Who in this room is the best person to travel with? Be honest.',
    ],
  },
  everyday: {
    shared: [
      "What's the best part of a normal day for you?",
      'Coffee or tea? How do you take it? Do I even know?',
      "What's your favorite way to waste an hour?",
      "What's on your mind most often lately?",
      "What's a chore you'd happily pay someone else to do forever?",
      'What do you look forward to most on a normal weekday?',
      "What's your comfort food when things go wrong?",
      'How do you actually like to be woken up?',
      "What's the last thing that made you laugh out loud?",
      'What is your phone taking time away from?',
      "What's your favorite thing we do that costs nothing?",
      'How are you really doing? Not the quick answer.',
      "What's something small I do that annoys you? Be honest, be kind.",
    ],
    couples: [
      'How do you like to be greeted when I get home?',
      'Early bird or night owl? Does that cause problems for us?',
      'What does a good normal night together look like?',
    ],
    friends: [
      "What's the group chat actually for?",
      "Who here takes longest to reply, and what's the excuse?",
      'What does a good normal night with friends look like to you?',
    ],
  },
};

// type: 'moveSelf' | 'swapPositions' | 'joinPartner' | 'skipTurn' | 'extraTurn'
//     | 'lovePoints' | 'bothPoints' | 'action' | 'giftPoints'
//
// `friends` is the wording used in Friends mode — most of these are mechanical
// and only need "your partner" swapped for "another player". `only` restricts
// a card to one mode, which is how the romantic dares stay out of a game
// between friends.
const SURPRISES = [
  {
    icon: '🔀',
    text: 'Swap places with your partner!',
    friends: 'Swap places with another player!',
    type: 'swapPositions',
  },
  { icon: '⬆️', text: 'Lucky leap — forward 4 spaces.', type: 'moveSelf', value: 4 },
  { icon: '⬇️', text: 'Stumble — back 3 spaces.', type: 'moveSelf', value: -3 },
  { icon: '🔁', text: 'Roll again!', type: 'extraTurn' },
  { icon: '⏸️', text: 'Skip your next turn.', type: 'skipTurn', target: 'self' },
  {
    icon: '🚫',
    text: 'Your partner skips their next turn!',
    friends: 'Another player skips their next turn!',
    type: 'skipTurn',
    target: 'opponent',
  },
  {
    icon: '💞',
    text: '+5 Love Points.',
    friends: '+5 points.',
    type: 'lovePoints',
    value: 5,
    target: 'self',
  },
  {
    icon: '💔',
    text: '-3 Love Points.',
    friends: '-3 points.',
    type: 'lovePoints',
    value: -3,
    target: 'self',
  },
  {
    icon: '🤗',
    text: 'Hug your partner right now.',
    friends: 'Hug the player on your left.',
    type: 'action',
    bonus: 2,
  },
  { icon: '😘', text: 'Kiss your partner on the cheek.', type: 'action', bonus: 2, only: 'couples' },
  { icon: '📸', text: 'Take a photo together.', type: 'action', bonus: 2 },
  {
    icon: '🎁',
    text: 'Give 3 Love Points to your partner.',
    friends: 'Give 3 points to another player.',
    type: 'giftPoints',
    value: 3,
  },
  { icon: '🍀', text: 'Lucky streak — forward 6 spaces.', type: 'moveSelf', value: 6 },
  { icon: '🎯', text: 'Forward 2 spaces.', type: 'moveSelf', value: 2 },
  { icon: '🌪️', text: 'Blown back 5 spaces.', type: 'moveSelf', value: -5 },
  {
    icon: '🧲',
    text: "Magnet — move to your partner's square.",
    friends: "Magnet — move to another player's square.",
    type: 'joinPartner',
  },
  {
    // "You BOTH" was wrong from three players up — this card has always paid
    // everyone at the table.
    icon: '🤝',
    text: 'Everyone gains 3 Love Points.',
    friends: 'Everyone gains 3 points.',
    type: 'bothPoints',
    value: 3,
  },
  {
    icon: '💌',
    text: 'Your partner gains 4 Love Points — tell them why.',
    friends: 'Another player gains 4 points — tell them why.',
    type: 'lovePoints',
    value: 4,
    target: 'opponent',
  },
  {
    icon: '💐',
    text: 'Say three things you appreciate about your partner.',
    friends: 'Say three things you appreciate about the player on your right.',
    type: 'action',
    bonus: 3,
  },
  {
    icon: '🎵',
    text: 'Play a song that reminds you of your partner.',
    friends: 'Play a song that reminds you of someone here.',
    type: 'action',
    bonus: 3,
  },
  {
    icon: '☕',
    text: 'Promise a coffee date this week — pick the day now.',
    friends: 'Promise this group a night out — pick the date now.',
    type: 'action',
    bonus: 2,
  },
  {
    icon: '🎭',
    text: "Act out your partner's most-used phrase.",
    friends: "Act out another player's most-used phrase.",
    type: 'action',
    bonus: 2,
  },
  { icon: '🕯️', text: 'Hold hands in silence for 20 seconds.', type: 'action', bonus: 3, only: 'couples' },
  {
    icon: '🙈',
    text: "Close your eyes and describe your partner's face.",
    type: 'action',
    bonus: 2,
    only: 'couples',
  },
  {
    icon: '⭐',
    text: 'Name one thing your partner did well today.',
    friends: 'Name one thing another player did well today.',
    type: 'action',
    bonus: 2,
  },
  {
    icon: '🎤',
    text: 'Let the group ask you one question. You have to answer it.',
    type: 'action',
    bonus: 3,
    only: 'friends',
  },
  {
    icon: '👀',
    text: 'Tell the player on your left your honest first impression of them.',
    type: 'action',
    bonus: 3,
    only: 'friends',
  },
];
