const BOARD_SETUP = {
  ladders: 7,
  snakes: 7,
  minSpan: 8,
  maxSpan: 26,
  maxEndpointsPerRow: 4,
  surpriseChance: 0.25,
};

// One of these is picked at random for every new game. Each defines the page
// backdrop AND the board surface, ladder and snake colours together, so the
// board always sits in the same world as the background behind it.
const BOARD_THEMES = {
  romance: {
    label: 'Romance',
    page: 'radial-gradient(1100px 620px at 50% -12%, #fff7f4 0%, transparent 62%), radial-gradient(900px 520px at 92% 104%, #ecdfff 0%, transparent 58%), linear-gradient(160deg, #fdeef1 0%, #f5e8f7 52%, #ffeef0 100%)',
    pageBase: '#f5e8f7',
    boardBg: 'linear-gradient(155deg, #fffdf9, #fdf1ea)',
    frame: '#ffffff',
    cell: 'linear-gradient(160deg, #fffdfa, #fff8f3)',
    cellAlt: 'linear-gradient(160deg, #fdeff1, #fbe7ec)',
    cellBorder: 'rgba(240, 219, 227, 0.7)',
    cellInk: '#8a7681',
    edge: ['#f0d9dd', '#e9cbd2', '#e0bac4', '#d5a7b4', '#c996a6'],
    dropShadow: 'rgba(120, 40, 80, 0.3)',
    ladder: { dark: '#a85f6d', light: '#f0b9a6', foot: '#d38f88' },
    snake: { body: '#7d4e66', outline: '#3d2233', belly: '#ead5d6', head: '#6f4159' },
    accent: '#d6336c',
    accentDeep: '#a52551',
    pageTexture:
      "<svg xmlns='http://www.w3.org/2000/svg' width='120' height='120'><g fill='#d6336c' fill-opacity='0.07'><path d='M30 26c-4-6-14-5-14 3 0 7 9 12 14 17 5-5 14-10 14-17 0-8-10-9-14-3z'/><path d='M88 74c-3-5-11-4-11 2 0 6 7 10 11 14 4-4 11-8 11-14 0-6-8-7-11-2z'/><circle cx='95' cy='25' r='2.5'/><circle cx='22' cy='92' r='2'/></g></svg>",
    pageTextureSize: '120px 120px',
    cellTexture:
      "<svg xmlns='http://www.w3.org/2000/svg' width='16' height='16'><g stroke='#b07a8e' stroke-opacity='0.09' stroke-width='1'><path d='M0 4h16M0 12h16'/><path d='M4 0v16M12 0v16'/></g></svg>",
    cellTextureSize: '16px 16px',
    photo: 'assets/textures/romance.webp',
    photoPageSize: '420px',
    photoPageOpacity: 0.42,
    photoBoardSize: '180px',
    photoBoardOpacity: 0.14,
    motion: 'twinkle', driftAxis: 'xy', driftDuration: '95s', boardDriftDuration: '150s', twinkleDuration: '7s',
    ornaments: ['💗', '✨', '🌸', '🌹', '🎀', '🍓'],
    startIcon: '💌', finishIcon: '💍',
  },
  forest: {
    label: 'Forest',
    page: 'radial-gradient(1100px 620px at 50% -12%, #f0f8ea 0%, transparent 62%), radial-gradient(900px 520px at 92% 104%, #cfe6d4 0%, transparent 58%), linear-gradient(160deg, #e4f1dc 0%, #d5e9d6 52%, #eaf5e2 100%)',
    pageBase: '#d5e9d6',
    boardBg: 'linear-gradient(155deg, #fbfdf6, #e9f3e0)',
    frame: '#fbfdf7',
    cell: 'linear-gradient(160deg, #fbfdf6, #f2f9ea)',
    cellAlt: 'linear-gradient(160deg, #e7f2de, #dcebd2)',
    cellBorder: 'rgba(200, 224, 190, 0.75)',
    cellInk: '#6d8168',
    edge: ['#d8e8cf', '#cbe0c0', '#bcd6b0', '#a9c99c', '#96bb88'],
    dropShadow: 'rgba(40, 80, 45, 0.32)',
    ladder: { dark: '#8a5a2b', light: '#dca868', foot: '#b07c3f' },
    snake: { body: '#647d3f', outline: '#2c391b', belly: '#d3d9a4', head: '#586f37' },
    accent: '#3f8f4f',
    accentDeep: '#2c6b39',
    pageTexture:
      "<svg xmlns='http://www.w3.org/2000/svg' width='140' height='140'><g fill='#2f5c2c' fill-opacity='0.08'><path d='M20 30c14-12 30-10 34 2-12 12-28 12-34-2z'/><path d='M100 88c12-14 28-14 34-3-10 13-26 15-34 3z'/><path d='M60 118c8-10 20-10 24-2-8 9-19 10-24 2z'/></g><g stroke='#2f5c2c' stroke-opacity='0.07' stroke-width='1.2' fill='none' stroke-linecap='round'><path d='M20 30c11 1 23 2 34 2'/><path d='M100 88c11 0 24 2 34-3'/><path d='M60 118c8 0 17 1 24-2'/></g></svg>",
    pageTextureSize: '140px 140px',
    cellTexture:
      "<svg xmlns='http://www.w3.org/2000/svg' width='60' height='24'><g stroke='#5a7a48' stroke-opacity='0.09' stroke-width='1' fill='none'><path d='M0 6q15-4 30 0t30 0'/><path d='M0 14q15 4 30 0t30 0'/><path d='M0 21q15-3 30 0t30 0'/></g></svg>",
    cellTextureSize: '60px 24px',
    photo: 'assets/textures/forest.webp',
    photoPageSize: '460px',
    photoPageOpacity: 0.40,
    photoBoardSize: '200px',
    photoBoardOpacity: 0.13,
    motion: 'drift', driftAxis: 'xy', driftDuration: '60s', boardDriftDuration: '110s',
    ornaments: ['🍃', '🌲', '🍄', '🌿', '🍂', '🐿️'],
    startIcon: '🌱', finishIcon: '🌳',
  },
  ocean: {
    label: 'Ocean',
    page: 'radial-gradient(1100px 620px at 50% -12%, #eaf7fb 0%, transparent 62%), radial-gradient(900px 520px at 92% 104%, #c9e2f2 0%, transparent 58%), linear-gradient(160deg, #ddeff7 0%, #cfe4f2 52%, #e8f5fb 100%)',
    pageBase: '#cfe4f2',
    boardBg: 'linear-gradient(155deg, #f9fdff, #e2f0f9)',
    frame: '#f9fdff',
    cell: 'linear-gradient(160deg, #f9fdff, #eef8fd)',
    cellAlt: 'linear-gradient(160deg, #e0eff8, #d3e6f3)',
    cellBorder: 'rgba(190, 217, 232, 0.75)',
    cellInk: '#5f8194',
    edge: ['#cfe4ef', '#bcd9e9', '#a8cde0', '#93bed4', '#7eb0c8'],
    dropShadow: 'rgba(20, 70, 100, 0.32)',
    ladder: { dark: '#9a7b45', light: '#e8cc95', foot: '#c2a068' },
    snake: { body: '#407b86', outline: '#1b414a', belly: '#c3dcd8', head: '#386d78' },
    accent: '#2b8ca6',
    accentDeep: '#1d6b80',
    pageTexture:
      "<svg xmlns='http://www.w3.org/2000/svg' width='120' height='60'><g stroke='#1c5f6a' stroke-opacity='0.1' stroke-width='1.6' fill='none' stroke-linecap='round'><path d='M0 16q15-10 30 0t30 0 30 0 30 0'/><path d='M0 40q15-10 30 0t30 0 30 0 30 0'/></g></svg>",
    pageTextureSize: '120px 60px',
    cellTextureSize: '40px 20px',
    photo: 'assets/textures/ocean.webp',
    photoPageSize: '440px',
    photoPageOpacity: 0.45,
    photoBoardSize: '190px',
    photoBoardOpacity: 0.15,
    motion: 'drift', driftAxis: 'x', driftDuration: '26s', boardDriftDuration: '38s',
    ornaments: ['🐚', '⭐', '🫧', '🐠', '🌊', '🦀'],
    startIcon: '⚓', finishIcon: '🏝️',
    cellTexture:
      "<svg xmlns='http://www.w3.org/2000/svg' width='40' height='20'><g stroke='#2f8f9c' stroke-opacity='0.1' stroke-width='1' fill='none' stroke-linecap='round'><path d='M0 10q10-6 20 0t20 0'/></g></svg>",
  },
  meadow: {
    label: 'Meadow',
    page: 'radial-gradient(1100px 620px at 50% -12%, #f8fce9 0%, transparent 62%), radial-gradient(900px 520px at 92% 104%, #e0eec4 0%, transparent 58%), linear-gradient(160deg, #eff8dd 0%, #e6f2d4 52%, #f7fbe8 100%)',
    pageBase: '#e6f2d4',
    boardBg: 'linear-gradient(155deg, #fdfef7, #eef6dd)',
    frame: '#fdfef8',
    cell: 'linear-gradient(160deg, #fdfef7, #f6fbe8)',
    cellAlt: 'linear-gradient(160deg, #ecf6da, #e2efcb)',
    cellBorder: 'rgba(214, 230, 184, 0.75)',
    cellInk: '#77875c',
    edge: ['#e0ecc8', '#d3e4b6', '#c4daa4', '#b3cf90', '#a2c47c'],
    dropShadow: 'rgba(70, 90, 30, 0.3)',
    ladder: { dark: '#9c7b3a', light: '#ebcf88', foot: '#c0a05a' },
    snake: { body: '#8b9a3b', outline: '#474f1f', belly: '#e4e7aa', head: '#7e8d33' },
    accent: '#7ba337',
    accentDeep: '#5b7d26',
    pageTexture:
      "<svg xmlns='http://www.w3.org/2000/svg' width='100' height='100'><g stroke='#4f6b22' stroke-opacity='0.11' stroke-width='1.4' fill='none' stroke-linecap='round'><path d='M12 94c0-12 4-20 8-26'/><path d='M18 94c0-10-2-18-6-24'/><path d='M62 98c0-12 5-20 9-26'/><path d='M68 98c0-10-2-18-6-24'/><path d='M38 48c0-10 4-16 7-21'/><path d='M44 48c0-9-2-15-6-20'/></g></svg>",
    pageTextureSize: '100px 100px',
    cellTexture:
      "<svg xmlns='http://www.w3.org/2000/svg' width='24' height='24'><g fill='#5b7d26' fill-opacity='0.09'><circle cx='6' cy='7' r='1.4'/><circle cx='18' cy='16' r='1.2'/><circle cx='12' cy='3' r='1'/><circle cx='3' cy='19' r='1'/></g></svg>",
    cellTextureSize: '24px 24px',
    photo: 'assets/textures/meadow.webp',
    photoPageSize: '400px',
    photoPageOpacity: 0.42,
    photoBoardSize: '175px',
    photoBoardOpacity: 0.14,
    motion: 'drift', driftAxis: 'x', driftDuration: '42s', boardDriftDuration: '70s',
    ornaments: ['🌼', '🦋', '🌿', '🐞', '🌾', '🌷'],
    startIcon: '🌻', finishIcon: '🐝',
  },
  sunset: {
    label: 'Sunset',
    page: 'radial-gradient(1100px 620px at 50% -12%, #fff3e4 0%, transparent 62%), radial-gradient(900px 520px at 92% 104%, #f0d6ea 0%, transparent 58%), linear-gradient(160deg, #ffe9db 0%, #f8dde6 52%, #f4e2f2 100%)',
    pageBase: '#f8dde6',
    boardBg: 'linear-gradient(155deg, #fffaf3, #fbe9db)',
    frame: '#fffaf4',
    cell: 'linear-gradient(160deg, #fffaf3, #fef2e7)',
    cellAlt: 'linear-gradient(160deg, #fbe8da, #f7ddcc)',
    cellBorder: 'rgba(240, 214, 194, 0.75)',
    cellInk: '#a2806c',
    edge: ['#f5d9c4', '#efcbb2', '#e7bb9e', '#dca786', '#cf9370'],
    dropShadow: 'rgba(130, 60, 40, 0.32)',
    ladder: { dark: '#9c5a30', light: '#f4bf8c', foot: '#c98b55' },
    snake: { body: '#a8683f', outline: '#54301e', belly: '#f1d4b3', head: '#985a30' },
    accent: '#e2703a',
    accentDeep: '#b4531f',
    pageTexture:
      "<svg xmlns='http://www.w3.org/2000/svg' width='160' height='120'><g fill='#b4531f' fill-opacity='0.055'><ellipse cx='40' cy='28' rx='34' ry='9'/><ellipse cx='120' cy='76' rx='40' ry='10'/><ellipse cx='74' cy='104' rx='26' ry='7'/></g><g stroke='#b4531f' stroke-opacity='0.05' stroke-width='1.2' fill='none'><path d='M0 52h160'/><path d='M0 92h160'/></g></svg>",
    pageTextureSize: '160px 120px',
    cellTexture:
      "<svg xmlns='http://www.w3.org/2000/svg' width='20' height='20'><g fill='#9c5a30' fill-opacity='0.08'><circle cx='4' cy='5' r='1'/><circle cx='14' cy='12' r='1.1'/><circle cx='9' cy='17' r='0.9'/></g></svg>",
    cellTextureSize: '20px 20px',
    photo: 'assets/textures/sunset.webp',
    photoPageSize: '450px',
    photoPageOpacity: 0.42,
    photoBoardSize: '195px',
    photoBoardOpacity: 0.14,
    motion: 'drift', driftAxis: 'x', driftDuration: '75s', boardDriftDuration: '120s',
    ornaments: ['🌇', '🕊️', '☁️', '🌅', '🐦', '✨'],
    startIcon: '🌤️', finishIcon: '🌆',
  },
  night: {
    label: 'Night',
    // The one dark scene: white frost over it turns grey and unreadable, so the
    // UI glass flips to a dark tint with light text (see [data-glass] in style.css).
    glass: 'dark',
    page:'radial-gradient(1100px 620px at 50% -12%, #333c63 0%, transparent 62%), radial-gradient(900px 520px at 92% 104%, #3a2a5c 0%, transparent 58%), linear-gradient(160deg, #1e2438 0%, #262040 52%, #1a2032 100%)',
    pageBase: '#262040',
    boardBg: 'linear-gradient(155deg, #303858, #242a44)',
    frame: '#3c4468',
    cell: 'linear-gradient(160deg, #333c5e, #2c3452)',
    cellAlt: 'linear-gradient(160deg, #2a3150, #242b46)',
    cellBorder: 'rgba(90, 100, 145, 0.5)',
    cellInk: '#9aa4ca',
    edge: ['#262d4a', '#212843', '#1c223a', '#171d31', '#131828'],
    dropShadow: 'rgba(0, 0, 0, 0.55)',
    ladder: { dark: '#5f6890', light: '#cdd6f5', foot: '#98a1c8' },
    snake: { body: '#5a639b', outline: '#20264c', belly: '#c8cef1', head: '#4f588d' },
    accent: '#8b6ee8',
    accentDeep: '#6a4fd0',
    pageTexture:
      "<svg xmlns='http://www.w3.org/2000/svg' width='140' height='140'><g fill='#ffffff' fill-opacity='0.5'><circle cx='20' cy='28' r='1.3'/><circle cx='96' cy='18' r='1'/><circle cx='124' cy='62' r='1.4'/><circle cx='58' cy='76' r='1'/><circle cx='34' cy='112' r='1.2'/><circle cx='108' cy='120' r='1'/><circle cx='78' cy='44' r='0.8'/><circle cx='8' cy='66' r='0.9'/></g><g fill='#cbbcff' fill-opacity='0.6'><path d='M62 14l1.4 3.6L67 19l-3.6 1.4L62 24l-1.4-3.6L57 19l3.6-1.4z'/><path d='M116 92l1.2 3 3 1.2-3 1.2-1.2 3-1.2-3-3-1.2 3-1.2z'/></g></svg>",
    pageTextureSize: '140px 140px',
    cellTexture:
      "<svg xmlns='http://www.w3.org/2000/svg' width='30' height='30'><g fill='#9aa4ca' fill-opacity='0.18'><circle cx='7' cy='8' r='0.9'/><circle cx='22' cy='19' r='0.7'/><circle cx='16' cy='27' r='0.6'/></g></svg>",
    cellTextureSize: '30px 30px',
    photo: 'assets/textures/night.webp',
    photoPageSize: '480px',
    photoPageOpacity: 0.55,
    photoBoardSize: '210px',
    photoBoardOpacity: 0.20,
    motion: 'twinkle', driftAxis: 'x', driftDuration: '140s', boardDriftDuration: '190s', twinkleDuration: '4.5s',
    ornaments: ['✨', '🌙', '⭐', '🦉', '🌌', '🔭'],
    startIcon: '🌠', finishIcon: '🌕',
  },
};

// The game is played in one of two modes, chosen on the setup screen. Mode
// decides which questions, dares and surprises are in play, and what the AI is
// told about who is sitting at the table — a group of friends should never be
// handed "give your partner a shoulder massage", and the model should never
// write a romantic prompt for people who aren't a couple.
const MODES = {
  couples: {
    label: 'Couples',
    hint: 'Questions and dares written for two partners.',
    subject: 'Two partners are playing a board game designed to bring them closer together.',
    guard: '',
    points: 'Love Points',
  },
  friends: {
    label: 'Friends',
    hint: 'Nothing romantic — written for friends playing together.',
    subject:
      'A group of friends is playing a board game designed to help them know each other better.',
    guard:
      'They are friends, not romantic partners. Never imply romance, dating, flirting or physical intimacy.',
    points: 'points',
  },
};

// `friendsLabel` renames a theme in Friends mode where the couples wording
// would be wrong. `color` marks the topic's swatch on its chip and question card.
const QUESTION_THEMES = {
  general: { label: 'General', color: '#3b7dd8' },
  love: { label: 'Love', friendsLabel: 'Closeness', color: '#d6336c' },
  money: { label: 'Money', color: '#2f9e5b' },
  dreams: { label: 'Dreams', color: '#8b5fbf' },
  dare: { label: 'Fun & Dare', color: '#e08a2c' },
  deep: { label: 'Deep Talk', color: '#2c7a7b' },
  memories: { label: 'Memories', color: '#b5763a' },
  home: { label: 'Home & Family', color: '#4a7f9e' },
  growth: { label: 'Growth', color: '#5c9e46' },
  gratitude: { label: 'Gratitude', color: '#c2811f' },
  adventure: { label: 'Adventure', color: '#3d8f8f' },
  everyday: { label: 'Everyday', color: '#8a6a9e' },
};

// Each theme is `shared` (works for anyone at the table) plus one list per
// mode. The pool for a game is shared + that mode's list — see questionPool()
// in script.js. Splitting them this way rather than keeping two whole banks
// means the ~60% of questions that were already neutral are written once.
const QUESTIONS = {
  general: {
    shared: [
      "What's one skill you wish we could learn together?",
      "What's a movie or show we should watch together this month?",
      'If we traded lives for a day, what would you do first?',
      "What's a nickname or inside joke of ours you love?",
      'What surprised you about me when we first met?',
      'What song reminds you of us?',
      "What's the best meal we've ever shared?",
      "What's a habit of mine that you now do too?",
      "What's one small thing I could do this week to make you happy?",
      'Who would survive a zombie attack better, and why?',
      "What's a small thing that instantly puts you in a good mood?",
      "If you could relive one ordinary day, which would you pick?",
      "What's a rule you think everyone should live by?",
      "What's the last thing you learned that changed how you think?",
      "If you had an extra hour today, what would you do with it?",
      "What's something everyone gets wrong about you?",
      "What's a question you wish people asked you more?",
      "What's the best advice you've ever ignored?",
    ],
    couples: [
      "What's a small thing your partner does that makes you smile?",
      'If we could go anywhere right now for a date, where would we go?',
      "What's something funny to you that your partner doesn't get?",
      'If we got a pet tomorrow, what would we name it?',
      'If our life was a movie, what type would it be?',
      "What's your favorite corner of our home?",
      "What's a habit of your partner's you didn't expect to fall for?",
      "What do you and your partner argue about that's actually kind of funny?",
      "What's a rule the two of you have that nobody else would understand?",
      "If you had to describe your relationship as a weather forecast, what would it be?",
      "What's something you do differently since being with your partner?",
      "What's a household task you've silently claimed as 'yours'?",
      "What's the last thing your partner did that you're still thinking about?",
      "If your partner narrated your life, what would the opening line be?",
      "What's a food only your partner could talk you into trying?",
      "What's a tiny tradition just the two of you have?",
      "What would your partner say is your most annoying quality?",
      "What's something you two used to disagree on that you now agree on?",
      "What's the weirdest thing you've bonded over together?",
      "If you could freeze one ordinary moment with your partner, which one?",
      "What's a compliment you give your partner that you mean every time?",
      "What TV character reminds you most of your partner?",
      "What's something your partner is better at than they realize?",
      "What's the most 'you two' thing you've ever done?",
      "If your relationship had a theme song, what would it be?",
      "What's a small inconvenience you'd happily deal with forever for your partner?",
      "What's something you've never told your partner but should?",
      "What's a nickname you'd never say out loud but secretly think?",
      "What's the best thing about doing nothing together?",
      "What's a plan you two keep talking about but never actually do?",
      "What's something your partner taught you without meaning to?",
      "What's your favorite way to spend a lazy Sunday together?",
      "What's a running joke between you two that outsiders never get?",
      "What's one thing you'd want your partner to know before this game ends?",
    ],
    friends: [
      "What's the most useless talent you have?",
      'Who here would you call first in an emergency, and why?',
      'What show would you make everyone here sit through?',
      'If we started a band tomorrow, who plays what?',
      "What's a rumour about you that turned out to be true?",
      'Who here has changed the most since you met them?',
      "What's a rule this group has that outsiders would find strange?",
      "Who here gives the worst directions, and does everyone still trust them?",
      "What's the most chaotic plan this group has ever pulled off?",
      "If this group had a group chat name, what should it be?",
      "What's a food everyone here argues about?",
      "Who's most likely to answer a 3am text from the group?",
      "What's something you've only ever laughed about with people in this room?",
      "If this group went on a game show together, what would it be?",
      "Who here has the worst taste in music, honestly?",
      "What's a tradition this group should actually start?",
      "Who's the one everyone secretly copies without admitting it?",
      "What's the most 'us' thing this group has ever done?",
      "If someone made a movie about this friend group, what genre would it be?",
      "What's something small someone here does that always makes you laugh?",
      "Who here would survive longest without their phone?",
      "What's a nickname this group should give to someone who doesn't have one?",
      "What's the group's unofficial motto?",
      "Who's most likely to be late, and what's always the excuse?",
      "What's the best thing about doing nothing with this group?",
      "What's a plan this group keeps talking about but never does?",
      "Who taught you something without realizing it?",
      "What's your favorite way to spend a lazy day with this group?",
      "What's a running joke here that outsiders never get?",
      "What's one thing you'd want this group to know before tonight ends?",
      "Who here is the designated planner, whether they wanted the job or not?",
      "What's the most trouble this group has ever gotten into together?",
      "If this group had a mascot, what would it be and why?",
      "Who's the peacemaker when this group argues?",
    ],
  },
  love: {
    shared: [
      "What's the best way to comfort you when you're sad?",
      "What's something you've never said out loud, but want me to know?",
      'Give someone here a real compliment right now.',
      "What's the best way we say sorry to each other?",
      "What's one thing you never want us to stop doing together?",
      "What's a way you feel loved that most people wouldn't guess?",
      "What does love look like on an ordinary Tuesday, not a special occasion?",
      "Who taught you what love should feel like?",
      "What's a small act of love you never get tired of?",
      "What's something you associate with the word 'love' that surprises you?",
      "How do you know when someone truly cares, versus just being nice?",
      "What's a love language you didn't know you had until recently?",
      "What's the difference between being loved and being understood?",
      "What's a moment you felt completely loved, no explanation needed?",
      "What's something that makes you feel unlovable, even briefly?",
      "What's a way you show love that people often miss?",
      "What's the bravest thing you've done for love?",
      "What does it mean to love someone even on their worst day?",
    ],
    couples: [
      'What made you fall for your partner at first?',
      'Describe your partner in three words — say them out loud.',
      'What small thing makes you feel most loved?',
      'What do you love most about how your partner treats you?',
      'When do you feel closest to your partner?',
      'What promise do you want to make to each other tonight?',
      'When did you know you loved me?',
      "What's the best thing about us as a couple?",
      'How has loving me changed you?',
      'If our love was a color, what would it be, and why?',
      'What does being loved by me feel like?',
      "What's a moment you realized this relationship was different from others?",
      "What do you think your partner needs to hear more often?",
      "What's the most romantic thing your partner has ever done, even if small?",
      "How does your partner make hard days easier?",
      "What's something about loving your partner that surprised you?",
      "What do you want your partner to never doubt about your love?",
      "What's a fear about love your partner has helped you get past?",
      "How has your definition of love changed since being with your partner?",
      "What's the softest side of your partner that only you get to see?",
      "What does your partner do that makes you feel chosen?",
      "What's a way you two show love without saying a word?",
      "What's something you'd want to redo, if you could, in how you've loved your partner?",
      "What's a love story detail about you two that still gives you butterflies?",
      "What's the bravest thing love has asked of you in this relationship?",
      "How do you want to be loved when things go wrong?",
      "What's a quiet way your partner has loved you that you never mentioned?",
      "What does 'forever' mean to you in this relationship?",
      "What's something you love about loving your partner, not just about them?",
      "What's a moment your partner loved you exactly as you were, flaws included?",
      "How do you want love to feel in ten years, compared to now?",
      "What's a way your partner has loved you better than anyone before?",
      "What do you hope your partner never forgets about how much you love them?",
      "What's the one thing love with your partner has taught you about yourself?",
    ],
    friends: [
      'What made you decide I was a real friend, not just someone you knew?',
      'Describe me in three words — say them out loud.',
      'What do you need from a friend that you find hard to ask for?',
      'When have you felt most looked after by someone here?',
      "What's something you appreciate about me that I probably don't know?",
      'What makes someone a good friend, to you?',
      'Who here would you want beside you on the worst day of your life?',
      "What's the kindest thing anyone here has done for you?",
      "What's a moment you realized this friendship was different from others?",
      "What do you think I need to hear more often?",
      "What's the kindest thing anyone here has done without being asked?",
      "How does this group make hard days easier?",
      "What's something about caring for people here that surprised you?",
      "What do you want the people here to never doubt about your loyalty?",
      "What's a fear about friendship someone here has helped you get past?",
      "How has your definition of a good friend changed over the years?",
      "What's the softest side of you that only close friends get to see?",
      "What do the people here do that makes you feel chosen?",
      "What's a way friends show they care without saying it out loud?",
      "What's something you'd want to redo in how you've shown up for a friend?",
      "What's a friendship memory that still gives you a warm feeling?",
      "What's the bravest thing friendship has asked of you?",
      "How do you want friends to show up when things go wrong for you?",
      "What's a quiet way someone here has cared for you that you never mentioned?",
      "What does 'ride or die' mean to you in this group?",
      "What's something you love about caring for people, not just about them?",
      "What's a moment someone here accepted you exactly as you were, flaws included?",
      "How do you want this friendship to feel in ten years, compared to now?",
      "What's a way someone here has shown up for you better than anyone before?",
      "What do you hope this group never forgets about how much you care?",
      "What's the one thing this friendship has taught you about yourself?",
      "Who here would you trust with something you've never told anyone?",
      "What's a way you've learned to love people better because of this group?",
      "What's something you appreciate that nobody here has ever said out loud?",
    ],
  },
  money: {
    shared: [
      'What money habit from your family do you want to keep or drop?',
      'What does feeling safe with money look like to you?',
      'If you got a lot of extra money tomorrow, save it, spend it, or split it?',
      "What's something fun you'd happily spend too much on?",
      "What's the best money decision you've ever made?",
      "What's one money talk you keep putting off?",
      "What's a skill you'd pay real money to learn?",
      "What's a purchase you don't regret, even though it was expensive?",
      "Do you see money as freedom, security, or something else entirely?",
      "What's a financial habit you picked up from watching someone else struggle?",
      "Would you rather have more time or more money right now?",
      "What's the most impulsive purchase you've ever made?",
      "What's a subscription or bill you keep meaning to cancel?",
      "What does 'rich' actually mean to you, beyond the number?",
      "What's something you'd never cut from your budget, no matter what?",
      "What's a money lesson you learned the hard way?",
      "Would you rather be secretly wealthy or openly comfortable?",
      "What's the smallest thing you've spent money on that made you truly happy?",
    ],
    couples: [
      "What's one money goal we should set this year?",
      'If we had an extra $500 this month, what would we do with it?',
      "What money habit of your partner's do you like?",
      'How do you feel about our savings plan?',
      "What's a big thing we should start saving for?",
      "Do we agree on how we split bills?",
      'What could we spend less on to save for something bigger?',
      'Where do you see us with money in 5 years?',
      'Are we saving enough for fun, or too focused on later?',
      'Should we each get money to spend with no questions asked?',
      "What's a purchase you've made that your partner still doesn't fully understand?",
      "How do you want to handle a big unexpected expense together?",
      "What's something financially you're proud we figured out together?",
      "Do you feel like we're a team with money, or still figuring it out?",
      "What's a money conversation we've been avoiding?",
      "What would you do differently if we combined all our finances tomorrow?",
      "What's something expensive you'd want us to save for as a couple?",
      "How do you feel about surprise gifts that cost real money?",
      "What's your honest reaction when I make a big purchase without asking?",
      "What financial habit of mine would you want to gently change?",
      "What's a shared money goal that would make you feel proud of us?",
      "Would you rather retire early and live simply, or work longer and live bigger?",
      "What's the most generous thing you've seen me do with money?",
      "How should we handle it if one of us earns a lot more than the other?",
      "What's something we spend on that's worth every penny?",
      "What financial fear do you have that I might not know about?",
      "What's a financial win we should celebrate more than we did?",
      "How do you want us to teach our future selves (or kids) about money?",
      "What's something you'd sacrifice financially for this relationship, no question asked?",
      "What's a purchase you'd want us to make together, not separately?",
      "How do you feel about debt — something to avoid entirely, or a normal tool?",
      "What's a financial habit of yours you're trying to break for us?",
      "What would financial 'enough' look like for our life together?",
      "What's the most romantic thing that's ever been done with money, in your opinion?",
    ],
    friends: [
      'Is splitting a bill with friends easy for you, or quietly awkward?',
      'Would you lend a friend money?',
      "What's the most you've spent on something nobody else understood?",
      'Do your friends know roughly what you earn?',
      "What's a trip you'd take with people here if money appeared tomorrow?",
      "What did you waste money on at 20 that you'd never buy now?",
      "What's a purchase you've made that your friends still don't fully understand?",
      "How do you feel when a friend suddenly seems to have a lot more money than you?",
      "What's something financially you're proud you figured out on your own?",
      "What's a money conversation you've avoided having with a friend?",
      "Would you ever loan a large amount to someone in this room?",
      "What's something expensive you'd want to save for with people here?",
      "How do you feel about splitting gifts for someone in this group?",
      "What's your honest reaction when a friend makes a big purchase you wouldn't?",
      "What financial habit of a friend here would you want to gently change?",
      "What's a shared goal with this group that would take real money to pull off?",
      "Would you rather retire early and live simply, or work longer and live bigger?",
      "What's the most generous thing you've seen someone here do with money?",
      "How should friends handle it when one earns a lot more than the others?",
      "What's something this group spends on that's worth every penny?",
      "What financial fear do you have that people here might not know about?",
      "What's a financial win of yours that deserved more celebration than it got?",
      "What's something you'd sacrifice financially for a friend, no question asked?",
      "What's a purchase you'd only make if someone here talked you into it?",
      "How do you feel about debt — something to avoid entirely, or a normal tool?",
      "What's a financial habit of yours you're actively trying to break?",
      "What would financial 'enough' look like for your life?",
      "What's the most generous gift you've ever given someone in this room?",
      "Who here is most likely to actually become rich, and how?",
      "What's a money mistake you'd warn everyone here about?",
      "Would you rather everyone here knew your salary, or nobody ever found out?",
      "What's the best free thing this group has ever done together?",
      "What's a splurge you'd only justify doing with this group?",
      "If this group started a business together, who'd handle the money?",
    ],
  },
  dreams: {
    shared: [
      "What's a skill you want to learn well before you turn 60?",
      "If money didn't matter, how would you spend next year?",
      'What would a perfect normal Tuesday look like for you?',
      "What's a dream you gave up that you'd like to start again?",
      "What's one adventure we haven't tried that you want to?",
      'If we could live in another country for a year, where and why?',
      "What's something on your list we should do together this year?",
      'If we could start a business together, what would it be?',
      "What's a dream you've never told anyone about?",
      "If you could master any skill overnight, what would you pick?",
      "What's a version of your future self you're excited to become?",
      "What's something you'd regret never trying?",
      "If you had unlimited courage for one day, what would you do?",
      "What's a dream that scares you a little because it actually matters?",
      "What's one thing on your bucket list that's actually achievable this year?",
      "What would you do differently if you weren't afraid of failing?",
      "What's a dream you had as a kid that still quietly matters to you?",
      "If you could guarantee success at one thing, what would you finally try?",
    ],
    couples: [
      "What's a dream trip you want us to take together someday?",
      'Where do you see us living in 10 years?',
      'What does your dream life with your partner look like?',
      "What's a tradition you'd like us to start as a couple?",
      "What's something you hope never changes about us?",
      "What goal are you working on that you want your partner's help with?",
      'What kind of older couple do you want us to become?',
      'What do you want people to say about us in 30 years?',
      "What's a dream you have that you haven't fully shared with your partner?",
      "How can your partner support a goal you're chasing right now?",
      "What's something you dream of building together, not just experiencing?",
      "If we could design our future home from scratch, what's non-negotiable?",
      "What's a version of 'us' in ten years that excites you most?",
      "What's a dream you gave up that your partner could help you pick back up?",
      "What legacy do you want the two of us to leave behind?",
      "What's something you want to accomplish before you're a certain age, together?",
      "What's a shared dream that feels a little out of reach right now?",
      "How do you want to grow old together, practically speaking?",
      "What's something your partner dreams about that you want to help make real?",
      "What's a risk you'd take together if failure wasn't a possibility?",
      "What does your ideal retirement with your partner look like?",
      "What's a skill you wish the two of you could learn together?",
      "What's a place you dream of calling home together someday?",
      "What's something about your future together that you've never said out loud?",
      "If you had to describe your shared dream in one sentence, what would it be?",
      "What's a goal of your partner's you quietly cheer for the most?",
      "What's a dream for this relationship you haven't dared say yet?",
      "What would you want to build together if money or time weren't limits?",
      "What's a version of adventure you want your partner to experience with you?",
      "How do you want your partner to remind you of your dreams when you forget them?",
      "What's something you hope you're still dreaming about together in 20 years?",
      "What's a dream you're scared to want out loud?",
      "What's a promise about the future you'd want to make right now?",
      "What's one thing you want to make sure you do together before it's too late?",
    ],
    friends: [
      "Where do you want to be living in ten years — and who's nearby?",
      "What's a trip this group should actually book, not just talk about?",
      'What do you want to be known for by the people who know you?',
      'What goal are you working on that someone here could help with?',
      'What kind of old person do you want to be?',
      "What's a tradition you'd like this group to start?",
      'What do you hope never changes about your friends?',
      "What's a dream you have that you haven't fully shared with anyone here?",
      "How can this group support a goal you're chasing right now?",
      "What's something you dream of building with people here, not just experiencing?",
      "If this group could design a shared project from scratch, what would it be?",
      "What's a version of this friend group in ten years that excites you most?",
      "What's a dream you gave up that someone here could help you pick back up?",
      "What legacy do you want this friend group to leave behind?",
      "What's something you want to accomplish before a certain age, with this group cheering?",
      "What's a shared dream for this group that feels a little out of reach right now?",
      "How do you want to stay close to this group as you get older?",
      "What's something someone here dreams about that you want to help make real?",
      "What's a risk you'd take with this group if failure wasn't a possibility?",
      "What does your ideal reunion with this group look like in twenty years?",
      "What's a skill you wish this group could learn together?",
      "What's a place you dream of gathering this group someday?",
      "What's something about your future you've never said out loud to anyone here?",
      "If you had to describe your biggest dream in one sentence, what would it be?",
      "What's a goal of someone here you quietly cheer for the most?",
      "What's a dream for this friendship you haven't dared say yet?",
      "What would you want to build with this group if money or time weren't limits?",
      "What's a version of adventure you want to experience with people here?",
      "How do you want this group to remind you of your dreams when you forget them?",
      "What's something you hope you're still doing with this group in 20 years?",
      "What's a dream you're scared to want out loud?",
      "What's a promise about the future you'd want to make to this group right now?",
      "What's one thing you want to make sure you do with this group before it's too late?",
      "What's a dream someone here has that deserves more support than it's getting?",
    ],
  },
  dare: {
    shared: [
      'Take a silly selfie together right now.',
      "Swap phones and change each other's wallpaper.",
      'Sing the chorus of a song everyone here knows.',
      'Talk for 30 seconds about something you love. No "um".',
      'Speak in an accent until your next turn.',
      "Do your best dance move for 10 seconds. No excuses.",
      "Say the alphabet backwards. Everyone's watching.",
      "Let the group pick a silly nickname for you for the rest of the game.",
      "Try to lick your elbow. Just try.",
      "Do your best celebrity impression until someone guesses who.",
      "Balance something on your head for 15 seconds.",
      "Text a random emoji to the last person you texted, no explanation.",
      "Hold a plank for 20 seconds while telling a joke.",
      "Let someone else style your hair for the next round.",
      "Speak only in questions until your next turn.",
      "Do an impression of how you woke up this morning.",
      "Show the weirdest photo in your camera roll.",
      "Freeze in a dramatic pose for 10 seconds, no laughing.",
    ],
    couples: [
      'Give your partner a 10-second hug right now.',
      'Do your best impression of your partner.',
      'Say "I love you" in a funny accent.',
      "Whisper something sweet in your partner's ear.",
      'Slow dance for 15 seconds. No music needed.',
      'Feed your partner a snack or a sip of a drink.',
      'Act out how you two met, like a movie scene.',
      "Hold hands and look into each other's eyes for 20 seconds. Don't laugh.",
      'Give your partner a compliment with your hands only. No talking.',
      'Give your partner a 30-second shoulder massage.',
      'Try to make your partner laugh in 15 seconds without touching them.',
      'Sing the chorus of "your" song together.',
      "Draw something on your partner's palm with your finger. They guess it.",
      "Say three things you love about your partner. Don't repeat a word.",
      "Recreate your first photo together, pose and all.",
      "Trace your partner's name on their back. They have to guess it.",
      "Give your partner a nickname based on how they were acting today.",
      "Tell your partner the exact moment you knew you wanted to date them.",
      "Do a 10-second slow-motion replay of how you met.",
      "Let your partner pick your outfit for tomorrow, sight unseen.",
      "Serenade your partner with the worst possible song, straight face.",
      "Guess your partner's exact age when you tell them one thing you love about them.",
      "Draw a heart on the back of your hand and gift it to your partner.",
      "Whisper your favorite memory of your partner in their ear.",
      "Act out your partner's morning routine, exaggerated.",
      "Give your partner three seconds of uninterrupted eye contact, then a kiss on the hand.",
      "Try to guess what your partner is thinking right now, out loud.",
      "Tell your partner one thing about them you find funny, one you find hot, one you find home.",
      "Recreate your partner's most-used facial expression.",
      "Give your partner a genuine toast, like at a wedding.",
      "Let your partner pick the next question theme for both of you.",
      "Do your partner's laugh, as accurately as you can.",
      "Hold hands and describe your partner's hands out loud, kindly.",
      "Tell your partner what you'd miss most about them for one week apart.",
    ],
    friends: [
      'Do your best impression of someone else in this room.',
      'Show the last photo in your camera roll and explain it.',
      'Say three genuine things about the player on your right. No repeats.',
      'Read your last sent message out loud, in a dramatic voice.',
      'Do 10 push-ups, or tell an embarrassing story. Choose now.',
      'Let someone here pick the next song. No complaints.',
      'Try to make the group laugh in 15 seconds without saying a word.',
      'Let the player on your left give you a new nickname for the rest of the game.',
      "Recreate the moment you two first met, exaggerated.",
      "Guess the last thing someone here searched on their phone.",
      "Give the player across from you a new nickname based on tonight.",
      "Do an impression of how someone here reacts when they lose.",
      "Tell the group the real reason you were late last time you all met.",
      "Let the group pick your profile picture for a week.",
      "Do your best impression of the group's most dramatic member.",
      "Guess someone's exact reaction if you told them a secret right now.",
      "Draw a doodle of the person across from you in 15 seconds.",
      "Whisper the nicest thing you can think of about the person to your left.",
      "Act out how someone here orders at a restaurant.",
      "Give a genuine toast to this group, like at a reunion.",
      "Try to guess what someone here is thinking right now, out loud.",
      "Tell the group one thing about you they'd never guess.",
      "Recreate someone's most-used phrase or catchphrase.",
      "Let the group pick your nickname for the rest of the night.",
      "Do the loudest laugh of someone in this room.",
      "Hold up your hand and let someone here read your palm, badly.",
      "Tell the group what you'd miss most about them for a month apart.",
      "Pick someone here and say the first word that comes to mind about them.",
      "Do your worst impression of yourself.",
      "Let someone here answer your next question for you.",
      "Show the group your camera roll for the last 24 hours.",
      "Give a one-sentence toast to the person on your right.",
      "Act out the last argument you had with anyone, played for laughs.",
      "Let the group vote on a new nickname for you, no vetoes.",
    ],
  },
  deep: {
    shared: [
      'What does "home" mean to you?',
      "What's a part of yourself you're still working on?",
      'How do you like to be helped when things are stressful?',
      'What does it mean to forgive someone, to you?',
      'How do you want to be treated when you make a mistake?',
      "What's something hard for you right now?",
      'What do you want to remember about this time in your life?',
      'When did you last feel truly understood?',
      "What's something you're carrying that nobody knows about?",
      "What does peace feel like to you, physically?",
      "What's a belief about yourself you're trying to unlearn?",
      "When do you feel most like yourself?",
      "What's something you needed to hear as a kid that you never got?",
      "What's a fear you've never said out loud?",
      "What does it mean to really trust someone?",
      "What's something you're grieving, even quietly?",
      "What do you wish people understood about how your mind works?",
      "What's a moment that changed how you see yourself?",
    ],
    couples: [
      "What's something hard for you right now that I could help with?",
      'Do you have any fear about our relationship?',
      'What do you need more of from me lately?',
      "How have you grown since we've been together?",
      'Is there anything unsaid between us you want to talk about?',
      "What's something you've learned about love from us?",
      "What's something you're afraid to ask me for?",
      'What from your past still affects how you love?',
      'What should I remember if we ever have a bad fight?',
      "What part of yourself have you only shown to your partner?",
      "What's something you're scared to lose about this relationship?",
      "How has your partner helped you understand yourself better?",
      "What's a wound from before us that still shows up sometimes?",
      "What do you need from me on your hardest days?",
      "What's something you've forgiven me for that we never talked about?",
      "What does safety feel like with you, specifically?",
      "What's a truth about yourself you're still scared to say to me?",
      "How do you want me to show up when you're grieving something?",
      "What's something about love that scares you, even now?",
      "What part of you do you think I still don't fully understand?",
      "What's a moment with me that changed how you see yourself?",
      "What do you need to hear from me that I haven't said enough?",
      "What's something you're proud you survived, that I helped you through?",
      "What does it mean to feel truly known by someone?",
      "What's a version of yourself you're afraid I'll eventually see?",
      "What do you wish I understood about how your mind works during conflict?",
      "What's something you needed from a partner that took you a while to ask for?",
      "How do you want to be comforted when words don't help?",
      "What's a fear about the future of us you haven't said out loud?",
      "What does unconditional feel like, practically, day to day?",
      "What's something you're still healing from that shows up in how you love?",
      "What do you want me to never give up on, even when it's hard?",
      "What's the deepest way I've ever made you feel safe?",
      "What's something true about you that only I really know?",
    ],
    friends: [
      'Is there anything unsaid between you and anyone here?',
      'What do you need more of from your friends lately?',
      "What's something you're afraid to ask people for?",
      'How have you changed since this group met you?',
      "What's a friendship you lost that you still think about?",
      'What do you find hardest to say out loud?',
      'When do you feel lonely even with people around?',
      "What should someone do if they've upset you?",
      "What part of yourself have you only shown to close friends?",
      "What's something you're scared to lose about this friendship?",
      "How has this friendship helped you understand yourself better?",
      "What's a wound from before this group that still shows up sometimes?",
      "What do you need from friends on your hardest days?",
      "What's something you've forgiven someone here for, that was never discussed?",
      "What does safety feel like with the people here, specifically?",
      "What's a truth about yourself you're still scared to say to this group?",
      "How do you want people here to show up when you're grieving something?",
      "What's something about friendship that scares you, even now?",
      "What part of you do you think this group still doesn't fully understand?",
      "What's a moment with someone here that changed how you see yourself?",
      "What do you need to hear from this group that hasn't been said enough?",
      "What's something you're proud you survived, that someone here helped you through?",
      "What does it mean to feel truly known by a friend?",
      "What's a version of yourself you're afraid this group will eventually see?",
      "What do you wish this group understood about how your mind works during conflict?",
      "What's something you needed from a friend that took you a while to ask for?",
      "How do you want to be comforted when words don't help?",
      "What's a fear about the future of this friendship you haven't said out loud?",
      "What does unconditional support feel like, practically, day to day?",
      "What's something you're still healing from that shows up in how you show up for friends?",
      "What do you want this group to never give up on, even when it's hard?",
      "What's the deepest way someone here has ever made you feel safe?",
      "What's something true about you that only close friends really know?",
      "What's a hard season someone here helped you through without realizing it?",
    ],
  },
  memories: {
    shared: [
      "What's the most unplanned thing we've ever done together?",
      'What did you think of me the first time you saw me?',
      "What's a small, normal moment with me that you never forgot?",
      "What's a trip we took that you still think about?",
      'What was our best celebration together?',
      "What's something we used to do that we should start doing again?",
      'What story about us do you love telling other people?',
      'What moment with me would you love to live again?',
      "What's the earliest memory you have of me?",
      "What's a memory that still makes you laugh out loud, every time?",
      "What's a smell or sound that instantly brings back a memory of us?",
      "What's the most 'us' photo that exists, and why?",
      "What's a memory you didn't realize was special until later?",
      "What's something we did once that we never talked about since?",
      "What's a memory that would surprise people who only know us now?",
      "What's the last thing you want to remember before you fall asleep tonight?",
      "What's a memory of me you've never actually told me about?",
      "What's a season of our time together you'd want to relive exactly as it was?",
    ],
    couples: [
      "What's your favorite memory from our first few months together?",
      "What's your favorite photo of us?",
      'Tell our first date story from your side.',
      "What's the hardest thing we've been through?",
      "What's the funniest fight we've ever had?",
      'Which gift from me meant the most to you?',
      'When did you first feel like we were really a team?',
      "What's the first thing you told your friends about me?",
      "What's the moment you first felt like this relationship was serious?",
      "What's a memory from an argument that you can now laugh about?",
      "What's the most nervous you've ever been around your partner?",
      "What's a memory of your partner that you've never told anyone else?",
      "What's the best surprise your partner has ever pulled off?",
      "What's a memory that proved your partner really knew you?",
      "What's the silliest thing you two have ever fought about?",
      "What's a memory from a hard time that made you love your partner more?",
      "What's the most spontaneous thing you two have ever done?",
      "What's a memory of your partner's family that stuck with you?",
      "What's the first compliment your partner ever gave you?",
      "What's a memory that still gives you butterflies, even now?",
      "What's the most 'this is it' moment you've had with your partner?",
      "What's a memory of getting ready for a date together?",
      "What's the funniest thing that's gone wrong on a trip together?",
      "What's a memory of comforting each other that you're proud of?",
      "What's the moment you knew your partner's friends approved of you?",
      "What's a memory of meeting your partner's family for the first time?",
      "What's the best 'nothing special' day you've ever had together?",
      "What's a memory that still feels like a movie scene?",
      "What's the moment you realized you'd choose your partner again?",
      "What's a memory of your partner surprising you with how well they know you?",
      "What's the best gift-giving memory between you two?",
      "What's a memory you want to make sure you never forget?",
      "What's the memory that best explains why you love your partner?",
      "What's a memory you two still argue about the details of?",
    ],
    friends: [
      "What's your favourite memory with someone in this room?",
      'Tell the story of how you two met, from your side.',
      "What's the funniest thing that's ever happened to this group?",
      'What was the worst idea we all agreed to?',
      "What's a photo of us you'd never delete?",
      'When did you first feel properly part of this group?',
      'What did you think of me before you actually knew me?',
      "What's a night none of us should have survived?",
      "What's the moment you first felt like this friendship was going to last?",
      "What's a memory from an argument you can now laugh about?",
      "What's the most nervous you've ever been meeting someone here?",
      "What's a memory of someone here you've never told anyone else?",
      "What's the best surprise someone here has ever pulled off?",
      "What's a memory that proved someone here really knew you?",
      "What's the silliest thing this group has ever argued about?",
      "What's a memory from a hard time that made you appreciate this group more?",
      "What's the most spontaneous thing this group has ever done?",
      "What's a memory of someone's family that stuck with you?",
      "What's the first compliment someone here ever gave you?",
      "What's a memory that still makes you smile, even now?",
      "What's the most 'real friendship' moment you've had here?",
      "What's a memory of getting ready for a night out together?",
      "What's the funniest thing that's gone wrong on a trip with this group?",
      "What's a memory of comforting each other that you're proud of?",
      "What's the moment you knew you truly belonged in this group?",
      "What's a memory of meeting someone's family for the first time?",
      "What's the best 'nothing special' day you've had with this group?",
      "What's a memory that still feels like a movie scene?",
      "What's the moment you realized you'd choose this friendship again?",
      "What's a memory of someone surprising you with how well they know you?",
      "What's the best gift-giving memory in this group?",
      "What's a memory you want to make sure this group never forgets?",
      "What's the memory that best explains why this group matters to you?",
      "What's a memory you two still argue about the details of?",
    ],
  },
  home: {
    shared: [
      'What does a perfect weekend at home look like to you?',
      'What chore do you secretly not mind doing?',
      'What tradition from your childhood do you want to keep?',
      "What's one thing about how I was raised that explains who I am?",
      'If we hosted a dinner tomorrow, who would we invite?',
      'What does a calm morning look like for you?',
      'What would you change about your daily routine if you could?',
      'How much time with people, and how much alone, do you actually need?',
      "What's a smell that instantly means 'home' to you?",
      "What's a rule from your childhood home you've kept or broken?",
      "What's the messiest your space has ever gotten, and why?",
      "What's your idea of the perfect home, in one sentence?",
      "What's something in your home that has a story behind it?",
      "What's a habit around the house you didn't know was unusual until someone pointed it out?",
      "What does 'feeling settled' somewhere actually look like for you?",
      "What's a home you visited once that you still think about?",
      "What's the loudest your household ever gets, and over what?",
      "What's a small ritual that makes any place feel more like home?",
    ],
    couples: [
      'How do we split the work no one sees?',
      'What would make our home feel more like ours?',
      'How do you want holidays to feel for us?',
      'How should we handle it when one of us needs space?',
      'What do you wish we did more of at home?',
      'Who in my family are you closest to?',
      'What limit with family do we need to set?',
      'How do you want us to handle guests at our home?',
      "What's a small thing about our place that makes it feel like 'ours'?",
      "What's a chore you'd take off my plate forever if you could?",
      "What's your honest opinion of how we decorate our space?",
      "What's a household argument we've had that seems silly in hindsight?",
      "What's something you want our home to feel like to guests?",
      "How do you feel about the way we spend evenings at home?",
      "What's a habit of mine at home you secretly find endearing?",
      "What's something you'd change about our morning routine together?",
      "What's a family tradition of mine you've adopted as your own?",
      "What's the ideal way for us to spend a rainy day indoors?",
      "What's something about my family that helped you understand me better?",
      "How do you want our home to feel different from the ones we grew up in?",
      "What's a house rule we should actually make official?",
      "What's your favorite sound our home makes?",
      "What's something we should do more of at home, just the two of us?",
      "What's the best 'nothing day' we've spent at home together?",
      "What's a task you'll always secretly resent doing alone?",
      "What's something about hosting together that you love or hate?",
      "What's a memory of moving in together that still makes you laugh?",
      "What's the one home improvement you'd make if money weren't a factor?",
      "What's something small I do at home that makes you feel taken care of?",
      "How involved do you want our families to be in our home life?",
      "What's a boundary with in-laws or family we should set together?",
      "What's your version of a perfect Sunday at home?",
      "What's something about how I keep house that you'd want to gently change?",
      "What's a corner of our home that feels the most 'you'?",
    ],
    friends: [
      "Whose place does this group always end up at, and why?",
      "What's your family like when everyone's in one room?",
      'What do you wish your friends knew about where you grew up?',
      'Are you usually the host or the guest?',
      "What's a family tradition you'd bring into this group?",
      'Who in your family would get on best with people here?',
      "What's the house rule you'd never break?",
      "What's a small thing about someone's place that makes it feel like 'them'?",
      "What's a chore you'd never volunteer for when staying at someone's place?",
      "What's your honest opinion of how someone here decorates?",
      "What's a household argument at a shared place that seems silly in hindsight?",
      "What's something you want a friend's home to feel like when you visit?",
      "How do you feel about crashing at someone's place unannounced?",
      "What's a habit of a roommate or friend you secretly find endearing?",
      "What's something you'd change about how this group hangs out at someone's home?",
      "What's a family tradition of yours you'd want to share with this group?",
      "What's the ideal way for this group to spend a rainy day indoors?",
      "What's something about someone's family that helped you understand them better?",
      "How do you want gatherings here to feel different from the ones you grew up with?",
      "What's a house rule this group should actually make official?",
      "What's your favorite sound from a place that feels like home?",
      "What's something this group should do more of, just hanging out at home?",
      "What's the best 'nothing day' you've spent at someone's place?",
      "What's a task you'll always secretly resent doing when hosting?",
      "What's something about hosting this group that you love or hate?",
      "What's a memory of a sleepover or hangout that still makes you laugh?",
      "What's the one home improvement you'd make if money weren't a factor?",
      "What's something small a friend does at home that makes you feel welcome?",
      "How involved do you want your family to be in your friendships?",
      "What's a boundary with roommates or family this group should respect?",
      "What's your version of a perfect Sunday hanging out?",
      "What's something about how someone here keeps house that surprised you?",
      "What's a corner of someone's home that feels the most 'them'?",
      "Whose home would you least want to leave, if you had to pick one?",
    ],
  },
  growth: {
    shared: [
      "What's something you're proud of yourself for this year?",
      'How have you changed in the last five years?',
      "What's a fear you don't have anymore?",
      'What do you want to be better at a year from now?',
      "What's a belief you've changed your mind about?",
      'Where do you feel stuck right now?',
      'What does success mean to you these days?',
      'What habit would help your life most if you kept doing it?',
      "What's something you want to try but feel too old or late for?",
      'What part of your work gives you energy?',
      'When did you last do something that scared you?',
      'What do you need to say no to more often?',
      'What would you, ten years ago, think of you now?',
      "What's a mistake that taught you more than any success has?",
      "What's something you used to be ashamed of that you're not anymore?",
      "What's a version of yourself you're glad you let go of?",
      "What's the hardest thing you've had to unlearn?",
      "What's a compliment about your growth you'd love to hear right now?",
    ],
    couples: [
      'What has feedback from me actually helped you with?',
      'What feedback do you wish I gave more kindly?',
      'How do you want me to help keep you on track?',
      "What's something about yourself you've changed because of this relationship?",
      "What's a habit your partner helped you build without lecturing you?",
      "What's a version of you your partner has never met, and are they missing out?",
      "What's something you're working on that your partner doesn't fully know about?",
      "How has your partner made you more patient, or less?",
      "What's a compliment about your growth you'd love to hear from your partner?",
      "What's something you're better at handling now than when you two first met?",
      "What's a fear you've overcome partly because of your partner?",
      "What's a way your partner challenges you to be better, even if it stings?",
      "What's something your partner does that quietly makes you a better person?",
      "What's a belief about relationships you've had to unlearn since being with your partner?",
      "What's a goal you set because your partner believed you could hit it?",
      "What's something you used to struggle with that your partner helped you through?",
      "How do you want to grow together in the next year?",
      "What's a version of yourself you're trying to become, that your partner already sees?",
      "What's a hard truth your partner told you that ended up helping you?",
      "What's something you're proud you didn't give up on, with your partner's support?",
      "What's a way you've had to grow up because of this relationship?",
      "What's a skill you've picked up just from being around your partner?",
      "What's something about conflict you've gotten better at, together?",
      "What's a way your partner has stretched your comfort zone, for the better?",
      "What's something you're still working on that you want your partner's patience with?",
      "What's a moment your partner saw potential in you before you saw it yourself?",
      "What's a habit you've dropped that your partner is quietly grateful for?",
      "What's something you want to be better at for your partner's sake, not just your own?",
      "What's a way being loved has made you braver?",
      "What's a personal win you should have celebrated more, that your partner noticed?",
      "What's something you've forgiven yourself for, with your partner's help?",
      "What's a way your partner has taught you to be kinder, even to yourself?",
      "What's a mistake in this relationship you've grown the most from?",
      "What's the biggest way you want to grow together this year?",
    ],
    friends: [
      "What's the most useful thing a friend has told you about yourself?",
      'Who here would tell you the truth when nobody else would?',
      'What do you want your friends to hold you to?',
      "What's something about yourself you've changed because of this friend group?",
      "What's a habit a friend helped you build without lecturing you?",
      "What's a version of you this group has never met, and are they missing out?",
      "What's something you're working on that people here don't fully know about?",
      "How has this group made you more patient, or less?",
      "What's a compliment about your growth you'd love to hear from someone here?",
      "What's something you're better at handling now than when this group first met?",
      "What's a fear you've overcome partly because of someone here?",
      "What's a way this group challenges you to be better, even if it stings?",
      "What's something a friend does that quietly makes you a better person?",
      "What's a belief about friendship you've had to unlearn because of this group?",
      "What's a goal you set because someone here believed you could hit it?",
      "What's something you used to struggle with that this group helped you through?",
      "How do you want to grow alongside this group in the next year?",
      "What's a version of yourself you're trying to become, that this group already sees?",
      "What's a hard truth someone here told you that ended up helping you?",
      "What's something you're proud you didn't give up on, with this group's support?",
      "What's a way you've had to grow up because of this friendship?",
      "What's a skill you've picked up just from being around this group?",
      "What's something about conflict you've gotten better at, with this group?",
      "What's a way someone here has stretched your comfort zone, for the better?",
      "What's something you're still working on that you want this group's patience with?",
      "What's a moment someone here saw potential in you before you saw it yourself?",
      "What's a habit you've dropped that this group is quietly grateful for?",
      "What's something you want to be better at for this group's sake, not just your own?",
      "What's a way being surrounded by these people has made you braver?",
      "What's a personal win you should have celebrated more, that someone here noticed?",
      "What's something you've forgiven yourself for, with this group's help?",
      "What's a way this group has taught you to be kinder, even to yourself?",
      "What's a mistake in this friendship you've grown the most from?",
      "What's the biggest way you want to grow alongside this group this year?",
    ],
  },
  gratitude: {
    shared: [
      'What are you thankful for about today?',
      'Who outside this room are you grateful for?',
      "What's a hard thing that happened that you're now glad it did?",
      "What's something about your body you're thankful for?",
      'Name three good things that happened this week.',
      "Who taught you something you're still thankful for?",
      'What about right now is worth being thankful for?',
      "What's a part of my personality you're glad I have?",
      "What's something you're grateful you learned from me?",
      "What's something ordinary you'd miss the most if it disappeared?",
      "Who is someone you've never properly thanked?",
      "What's a comfort in your life you take for granted?",
      "What's something about today, specifically, that you're grateful for?",
      "What's a hard season that ended up giving you something good?",
      "What's a skill or gift you have that you're quietly thankful for?",
      "What's something small someone did for you recently that you appreciated?",
      "What's a place you're grateful exists in your life?",
      "What's something about your own resilience you're thankful for?",
    ],
    couples: [
      "What's one thing you're thankful for about us right now?",
      "What's something I do that you've never really thanked me for?",
      'What small comfort in our life do you never want to lose?',
      'What did I do this week that made your life easier?',
      'What are you thankful your partner puts up with about you?',
      'What in our home are you most glad we own?',
      "What's good about the way we argue?",
      "What's something about your partner's patience you're thankful for?",
      "What's a hard season together that you're now grateful you went through?",
      "What's something your partner does daily that you've never properly thanked them for?",
      "What's a way your partner has made you a better person that you're grateful for?",
      "What's something about your partner's family you're thankful they've given you?",
      "What's a comfort your partner provides that you'd be lost without?",
      "What's something about this relationship that you don't say thank you for enough?",
      "What's a sacrifice your partner made for you that you're deeply grateful for?",
      "What's something your partner taught you that you're thankful you learned?",
      "What's a way your partner shows up that you never want to take for granted?",
      "What's something about your partner's flaws you're weirdly grateful for?",
      "What's a moment your partner's support meant more than they knew?",
      "What's something about your life together you'd want to freeze in gratitude?",
      "What's a quality in your partner you wish you thanked them for more often?",
      "What's something about how your partner argues that you're secretly grateful for?",
      "What's a way your partner has made your family better, or vice versa?",
      "What's a financial sacrifice your partner made that you're thankful for?",
      "What's something about growing older with your partner you're already grateful for?",
      "What's a hard truth your partner told you that you're now thankful for?",
      "What's something about your home life you're most thankful your partner provides?",
      "What's a small daily habit of your partner's you're grateful for?",
      "What's something your partner forgave you for that you're still grateful about?",
      "What's a way your partner has shown up for your family that you appreciated?",
      "What's something about your partner's humor you're thankful for on hard days?",
      "What's a moment you felt lucky, specifically, to have this partner?",
      "What's something about your partner's ambition you're grateful rubs off on you?",
      "What's the thing about your partner you'd want to say thank you for, right now?",
    ],
    friends: [
      "What did someone here do for you that you never properly thanked them for?",
      'What are you thankful your friends put up with about you?',
      "What's a small thing about this group you'd miss most?",
      'Who here made a hard time easier without knowing it?',
      "What's something you're grateful you learned from someone in this room?",
      "What's good about the way this group disagrees?",
      "What's something about a friend's patience you're thankful for?",
      "What's a hard season with this group that you're now grateful you went through?",
      "What's something a friend does regularly that you've never properly thanked them for?",
      "What's a way this group has made you a better person that you're grateful for?",
      "What's something about someone's family you're thankful they've shared with you?",
      "What's a comfort a friend provides that you'd be lost without?",
      "What's something about this friendship that you don't say thank you for enough?",
      "What's a sacrifice a friend made for you that you're deeply grateful for?",
      "What's something a friend taught you that you're thankful you learned?",
      "What's a way someone here shows up that you never want to take for granted?",
      "What's something about a friend's flaws you're weirdly grateful for?",
      "What's a moment someone's support meant more than they knew?",
      "What's something about this friend group you'd want to freeze in gratitude?",
      "What's a quality in someone here you wish you thanked them for more often?",
      "What's something about how someone here argues that you're secretly grateful for?",
      "What's a way this group has made your family situation better, or vice versa?",
      "What's a sacrifice a friend made that you're thankful for, financial or otherwise?",
      "What's something about growing older with this group you're already grateful for?",
      "What's a hard truth someone here told you that you're now thankful for?",
      "What's something about your social life you're most thankful this group provides?",
      "What's a small habit of someone here you're grateful for?",
      "What's something a friend forgave you for that you're still grateful about?",
      "What's a way this group has shown up for your family that you appreciated?",
      "What's something about this group's humor you're thankful for on hard days?",
      "What's a moment you felt lucky, specifically, to have these friends?",
      "What's something about someone's ambition you're grateful rubs off on you?",
      "What's the thing about someone here you'd want to say thank you for, right now?",
      "What's a memory with this group you're quietly thankful you got to have?",
    ],
  },
  adventure: {
    shared: [
      "What's the biggest thing you'd try if you knew you couldn't fail?",
      'Mountains, ocean, or city — where do you feel most alive?',
      "What's a place none of us has been that we should go?",
      'Would you rather plan every detail, or just go with no plan?',
      'If we had two free weeks starting tomorrow, what would we do?',
      'What outdoor thing should we try together this year?',
      "What's a food you want to eat in the country it's from?",
      'Road trip or flight — and who drives?',
      "What's a place near us we've never checked out?",
      'Would you rather move every year, or settle in one place?',
      "What's something adventurous you did that you'd never do again?",
      'If we could take one year off together, what would we do with it?',
      'What sound, smell, or place instantly makes you feel free?',
      "What's a small adventure we could have this weekend?",
      "What's an adventure that turned out completely different from what you expected?",
      "What's the most spontaneous decision you've ever made while traveling?",
      "What's a physical challenge you'd love to attempt together?",
      "If you could teleport anywhere for just one hour, where would you go?",
    ],
    couples: [
      "What's the best trip you took before we met?",
      'What would our ideal anniversary trip look like?',
      "What's the wildest place you'd want to go on a trip together?",
      "Would you rather a slow scenic trip or a fast-paced action trip with your partner?",
      "What's a travel disaster you two survived that you now laugh about?",
      "What's an adventure your partner talked you into that you're now glad you did?",
      "What's the most romantic view you two have ever shared?",
      "What's a trip that changed how you two saw each other?",
      "What's an activity you'd never try solo, but would with your partner?",
      "What's the scariest thing you'd do together if you both said yes right now?",
      "What's a country you'd want to live in together for a year?",
      "What's the best local, unplanned discovery you two made on a trip?",
      "What's an adventure you want to have before you're too old to enjoy it?",
      "Would you rather camp under the stars or stay somewhere luxurious, together?",
      "What's something adventurous your partner would surprise people by agreeing to?",
      "What's a trip you took together that you'd redo exactly the same way?",
      "What's an adventure that would test you two as a couple, in a good way?",
      "What's the most 'us' way to spend a spontaneous day off together?",
      "What's a bucket list item you want your partner specifically there for?",
      "What's the most nervous you've been trying something new together?",
      "What's an adventure that would be worth the cost, no matter what?",
      "What's a skill you'd want to learn together purely for the adventure of it?",
      "What's the farthest you two have ever traveled together?",
      "What's an adventure that would make a great story for your grandkids?",
      "What's a road you two have always wanted to just drive, no destination?",
      "What's the most 'out of character' thing your partner has done on an adventure?",
      "What's an adventure you'd want to have again exactly as it happened?",
      "What's a fear you'd want to face together, once, just to say you did?",
      "What's the best souvenir from a trip together, and why?",
      "What's an adventure your partner has always wanted, that you haven't asked about?",
      "What's the wildest 'yes' you two have said to each other on a trip?",
      "What's an adventure you two keep almost planning but never book?",
      "What's the most beautiful place you've seen with your partner?",
      "What's an adventure that taught you something new about your partner?",
    ],
    friends: [
      "What's the best trip you've taken without anyone here?",
      'Who in this room is the best person to travel with? Be honest.',
      "What's the wildest place this group should go on a trip together?",
      "Would you rather a slow scenic trip or a fast-paced action trip with this group?",
      "What's a travel disaster this group survived that you now laugh about?",
      "What's an adventure someone here talked you into that you're now glad you did?",
      "What's the most memorable view this group has ever shared?",
      "What's a trip that changed how you saw someone here?",
      "What's an activity you'd never try solo, but would with this group?",
      "What's the scariest thing this group would do together if everyone said yes right now?",
      "What's a country this group should live in together for a summer?",
      "What's the best local, unplanned discovery this group made on a trip?",
      "What's an adventure you want to have with this group before you're too old to enjoy it?",
      "Would you rather camp under the stars or stay somewhere luxurious, with this group?",
      "What's something adventurous someone here would surprise people by agreeing to?",
      "What's a trip this group took that you'd redo exactly the same way?",
      "What's an adventure that would test this group's friendship, in a good way?",
      "What's the most 'this group' way to spend a spontaneous day off?",
      "What's a bucket list item you want someone here specifically there for?",
      "What's the most nervous you've been trying something new with this group?",
      "What's an adventure that would be worth the cost, no matter what?",
      "What's a skill this group should learn together purely for the adventure of it?",
      "What's the farthest this group has ever traveled together?",
      "What's an adventure that would make a great story for your grandkids?",
      "What's a road this group has always wanted to just drive, no destination?",
      "What's the most 'out of character' thing someone here has done on an adventure?",
      "What's an adventure you'd want to have again exactly as it happened?",
      "What's a fear you'd want to face with this group, once, just to say you did?",
      "What's the best souvenir from a trip with this group, and why?",
      "What's an adventure someone here has always wanted, that nobody's asked about?",
      "What's the wildest 'yes' this group has said on a trip?",
      "What's an adventure this group keeps almost planning but never books?",
      "What's the most beautiful place you've seen with people from this group?",
      "What's an adventure that taught you something new about someone here?",
    ],
  },
  everyday: {
    shared: [
      "What's the best part of a normal day for you?",
      'How do you take your coffee or tea?',
      "What's your favorite way to waste an hour?",
      "What's on your mind most often lately?",
      "What's a chore you'd happily pay someone else to do forever?",
      'What do you look forward to most on a normal weekday?',
      "What's your comfort food when things go wrong?",
      'How do you actually like to be woken up?',
      "What's the last thing that made you laugh out loud?",
      'What is your phone taking time away from?',
      "What's your favorite thing we do that costs nothing?",
      'How are you really doing? Not the quick answer.',
      "What's something small I do that annoys you? Be honest, be kind.",
      "What's a small daily ritual you'd never give up?",
      "What's the most boring task that somehow satisfies you?",
      "What's something ordinary that instantly improves your mood?",
      "What's your honest energy level right now, out of 10?",
      "What's a tiny inconvenience in your day that quietly annoys you every time?",
    ],
    couples: [
      'How do you like to be greeted when I get home?',
      'Are you an early bird or a night owl?',
      'What does a good normal night together look like?',
      "What's a small daily habit of your partner's that you secretly love?",
      "What's the most 'married couple' thing you two do, even without being married?",
      "What's a texting habit of your partner's that says a lot about them?",
      "What's the most mundane task you actually enjoy doing with your partner?",
      "What's something about your partner's morning routine that surprised you?",
      "What's a food combo your partner eats that you'll never understand?",
      "What's the last completely normal moment with your partner that you appreciated?",
      "What's a household task you two have silently agreed never to talk about?",
      "What's your partner's most-used phrase, and does it drive you crazy or make you smile?",
      "What's a small thing about your partner's daily routine you've started copying?",
      "What's the most efficient way your partner solves a problem, that you admire?",
      "What's something you two do on repeat that never gets old?",
      "What's a habit of your partner's that took getting used to?",
      "What's the most 'us' errand you two run together?",
      "What's something about your partner's daily energy that rubs off on you?",
      "What's a small comfort you two share every single day?",
      "What's the weirdest thing that's become normal since being with your partner?",
      "What's your partner's go-to answer when you ask 'what do you want for dinner'?",
      "What's a tiny disagreement you two have on a loop, without it ever being serious?",
      "What's something about your partner's phone habits that says a lot about them?",
      "What's the most predictable thing your partner does every single day?",
      "What's a Sunday-morning habit you two share?",
      "What's something small your partner does that you'd notice immediately if it stopped?",
      "What's the most low-key way you two show affection during a normal day?",
      "What's a daily errand that's secretly your favorite part of the day?",
      "What's something about your partner's routine you find weirdly charming?",
      "What's the last thing your partner said that you're still thinking about?",
      "What's a normal Tuesday activity you'd choose over something 'exciting'?",
      "What's something about your daily rhythm that only works because of your partner?",
      "What's a small joke you two make almost every day without noticing?",
      "What's the most ordinary thing your partner does that you'd genuinely miss?",
    ],
    friends: [
      "What's the group chat actually for?",
      "Who here takes longest to reply, and what's the excuse?",
      'What does a good normal night with friends look like to you?',
      "What's a small daily habit of someone here that you secretly love?",
      "What's the most 'old married couple' thing this group does, platonically?",
      "What's a texting habit of someone here that says a lot about them?",
      "What's the most mundane task you actually enjoy doing with this group?",
      "What's something about someone's morning routine that surprised you?",
      "What's a food combo someone here eats that you'll never understand?",
      "What's the last completely normal moment with this group that you appreciated?",
      "What's a shared habit this group has silently agreed never to talk about?",
      "What's someone's most-used phrase, and does it drive you crazy or make you smile?",
      "What's a small thing about someone's daily routine you've started copying?",
      "What's the most efficient way someone here solves a problem, that you admire?",
      "What's something you all do on repeat that never gets old?",
      "What's a habit of someone here that took getting used to?",
      "What's the most 'this group' errand you all run together?",
      "What's something about someone's daily energy that rubs off on you?",
      "What's a small comfort this group shares regularly?",
      "What's the weirdest thing that's become normal since knowing this group?",
      "What's someone's go-to answer when the group asks 'what do you want to eat'?",
      "What's a tiny disagreement this group has on a loop, without it ever being serious?",
      "What's something about someone's phone habits that says a lot about them?",
      "What's the most predictable thing someone here does every single day?",
      "What's a weekend-morning habit this group shares?",
      "What's something small someone here does that you'd notice immediately if it stopped?",
      "What's the most low-key way this group shows they care during a normal day?",
      "What's a daily errand that's secretly your favorite part of the day?",
      "What's something about someone's routine you find weirdly charming?",
      "What's the last thing someone here said that you're still thinking about?",
      "What's a normal weekday activity you'd choose over something 'exciting'?",
      "What's something about your daily rhythm that only works because of this group?",
      "What's a small joke this group makes almost every day without noticing?",
      "What's the most ordinary thing someone here does that you'd genuinely miss?",
    ],
  },
};

// type: 'moveSelf' | 'swapPositions' | 'joinPartner' | 'skipTurn' | 'extraTurn'
//     | 'lovePoints' | 'bothPoints' | 'action' | 'giftPoints'
//
// `friends` is the wording used in Friends mode — most of these are mechanical
// and only need "your partner" swapped for "another player". `only` restricts
// a card to one mode, which is how the romantic dares stay out of a game
// between friends.
const SURPRISES = [
  {
    icon: '🔀',
    text: 'Swap places with your partner!',
    friends: 'Swap places with another player!',
    type: 'swapPositions',
  },
  { icon: '⬆️', text: 'Lucky leap — forward 4 spaces.', type: 'moveSelf', value: 4 },
  { icon: '⬇️', text: 'Stumble — back 3 spaces.', type: 'moveSelf', value: -3 },
  { icon: '🔁', text: 'Roll again!', type: 'extraTurn' },
  { icon: '⏸️', text: 'Skip your next turn.', type: 'skipTurn', target: 'self' },
  {
    icon: '🚫',
    text: 'Your partner skips their next turn!',
    friends: 'Another player skips their next turn!',
    type: 'skipTurn',
    target: 'opponent',
  },
  {
    icon: '💞',
    text: '+5 Love Points.',
    friends: '+5 points.',
    type: 'lovePoints',
    value: 5,
    target: 'self',
  },
  {
    icon: '💔',
    text: '-3 Love Points.',
    friends: '-3 points.',
    type: 'lovePoints',
    value: -3,
    target: 'self',
  },
  {
    icon: '🤗',
    text: 'Hug your partner right now.',
    friends: 'Hug the player on your left.',
    type: 'action',
    bonus: 2,
  },
  { icon: '😘', text: 'Kiss your partner on the cheek.', type: 'action', bonus: 2, only: 'couples' },
  { icon: '📸', text: 'Take a photo together.', type: 'action', bonus: 2 },
  {
    icon: '🎁',
    text: 'Give 3 Love Points to your partner.',
    friends: 'Give 3 points to another player.',
    type: 'giftPoints',
    value: 3,
  },
  { icon: '🍀', text: 'Lucky streak — forward 6 spaces.', type: 'moveSelf', value: 6 },
  { icon: '🎯', text: 'Forward 2 spaces.', type: 'moveSelf', value: 2 },
  { icon: '🌪️', text: 'Blown back 5 spaces.', type: 'moveSelf', value: -5 },
  {
    icon: '🧲',
    text: "Magnet — move to your partner's square.",
    friends: "Magnet — move to another player's square.",
    type: 'joinPartner',
  },
  {
    // "You BOTH" was wrong from three players up — this card has always paid
    // everyone at the table.
    icon: '🤝',
    text: 'Everyone gains 3 Love Points.',
    friends: 'Everyone gains 3 points.',
    type: 'bothPoints',
    value: 3,
  },
  {
    icon: '💌',
    text: 'Your partner gains 4 Love Points — tell them why.',
    friends: 'Another player gains 4 points — tell them why.',
    type: 'lovePoints',
    value: 4,
    target: 'opponent',
  },
  {
    icon: '💐',
    text: 'Say three things you appreciate about your partner.',
    friends: 'Say three things you appreciate about the player on your right.',
    type: 'action',
    bonus: 3,
  },
  {
    icon: '🎵',
    text: 'Play a song that reminds you of your partner.',
    friends: 'Play a song that reminds you of someone here.',
    type: 'action',
    bonus: 3,
  },
  {
    icon: '☕',
    text: 'Promise a coffee date this week — pick the day now.',
    friends: 'Promise this group a night out — pick the date now.',
    type: 'action',
    bonus: 2,
  },
  {
    icon: '🎭',
    text: "Act out your partner's most-used phrase.",
    friends: "Act out another player's most-used phrase.",
    type: 'action',
    bonus: 2,
  },
  { icon: '🕯️', text: 'Hold hands in silence for 20 seconds.', type: 'action', bonus: 3, only: 'couples' },
  {
    icon: '🙈',
    text: "Close your eyes and describe your partner's face.",
    type: 'action',
    bonus: 2,
    only: 'couples',
  },
  {
    icon: '⭐',
    text: 'Name one thing your partner did well today.',
    friends: 'Name one thing another player did well today.',
    type: 'action',
    bonus: 2,
  },
  {
    icon: '🎤',
    text: 'Let the group ask you one question. You have to answer it.',
    type: 'action',
    bonus: 3,
    only: 'friends',
  },
  {
    icon: '👀',
    text: 'Tell the player on your left your honest first impression of them.',
    type: 'action',
    bonus: 3,
    only: 'friends',
  },
  { icon: '🌈', text: 'Forward 3 spaces.', type: 'moveSelf', value: 3 },
  { icon: '🐢', text: 'Slow and steady — back 2 spaces.', type: 'moveSelf', value: -2 },
  { icon: '🔥', text: 'On a streak — forward 5 spaces.', type: 'moveSelf', value: 5 },
  { icon: '🧊', text: 'Cold feet — back 4 spaces.', type: 'moveSelf', value: -4 },
  {
    icon: '🎈',
    text: '+2 Love Points.',
    friends: '+2 points.',
    type: 'lovePoints',
    value: 2,
    target: 'self',
  },
  {
    icon: '🥶',
    text: '-2 Love Points.',
    friends: '-2 points.',
    type: 'lovePoints',
    value: -2,
    target: 'self',
  },
  {
    icon: '🎊',
    text: 'Everyone gains 2 Love Points.',
    friends: 'Everyone gains 2 points.',
    type: 'bothPoints',
    value: 2,
  },
  {
    icon: '🫶',
    text: 'Give 5 Love Points to your partner.',
    friends: 'Give 5 points to another player.',
    type: 'giftPoints',
    value: 5,
  },
  {
    icon: '🔗',
    text: "Chain reaction — move to your partner's square.",
    friends: "Chain reaction — move to another player's square.",
    type: 'joinPartner',
  },
  { icon: '🕺', text: 'Dance for 10 seconds, no music required.', type: 'action', bonus: 2 },
  { icon: '🤳', text: 'Take a selfie together and describe it out loud.', type: 'action', bonus: 2 },
  {
    icon: '🎶',
    text: 'Hum a song and have your partner guess it.',
    friends: 'Hum a song and have the group guess it.',
    type: 'action',
    bonus: 2,
  },
  {
    icon: '🙋',
    text: 'Ask your partner anything — they must answer honestly.',
    friends: 'Ask anyone at the table anything — they must answer honestly.',
    type: 'action',
    bonus: 3,
  },
  {
    icon: '💭',
    text: 'Say what you think your partner is thinking right now.',
    type: 'action',
    bonus: 2,
    only: 'couples',
  },
  {
    icon: '🦜',
    text: 'Do your best impression of your partner.',
    friends: 'Do your best impression of someone at the table.',
    type: 'action',
    bonus: 2,
  },
];
