// Indonesian question bank. Same shape as QUESTIONS in data.js, and every
// list is a line-for-line translation of the English one: same length, same
// order. That's what lets the language change mid-game — the used-question
// indexes a game keeps (state.usedQuestions) point at the same question in
// either language. If you add a question to one bank, add its twin here at
// the same position.
//
// Written in everyday spoken Indonesian ("kamu", "nggak", "bareng"), not the
// formal register — it should sound like friends chatting, not a survey.
// Like data.js, no module system: QUESTIONS_ID is a global script.js reads.
const QUESTIONS_ID = {
  general: {
    shared: [
      "Oke, satu skill apa yang harus banget kita pelajari bareng?",
      "Bulan ini kita maraton nonton apa, nih?",
      "Kalau kita tukeran hidup sehari, hal pertama yang kamu lakuin apa?",
      "Dari semua inside joke kita, mana yang paling kamu suka?",
      "Apa yang bikin kamu kaget soal aku waktu pertama kenal?",
      "Lagu apa yang 'kita banget' menurutmu?",
      "Makanan terenak yang pernah kita makan bareng — sebutin.",
      "Kebiasaanku yang mana yang tanpa sadar udah kamu tiru?",
      "Satu hal kecil apa yang bisa aku lakuin minggu ini biar harimu senang?",
      "Kiamat zombie: siapa yang bertahan paling lama, dan kenapa?",
      "Hal kecil apa yang langsung bikin mood kamu bagus?",
      "Kalau bisa ngulang satu hari biasa aja, kamu pilih yang mana?",
      "Satu aturan hidup apa yang menurutmu semua orang harus pegang?",
      "Hal terakhir yang kamu pelajari dan bikin kamu 'wah' itu apa?",
      "Kalau hari ini dapat bonus satu jam, mau kamu pakai buat apa?",
      "Orang-orang paling sering salah paham soal kamu di bagian mana?",
      "Pertanyaan apa yang kamu pengin lebih sering ditanyain orang?",
      "Saran terbaik yang malah kamu cuekin itu apa?",
    ],
    couples: [
      "Hal kecil apa dari pasanganmu yang selalu bikin kamu senyum?",
      "Kalau sekarang bisa kencan ke mana aja, kita ke mana?",
      "Apa yang menurutmu lucu banget tapi pasanganmu nggak nangkep?",
      "Kalau besok kita pelihara hewan, mau kita kasih nama apa?",
      "Kalau hidup kita jadi film, genrenya apa?",
      "Sudut favoritmu di tempat tinggal kita di mana?",
      "Kebiasaan pasanganmu yang mana yang ternyata bikin kamu makin sayang?",
      "Apa yang sering kalian debatin tapi sebenarnya lucu?",
      "Aturan apa yang kalian punya yang orang lain nggak bakal ngerti?",
      "Kalau hubungan kita hari ini itu ramalan cuaca, bunyinya gimana?",
      "Apa yang sekarang kamu lakuin beda sejak sama pasanganmu?",
      "Kerjaan rumah mana yang diam-diam udah kamu klaim jadi 'punyamu'?",
      "Apa yang pasanganmu lakuin belakangan ini yang masih kepikiran terus?",
      "Kalau pasanganmu jadi narator hidupmu, kalimat pembukanya apa?",
      "Makanan apa yang cuma pasanganmu yang bisa bujuk kamu buat nyoba?",
      "Tradisi kecil apa yang cuma kalian berdua yang punya?",
      "Menurut pasanganmu, kebiasaanmu yang paling nyebelin apa? Jujur, ya.",
      "Apa yang dulu kalian beda pendapat, tapi sekarang malah sepakat banget?",
      "Hal paling aneh yang bikin kalian makin dekat itu apa?",
      "Kalau bisa membekukan satu momen biasa bareng pasanganmu, yang mana?",
      "Pujian apa buat pasanganmu yang selalu kamu maksud dari hati?",
      "Karakter TV mana yang paling mirip pasanganmu?",
      "Pasanganmu jago banget di hal apa, tapi dia nggak sadar?",
      "Hal paling 'kalian banget' yang pernah kalian lakuin apa?",
      "Kalau hubungan kita punya lagu tema, lagunya apa?",
      "Hal nyebelin kecil apa yang rela kamu hadapi selamanya demi pasanganmu?",
      "Apa yang belum pernah kamu bilang ke pasanganmu, padahal harusnya iya?",
      "Panggilan sayang apa yang diam-diam kamu pakai buat pasanganmu di kepala?",
      "Bagian terbaik dari males-malesan bareng itu apa?",
      "Rencana apa yang terus kalian omongin tapi nggak pernah jadi?",
      "Apa yang pasanganmu ajarin ke kamu tanpa dia sadar?",
      "Minggu santai bareng yang paling kamu suka itu kayak gimana?",
      "Lelucon apa di antara kalian yang orang lain nggak pernah ngerti?",
      "Satu hal apa yang pengin kamu sampaikan ke pasanganmu sebelum game ini selesai?",
    ],
    friends: [
      "Bakat paling nggak bergunamu apa? Tunjukin, dong.",
      "Kalau darurat, siapa di sini yang pertama kamu telepon, dan kenapa?",
      "Tontonan apa yang bakal kamu paksa semua orang di sini nonton?",
      "Kalau besok kita bikin band, siapa main apa?",
      "Gosip soal kamu yang ternyata beneran itu apa?",
      "Siapa di sini yang paling berubah sejak kamu kenal dia?",
      "Aturan apa di geng ini yang pasti dianggap aneh sama orang luar?",
      "Siapa di sini yang paling parah kasih arah jalan — dan kok kita masih ngikut?",
      "Rencana paling kacau apa yang beneran berhasil dijalanin geng ini?",
      "Kalau geng ini bikin nama grup chat, namanya apa?",
      "Makanan apa yang selalu bikin kita semua ribut?",
      "Siapa yang paling mungkin bales chat grup jam 3 pagi?",
      "Apa yang cuma pernah kamu ketawain bareng orang-orang di ruangan ini?",
      "Kalau kita semua ikut acara kuis bareng, acara apa?",
      "Jujur aja, siapa di sini yang selera musiknya paling parah?",
      "Tradisi apa yang harusnya beneran dimulai sama geng ini?",
      "Siapa yang diam-diam ditiru semua orang tapi nggak ada yang ngaku?",
      "Hal paling 'kita banget' yang pernah geng ini lakuin apa?",
      "Kalau ada film tentang geng ini, genrenya apa?",
      "Kebiasaan kecil siapa di sini yang selalu bikin kamu ngakak?",
      "Siapa di sini yang paling kuat tanpa HP?",
      "Siapa di sini yang butuh nama panggilan, dan apa namanya?",
      "Motto nggak resmi geng ini apa?",
      "Siapa yang selalu telat, dan alasan andalannya apa?",
      "Bagian terbaik dari gabut bareng geng ini apa?",
      "Rencana apa yang terus kita omongin tapi nggak pernah jadi?",
      "Siapa di sini yang ngajarin kamu sesuatu tanpa dia sadar?",
      "Cara favoritmu ngabisin hari santai bareng geng ini gimana?",
      "Lelucon apa di sini yang orang luar nggak pernah ngerti?",
      "Satu hal apa yang pengin kamu sampaikan ke geng ini sebelum malam ini selesai?",
      "Siapa yang jadi tukang atur rencana di sini, mau nggak mau?",
      "Masalah terbesar apa yang pernah geng ini hadapi bareng?",
      "Kalau geng ini punya maskot, apa maskotnya?",
      "Siapa yang jadi penengah kalau geng ini mulai ribut?",
    ],
  },
  love: {
    shared: [
      "Kalau lagi sedih, apa yang beneran bikin kamu lebih baik?",
      "Apa yang belum pernah kamu ucapin, tapi pengin aku tahu?",
      "Kasih pujian beneran ke salah satu orang di sini. Sekarang.",
      "Biasanya kita baikan setelah berantem itu gimana?",
      "Satu hal apa yang kamu nggak mau kita berhenti lakuin bareng?",
      "Apa yang bikin kamu merasa disayang, yang orang lain nggak bakal nyangka?",
      "Cinta itu kayak gimana di hari Selasa yang biasa-biasa aja?",
      "Siapa yang nunjukin ke kamu cinta itu harusnya terasa kayak apa?",
      "Perhatian kecil apa yang nggak pernah bikin kamu bosan?",
      "Hal aneh apa yang kamu hubungkan sama kata 'cinta'?",
      "Gimana kamu tahu seseorang beneran peduli, bukan cuma basa-basi?",
      "Bahasa cinta apa yang baru-baru ini kamu sadari kamu punya?",
      "Dicintai sama dimengerti itu beda nggak, sih? Bedanya di mana?",
      "Kapan terakhir kamu merasa disayang banget, tanpa perlu penjelasan?",
      "Apa yang bikin kamu merasa nggak layak disayang, walau cuma sebentar?",
      "Cara kamu nunjukin sayang yang sering nggak disadari orang itu apa?",
      "Hal paling berani yang pernah kamu lakuin demi cinta apa?",
      "Buatmu, sayang sama seseorang di hari terburuknya itu kayak gimana?",
    ],
    couples: [
      "Apa yang awalnya bikin kamu jatuh hati sama pasanganmu?",
      "Gambarkan pasanganmu dalam tiga kata — ucapin langsung.",
      "Hal kecil apa yang bikin kamu merasa paling disayang?",
      "Apa yang paling kamu suka dari cara pasanganmu memperlakukan kamu?",
      "Kapan kamu merasa paling dekat sama pasanganmu?",
      "Satu janji apa yang pengin kalian buat satu sama lain malam ini?",
      "Kapan kamu sadar kamu sayang sama aku?",
      "Apa hal terbaik dari kita sebagai pasangan?",
      "Sayang sama aku bikin kamu berubah gimana?",
      "Kalau cinta kita itu warna, warnanya apa dan kenapa?",
      "Rasanya disayang sama aku itu kayak gimana?",
      "Kapan kamu sadar hubungan ini beda dari yang lain?",
      "Menurutmu, pasanganmu perlu lebih sering dengar kalimat apa?",
      "Hal paling romantis yang pernah pasanganmu lakuin, sekecil apa pun, itu apa?",
      "Gimana cara pasanganmu bikin hari-hari berat jadi lebih ringan?",
      "Apa yang bikin kamu kaget dari rasanya sayang sama pasanganmu?",
      "Apa yang kamu nggak mau pasanganmu ragukan soal rasa sayangmu?",
      "Ketakutan soal cinta apa yang udah pasanganmu bantu kamu lewati?",
      "Gimana pandanganmu soal cinta berubah sejak sama pasanganmu?",
      "Sisi lembut pasanganmu yang mana yang cuma kamu yang lihat?",
      "Apa yang pasanganmu lakuin yang bikin kamu merasa dipilih?",
      "Gimana kalian nunjukin sayang tanpa ngomong sepatah kata pun?",
      "Kalau bisa ngulang satu hal dalam cara kamu menyayangi pasanganmu, apa itu?",
      "Bagian mana dari kisah cinta kalian yang masih bikin deg-degan?",
      "Hal paling berani apa yang diminta cinta darimu di hubungan ini?",
      "Kalau lagi ada masalah, kamu pengin disayang dengan cara gimana?",
      "Cara diam-diam pasanganmu sayang sama kamu yang belum pernah kamu bahas itu apa?",
      "'Selamanya' itu artinya apa buatmu di hubungan ini?",
      "Apa yang kamu suka dari rasanya menyayangi pasanganmu — bukan cuma dari dia?",
      "Kapan pasanganmu sayang sama kamu apa adanya, lengkap sama kekuranganmu?",
      "Sepuluh tahun lagi, kamu pengin cinta kita terasa kayak gimana?",
      "Gimana pasanganmu menyayangi kamu lebih baik dari siapa pun sebelumnya?",
      "Apa yang kamu harap nggak pernah pasanganmu lupa soal seberapa sayangnya kamu?",
      "Menyayangi pasanganmu ngajarin kamu apa soal dirimu sendiri?",
    ],
    friends: [
      "Kapan kamu mutusin aku ini teman beneran, bukan sekadar kenalan?",
      "Gambarkan aku dalam tiga kata — ucapin langsung.",
      "Apa yang kamu butuhin dari teman tapi susah buat minta?",
      "Kapan kamu merasa paling diperhatiin sama seseorang di sini?",
      "Apa yang kamu hargai dari aku yang mungkin aku nggak tahu?",
      "Menurutmu, teman yang baik itu yang kayak gimana?",
      "Siapa di sini yang pengin kamu ada di sampingmu di hari terburukmu?",
      "Hal paling baik yang pernah seseorang di sini lakuin buat kamu apa?",
      "Kapan kamu sadar pertemanan ini beda dari yang lain?",
      "Menurutmu, aku perlu lebih sering dengar kalimat apa?",
      "Kebaikan apa yang pernah seseorang di sini lakuin tanpa diminta?",
      "Gimana geng ini bikin hari-hari berat jadi lebih ringan?",
      "Apa yang bikin kamu kaget dari rasanya peduli sama orang-orang di sini?",
      "Apa yang kamu nggak mau orang-orang di sini ragukan soal kesetiaanmu?",
      "Ketakutan soal pertemanan apa yang udah dibantu dilewati sama seseorang di sini?",
      "Gimana pandanganmu soal teman yang baik berubah dari tahun ke tahun?",
      "Sisi lembutmu yang mana yang cuma teman dekat yang lihat?",
      "Apa yang orang-orang di sini lakuin yang bikin kamu merasa dipilih?",
      "Gimana teman nunjukin peduli tanpa harus ngomong?",
      "Kalau bisa ngulang satu hal dalam caramu hadir buat teman, apa itu?",
      "Kenangan pertemanan apa yang masih bikin hati hangat?",
      "Hal paling berani apa yang pernah diminta pertemanan darimu?",
      "Kalau lagi ada masalah, kamu pengin teman-temanmu hadir dengan cara gimana?",
      "Cara diam-diam seseorang di sini peduli sama kamu yang belum pernah kamu bahas itu apa?",
      "'Susah senang bareng' itu artinya apa di geng ini?",
      "Apa yang kamu suka dari rasanya peduli sama orang — bukan cuma dari orangnya?",
      "Kapan seseorang di sini nerima kamu apa adanya, lengkap sama kekuranganmu?",
      "Sepuluh tahun lagi, kamu pengin pertemanan ini terasa kayak gimana?",
      "Gimana seseorang di sini hadir buat kamu lebih baik dari siapa pun sebelumnya?",
      "Apa yang kamu harap geng ini nggak pernah lupa soal seberapa pedulinya kamu?",
      "Pertemanan ini ngajarin kamu apa soal dirimu sendiri?",
      "Siapa di sini yang kamu percaya buat nyimpen rahasia yang belum pernah kamu ceritain?",
      "Gimana geng ini ngajarin kamu buat lebih sayang sama orang?",
      "Apa yang kamu hargai tapi belum pernah diucapin siapa pun di sini?",
    ],
  },
  money: {
    shared: [
      "Kebiasaan soal uang dari keluargamu yang mana yang mau kamu pertahankan — dan yang mana yang harus dibuang?",
      "Merasa aman soal uang itu kayak gimana buatmu?",
      "Besok kamu dapat uang banyak: ditabung, dipakai, atau dibagi?",
      "Hal seru apa yang rela kamu boros-borosin?",
      "Keputusan soal uang terbaik yang pernah kamu ambil apa?",
      "Obrolan soal uang apa yang terus kamu tunda?",
      "Skill apa yang rela kamu bayar mahal buat dipelajari?",
      "Barang mahal apa yang kamu beli dan nggak nyesel sama sekali?",
      "Buatmu, uang itu lebih soal kebebasan atau rasa aman?",
      "Kebiasaan soal uang apa yang kamu dapat dari lihat orang lain kesusahan?",
      "Sekarang ini, mending punya lebih banyak waktu atau lebih banyak uang?",
      "Barang paling impulsif yang pernah kamu beli apa?",
      "Langganan apa yang terus pengin kamu berhentiin tapi belum juga?",
      "'Kaya' itu artinya apa buatmu — selain angkanya?",
      "Pengeluaran apa yang nggak bakal kamu potong, apa pun yang terjadi?",
      "Pelajaran soal uang apa yang kamu dapat dengan cara pahit?",
      "Kaya tapi diam-diam, atau cukupan tapi santai — pilih mana?",
      "Barang termurah apa yang bikin kamu bahagia banget?",
    ],
    couples: [
      "Satu target keuangan apa yang harus kita pasang tahun ini?",
      "Kalau bulan ini kita dapat tambahan 5 juta, mau kita pakai buat apa?",
      "Kebiasaan pasanganmu soal uang yang mana yang kamu suka?",
      "Jujur, gimana perasaanmu soal rencana tabungan kita?",
      "Hal besar apa yang harus mulai kita tabung?",
      "Kita udah sepakat belum soal bagi-bagi tagihan?",
      "Pengeluaran apa yang bisa kita kurangi buat nabung hal yang lebih besar?",
      "Lima tahun lagi, kondisi keuangan kita kamu bayangin kayak gimana?",
      "Kita udah cukup nabung buat senang-senang, atau terlalu mikirin nanti?",
      "Perlu nggak kita masing-masing punya uang jajan 'bebas tanpa ditanya'?",
      "Apa yang kamu beli yang sampai sekarang pasanganmu nggak paham?",
      "Kalau ada pengeluaran besar mendadak, kita hadapi bareng gimana?",
      "Soal uang, apa yang kamu bangga berhasil kita beresin bareng?",
      "Soal uang, kita udah terasa satu tim atau masih meraba-raba?",
      "Obrolan soal uang apa yang selama ini kita hindari?",
      "Kalau besok semua uang kita digabung, apa yang bakal kamu lakuin beda?",
      "Barang mahal apa yang pengin kamu tabung bareng sebagai pasangan?",
      "Gimana perasaanmu soal kado kejutan yang harganya lumayan?",
      "Reaksi jujur: aku beli barang mahal tanpa nanya kamu dulu?",
      "Kebiasaanku soal uang yang mana yang pengin kamu ubah pelan-pelan?",
      "Target uang bersama apa yang bakal bikin kamu bangga banget sama kita?",
      "Pensiun dini dan hidup sederhana, atau kerja lebih lama dan hidup mewah?",
      "Hal paling dermawan yang pernah kamu lihat aku lakuin pakai uang apa?",
      "Gimana kalau salah satu dari kita penghasilannya jauh lebih besar?",
      "Pengeluaran kita yang mana yang worth it banget?",
      "Kekhawatiran soal uang apa yang mungkin belum aku tahu?",
      "Pencapaian soal uang apa yang harusnya kita rayain lebih heboh?",
      "Gimana kita mau ngajarin diri kita nanti — atau anak — soal uang?",
      "Soal uang, apa yang rela kamu korbanin demi kita, tanpa mikir dua kali?",
      "Barang apa yang harusnya kita beli bareng, bukan sendiri-sendiri?",
      "Utang: harus dihindari banget, atau cuma alat biasa?",
      "Kebiasaan soal uang apa yang lagi kamu coba hentikan demi kita?",
      "Uang yang 'cukup' buat hidup kita bareng itu kayak gimana?",
      "Menurutmu, hal paling romantis yang pernah dilakuin orang pakai uang itu apa?",
    ],
    friends: [
      "Patungan bayar tagihan bareng teman: gampang, atau agak canggung?",
      "Kamu mau minjemin uang ke teman nggak?",
      "Uang paling banyak yang pernah kamu habisin buat hal yang orang lain nggak ngerti?",
      "Teman-temanmu kira-kira tahu nggak penghasilanmu berapa?",
      "Kalau besok tiba-tiba dapat uang, kita liburan ke mana?",
      "Umur 20 kamu buang-buang uang buat apa yang sekarang nggak bakal kamu beli?",
      "Apa yang kamu beli yang sampai sekarang teman-temanmu nggak paham?",
      "Gimana perasaanmu kalau teman tiba-tiba jauh lebih kaya dari kamu?",
      "Soal uang, apa yang kamu bangga bisa beresin sendiri?",
      "Obrolan soal uang apa yang kamu hindari sama teman?",
      "Kamu mau minjemin uang dalam jumlah besar ke seseorang di ruangan ini?",
      "Barang mahal apa yang pengin kamu tabung bareng orang-orang di sini?",
      "Patungan kado buat teman — suka atau nggak?",
      "Reaksi jujur waktu teman beli barang mahal yang kamu nggak bakal beli?",
      "Kebiasaan soal uang teman yang mana yang pengin kamu ubah pelan-pelan?",
      "Target bareng geng ini yang butuh modal beneran itu apa?",
      "Pensiun dini dan hidup sederhana, atau kerja lebih lama dan hidup mewah?",
      "Hal paling dermawan yang pernah kamu lihat dilakuin seseorang di sini pakai uang?",
      "Gimana sebaiknya kalau satu teman penghasilannya jauh lebih besar dari yang lain?",
      "Pengeluaran geng ini yang mana yang worth it banget?",
      "Kekhawatiran soal uang apa yang mungkin orang-orang di sini belum tahu?",
      "Pencapaian soal uangmu yang mana yang harusnya dirayain lebih heboh?",
      "Soal uang, apa yang rela kamu korbanin demi teman, tanpa mikir dua kali?",
      "Apa yang cuma bakal kamu beli kalau dibujuk seseorang di sini?",
      "Utang: harus dihindari banget, atau cuma alat biasa?",
      "Kebiasaan soal uang apa yang lagi kamu coba hentikan?",
      "Uang yang 'cukup' buat hidupmu itu kayak gimana?",
      "Kado paling royal yang pernah kamu kasih ke seseorang di ruangan ini apa?",
      "Siapa di sini yang paling mungkin jadi kaya, dan caranya gimana?",
      "Kesalahan soal uang apa yang pengin kamu peringatin ke semua orang di sini?",
      "Semua orang di sini tahu gajimu, atau nggak ada yang tahu selamanya — pilih satu.",
      "Hal gratis terbaik yang pernah geng ini lakuin apa?",
      "Foya-foya apa yang cuma masuk akal kalau bareng geng ini?",
      "Kalau geng ini bikin usaha, siapa yang pegang uangnya?",
    ],
  },
  dreams: {
    shared: [
      "Skill apa yang pengin kamu kuasai banget sebelum umur 60?",
      "Kalau uang bukan masalah, tahun depan mau kamu habisin gimana?",
      "Hari Selasa yang sempurna tapi biasa aja itu kayak gimana buatmu?",
      "Mimpi apa yang pernah kamu lepas dan pengin kamu kejar lagi?",
      "Petualangan apa yang belum kita coba dan kamu pengin banget?",
      "Kalau bisa tinggal setahun di negara lain, di mana dan kenapa?",
      "Apa yang ada di daftarmu yang harus kita lakuin bareng tahun ini?",
      "Kalau kita bikin usaha bareng, usaha apa?",
      "Mimpi apa yang belum pernah kamu ceritain ke siapa pun?",
      "Kalau bisa jago satu skill dalam semalam, kamu pilih apa?",
      "Versi dirimu di masa depan yang bikin kamu excited itu kayak gimana?",
      "Apa yang bakal kamu sesali kalau nggak pernah dicoba?",
      "Kalau seharian kamu super berani, mau ngapain?",
      "Mimpi apa yang bikin kamu agak takut karena itu penting banget?",
      "Bucket list mana yang sebenarnya bisa kamu wujudkan tahun ini?",
      "Apa yang bakal kamu lakuin kalau nggak takut gagal?",
      "Mimpi masa kecil apa yang diam-diam masih penting buatmu?",
      "Kalau sukses udah pasti, apa yang akhirnya bakal kamu kejar?",
    ],
    couples: [
      "Liburan impian apa yang pengin kamu lakuin bareng aku suatu hari?",
      "Sepuluh tahun lagi, kamu bayangin kita tinggal di mana?",
      "Hidup impianmu bareng pasanganmu itu kayak gimana?",
      "Tradisi apa yang harus kita mulai sebagai pasangan?",
      "Apa yang kamu harap nggak pernah berubah dari kita?",
      "Target apa yang lagi kamu kejar dan pengin dibantu pasanganmu?",
      "Kamu pengin kita jadi pasangan tua yang kayak gimana?",
      "Tiga puluh tahun lagi, kamu pengin orang ngomong apa soal kita?",
      "Mimpi apa yang belum sepenuhnya kamu ceritain ke pasanganmu?",
      "Gimana pasanganmu bisa dukung target yang lagi kamu kejar sekarang?",
      "Apa yang kamu mimpikan buat dibangun bareng, bukan cuma dialami?",
      "Kalau kita desain rumah impian dari nol, apa yang wajib ada?",
      "Versi 'kita' sepuluh tahun lagi yang paling bikin kamu semangat itu kayak gimana?",
      "Mimpi apa yang kamu lepas dan bisa dibantu pasanganmu buat dikejar lagi?",
      "Apa yang pengin kita berdua tinggalkan buat orang lain?",
      "Apa yang pengin kita capai bareng sebelum umur tertentu?",
      "Mimpi bersama apa yang rasanya masih agak jauh sekarang?",
      "Realistisnya, kamu pengin kita menua bareng dengan cara gimana?",
      "Mimpi pasanganmu yang mana yang pengin banget kamu bantu wujudkan?",
      "Kalau gagal itu nggak mungkin, risiko apa yang bakal kita ambil bareng?",
      "Masa pensiun ideal bareng pasanganmu itu kayak gimana?",
      "Skill apa yang pengin kalian pelajari bareng?",
      "Di mana kamu mimpi punya rumah bareng suatu hari nanti?",
      "Apa soal masa depan kita yang belum pernah kamu ucapin?",
      "Rangkum mimpi bersama kita dalam satu kalimat.",
      "Target pasanganmu yang mana yang paling diam-diam kamu dukung?",
      "Mimpi apa buat hubungan ini yang belum berani kamu ucapin?",
      "Kalau uang dan waktu nggak jadi masalah, kita bakal bangun apa bareng?",
      "Petualangan kayak gimana yang pengin kamu alami bareng pasanganmu?",
      "Kalau kamu lupa sama mimpimu, gimana pasanganmu harus ngingetin?",
      "Dua puluh tahun lagi, kamu harap kita masih mimpiin apa bareng?",
      "Mimpi apa yang kamu takut buat ngaku kamu pengin?",
      "Janji apa soal masa depan kita yang mau kamu buat sekarang?",
      "Satu hal apa yang harus kita lakuin bareng sebelum terlambat?",
    ],
    friends: [
      "Sepuluh tahun lagi kamu pengin tinggal di mana — dan siapa yang tinggal dekat?",
      "Liburan apa yang harusnya beneran dipesan geng ini, bukan cuma wacana?",
      "Kamu pengin dikenal karena apa sama orang-orang yang kenal kamu?",
      "Target apa yang lagi kamu kejar dan bisa dibantu seseorang di sini?",
      "Kamu pengin jadi orang tua yang kayak gimana nanti?",
      "Tradisi apa yang harus dimulai geng ini?",
      "Apa yang kamu harap nggak pernah berubah dari teman-temanmu?",
      "Mimpi apa yang belum sepenuhnya kamu ceritain ke siapa pun di sini?",
      "Gimana geng ini bisa dukung target yang lagi kamu kejar sekarang?",
      "Apa yang pengin kamu bangun bareng orang-orang di sini, bukan cuma dialami?",
      "Kalau geng ini bikin proyek dari nol, proyek apa?",
      "Versi geng ini sepuluh tahun lagi yang paling bikin kamu semangat itu kayak gimana?",
      "Mimpi apa yang kamu lepas dan bisa dibantu seseorang di sini buat dikejar lagi?",
      "Apa yang pengin ditinggalkan geng ini buat orang lain?",
      "Apa yang pengin kamu capai sebelum umur tertentu, sambil disorakin geng ini?",
      "Mimpi bareng geng ini yang rasanya masih agak jauh sekarang apa?",
      "Gimana kamu pengin tetap dekat sama geng ini seiring bertambah umur?",
      "Mimpi siapa di sini yang pengin banget kamu bantu wujudkan?",
      "Kalau gagal itu nggak mungkin, risiko apa yang bakal kamu ambil bareng geng ini?",
      "Reuni ideal sama geng ini 20 tahun lagi itu kayak gimana?",
      "Skill apa yang pengin dipelajari geng ini bareng?",
      "Di mana kamu mimpi bisa ngumpulin geng ini semua suatu hari?",
      "Apa soal masa depanmu yang belum pernah kamu ceritain ke siapa pun di sini?",
      "Rangkum mimpi terbesarmu dalam satu kalimat.",
      "Target siapa di sini yang paling diam-diam kamu dukung?",
      "Mimpi apa buat pertemanan ini yang belum berani kamu ucapin?",
      "Kalau uang dan waktu nggak jadi masalah, kamu bakal bangun apa bareng geng ini?",
      "Petualangan kayak gimana yang pengin kamu alami bareng orang-orang di sini?",
      "Kalau kamu lupa sama mimpimu, gimana geng ini harus ngingetin?",
      "Dua puluh tahun lagi, kamu harap masih ngapain bareng geng ini?",
      "Mimpi apa yang kamu takut buat ngaku kamu pengin?",
      "Janji apa soal masa depan yang mau kamu buat ke geng ini sekarang?",
      "Satu hal apa yang harus kamu lakuin bareng geng ini sebelum terlambat?",
      "Mimpi siapa di sini yang pantas dapat dukungan jauh lebih banyak?",
    ],
  },
  dare: {
    shared: [
      "Selfie paling konyol bareng. Sekarang juga.",
      "Tukeran HP terus ganti wallpaper satu sama lain.",
      "Nyanyiin reff lagu yang semua orang di sini tahu.",
      "Ngomong 30 detik soal hal yang kamu suka. Nggak boleh 'eee'.",
      "Ngomong pakai logat daerah sampai giliranmu berikutnya.",
      "Keluarin jurus joget terbaikmu selama 10 detik. Nggak ada alasan.",
      "Sebutin alfabet dari belakang. Semua lagi nonton.",
      "Biarin yang lain kasih kamu julukan konyol sampai game selesai.",
      "Coba jilat sikumu sendiri. Coba aja.",
      "Tirukan artis sampai ada yang bisa nebak siapa.",
      "Taruh sesuatu di atas kepala dan jaga biar nggak jatuh selama 15 detik.",
      "Kirim emoji random ke orang terakhir yang kamu chat. Tanpa penjelasan.",
      "Plank 20 detik sambil ngelawak.",
      "Biarin orang lain nata rambutmu buat ronde berikutnya.",
      "Cuma boleh ngomong pakai kalimat tanya sampai giliranmu berikutnya.",
      "Peragakan gimana kamu bangun tidur tadi pagi.",
      "Tunjukin foto paling aneh di galerimu.",
      "Diam dengan pose dramatis selama 10 detik. Nggak boleh ketawa.",
    ],
    couples: [
      "Peluk pasanganmu 10 detik. Sekarang.",
      "Tirukan pasanganmu sebisa mungkin.",
      "Bilang 'aku sayang kamu' pakai logat yang paling konyol.",
      "Bisikin sesuatu yang manis di telinga pasanganmu.",
      "Dansa pelan 15 detik. Musik opsional.",
      "Suapin pasanganmu camilan atau kasih dia seteguk minumanmu.",
      "Peragakan gimana kalian pertama ketemu, kayak adegan film.",
      "Pegangan tangan dan saling tatap 20 detik. Jangan ketawa.",
      "Puji pasanganmu cuma pakai gerakan tangan. Nggak boleh ngomong.",
      "Pijat bahu pasanganmu selama 30 detik.",
      "Bikin pasanganmu ketawa dalam 15 detik tanpa nyentuh dia.",
      "Nyanyiin reff lagu 'kalian' bareng-bareng.",
      "Gambar sesuatu di telapak tangan pasanganmu pakai jari. Dia yang nebak.",
      "Sebutin tiga hal yang kamu suka dari pasanganmu — nggak boleh ada kata yang diulang.",
      "Bikin ulang foto pertama kalian berdua, lengkap sama posenya.",
      "Tulis nama pasanganmu di punggungnya pakai jari. Dia harus nebak.",
      "Kasih pasanganmu julukan berdasarkan kelakuannya hari ini.",
      "Ceritain ke pasanganmu momen persis waktu kamu pengin jadian sama dia.",
      "Ulang adegan pertama kalian ketemu dalam gerak lambat, 10 detik.",
      "Biarin pasanganmu pilih bajumu buat besok, nggak boleh protes.",
      "Nyanyiin lagu paling jelek yang kamu tahu buat pasanganmu. Muka datar.",
      "Tatap mata pasanganmu dan bilang satu hal yang bikin kamu gemas sama dia.",
      "Gambar hati di tanganmu dan 'kasih' ke pasanganmu.",
      "Bisikin kenangan favoritmu soal pasanganmu di telinganya.",
      "Peragakan rutinitas pagi pasanganmu — dilebay-lebayin.",
      "Tatap mata pasanganmu tiga detik, terus cium tangannya.",
      "Tebak apa yang lagi dipikirin pasanganmu sekarang, keras-keras.",
      "Bilang satu hal lucu, satu hal seksi, dan satu hal yang bikin kamu merasa 'pulang' dari pasanganmu.",
      "Tirukan ekspresi wajah khas pasanganmu.",
      "Kasih pasanganmu pidato tulus, kayak di acara nikahan.",
      "Biarin pasanganmu pilih topik pertanyaan berikutnya buat kalian berdua.",
      "Tirukan ketawa pasanganmu semirip mungkin.",
      "Pegangan tangan dan gambarkan tangan pasanganmu. Yang manis, ya.",
      "Bilang ke pasanganmu apa yang paling bakal kamu kangenin kalau pisah seminggu.",
    ],
    friends: [
      "Tirukan seseorang di ruangan ini sebisa mungkin.",
      "Tunjukin foto terakhir di galerimu dan jelasin.",
      "Sebutin tiga hal tulus soal pemain di sebelah kananmu. Nggak boleh diulang.",
      "Bacain pesan terakhir yang kamu kirim, sedramatis mungkin.",
      "Push-up 10 kali atau cerita pengalaman memalukan. Pilih sekarang.",
      "Biarin seseorang di sini pilih lagu berikutnya. Nggak boleh protes.",
      "Bikin satu geng ketawa dalam 15 detik tanpa ngomong sepatah kata pun.",
      "Biarin pemain di sebelah kirimu kasih julukan baru sampai game selesai.",
      "Peragakan gimana kamu pertama kenal pemain di sebelah kananmu — dilebay-lebayin.",
      "Tebak hal terakhir yang dicari seseorang di sini di HP-nya.",
      "Kasih pemain di depanmu julukan berdasarkan kejadian malam ini.",
      "Peragakan reaksi seseorang di sini waktu kalah.",
      "Ceritain ke geng alasan sebenarnya kamu telat waktu terakhir ketemu.",
      "Biarin geng milihin foto profilmu selama seminggu.",
      "Tirukan anggota geng yang paling drama.",
      "Tebak persis gimana reaksi seseorang kalau kamu ceritain rahasia sekarang.",
      "Gambar orang di depanmu dalam 15 detik.",
      "Bisikin hal paling manis yang kepikiran ke orang di sebelah kirimu.",
      "Peragakan gimana seseorang di sini pesan makanan di restoran.",
      "Kasih pidato tulus buat geng ini, kayak di acara reuni.",
      "Tebak apa yang lagi dipikirin seseorang di sini, keras-keras.",
      "Ceritain satu hal soal kamu yang nggak bakal ditebak geng ini.",
      "Tirukan kata-kata andalan seseorang, semirip mungkin.",
      "Biarin geng milihin julukanmu sampai malam ini selesai.",
      "Tirukan ketawa paling heboh dari seseorang di ruangan ini.",
      "Julurkan tanganmu dan biarin seseorang di sini 'meramal' garis tanganmu. Asal-asalan.",
      "Bilang ke geng apa yang paling bakal kamu kangenin kalau pisah sebulan.",
      "Pilih seseorang dan sebut kata pertama yang muncul di kepalamu soal dia.",
      "Tirukan dirimu sendiri sejelek mungkin.",
      "Biarin seseorang di sini jawab pertanyaanmu berikutnya.",
      "Tunjukin galeri fotomu dari 24 jam terakhir ke geng.",
      "Kasih ucapan satu kalimat buat orang di sebelah kananmu.",
      "Peragakan debat terakhirmu sama siapa pun — versi lucunya.",
      "Biarin geng voting julukan baru buatmu. Nggak boleh nolak.",
    ],
  },
  deep: {
    shared: [
      "'Rumah' itu sebenarnya artinya apa buatmu?",
      "Bagian mana dari dirimu yang masih lagi kamu perbaiki?",
      "Kalau lagi stres, kamu sebenarnya pengin dibantu kayak gimana?",
      "Memaafkan seseorang itu artinya apa buatmu?",
      "Kalau kamu bikin salah, kamu pengin diperlakukan kayak gimana?",
      "Apa yang lagi berat buatmu belakangan ini?",
      "Apa yang pengin kamu ingat dari fase hidupmu yang sekarang?",
      "Kapan terakhir kamu merasa beneran dimengerti?",
      "Beban apa yang kamu bawa tapi nggak ada yang tahu?",
      "Rasa tenang itu kerasa kayak apa di tubuhmu?",
      "Keyakinan soal dirimu yang mana yang lagi kamu coba lepasin?",
      "Kapan kamu merasa paling jadi dirimu sendiri?",
      "Kalimat apa yang dulu waktu kecil kamu butuh dengar tapi nggak pernah dapat?",
      "Ketakutan apa yang belum pernah kamu ucapin?",
      "Percaya sepenuhnya sama seseorang itu artinya apa buatmu?",
      "Apa yang lagi diam-diam kamu relakan sekarang?",
      "Apa yang kamu harap orang ngerti soal cara kerja pikiranmu?",
      "Momen apa yang mengubah caramu melihat dirimu sendiri?",
    ],
    couples: [
      "Apa yang lagi berat buatmu belakangan ini yang bisa aku bantu?",
      "Ada kekhawatiran nggak soal kita?",
      "Belakangan ini kamu butuh apa lebih banyak dari aku?",
      "Gimana kamu bertumbuh sejak kita bareng?",
      "Ada yang belum terucap di antara kita yang pengin kamu bahas?",
      "Sama aku ngajarin kamu apa soal cinta?",
      "Apa yang kamu takut buat minta dari aku?",
      "Apa dari masa lalumu yang masih membentuk caramu mencintai?",
      "Apa yang harus aku ingat kalau suatu saat kita berantem hebat?",
      "Bagian dirimu yang mana yang cuma pernah kamu tunjukin ke pasanganmu?",
      "Apa yang kamu takut hilang dari hubungan ini?",
      "Gimana pasanganmu bantu kamu lebih memahami dirimu sendiri?",
      "Luka lama dari sebelum kita yang kadang masih muncul itu apa?",
      "Di hari terburukmu, kamu butuh apa dari aku?",
      "Apa yang udah kamu maafin dari aku tapi nggak pernah kita bahas?",
      "Merasa aman sama aku itu sebenarnya kerasa kayak gimana?",
      "Kebenaran soal dirimu yang mana yang masih takut kamu ceritain ke aku?",
      "Kalau kamu lagi berduka, kamu pengin aku hadir kayak gimana?",
      "Apa soal cinta yang masih bikin kamu takut, bahkan sekarang?",
      "Bagian dirimu yang mana yang menurutmu masih belum sepenuhnya aku pahami?",
      "Momen bareng aku yang mana yang mengubah caramu melihat dirimu?",
      "Kalimat apa yang kamu butuh dengar dari aku tapi jarang aku ucapin?",
      "Apa yang kamu bangga berhasil kamu lewati, dengan bantuanku?",
      "Merasa benar-benar dikenal sama seseorang itu artinya apa buatmu?",
      "Sisi dirimu yang mana yang kamu takut akhirnya aku lihat?",
      "Apa yang kamu harap aku ngerti soal isi kepalamu waktu kita lagi berantem?",
      "Apa yang kamu butuhin dari pasangan tapi lama baru berani minta?",
      "Kalau kata-kata nggak membantu, kamu pengin dihibur kayak gimana?",
      "Ketakutan soal masa depan kita yang belum pernah kamu ucapin itu apa?",
      "'Tanpa syarat' itu kelihatan kayak gimana dalam keseharian?",
      "Luka apa yang masih kamu pulihkan dan kelihatan dari caramu mencintai?",
      "Apa yang kamu pengin aku nggak pernah nyerah, bahkan waktu lagi susah?",
      "Kapan aku bikin kamu merasa paling aman?",
      "Apa yang benar soal kamu yang cuma aku yang benar-benar tahu?",
    ],
    friends: [
      "Ada yang belum terucap antara kamu sama seseorang di sini?",
      "Belakangan ini kamu butuh apa lebih banyak dari teman-temanmu?",
      "Apa yang kamu takut buat minta ke orang lain?",
      "Gimana kamu berubah sejak geng ini kenal kamu?",
      "Pertemanan apa yang udah hilang tapi masih sering kamu pikirin?",
      "Apa yang paling susah buat kamu ucapin langsung?",
      "Kapan kamu merasa kesepian padahal lagi rame?",
      "Kalau seseorang di sini bikin kamu kesal, dia harus ngapain?",
      "Bagian dirimu yang mana yang cuma kamu tunjukin ke teman dekat?",
      "Apa yang kamu takut hilang dari pertemanan ini?",
      "Gimana pertemanan ini bantu kamu lebih memahami dirimu sendiri?",
      "Luka lama dari sebelum kenal geng ini yang kadang masih muncul itu apa?",
      "Di hari terburukmu, kamu butuh apa dari teman?",
      "Apa yang udah kamu maafin dari seseorang di sini tapi nggak pernah dibahas?",
      "Merasa aman sama orang-orang di sini itu sebenarnya kerasa kayak gimana?",
      "Kebenaran soal dirimu yang mana yang masih takut kamu ceritain ke geng ini?",
      "Kalau kamu lagi berduka, kamu pengin orang-orang di sini hadir kayak gimana?",
      "Apa soal pertemanan yang masih bikin kamu takut, bahkan sekarang?",
      "Bagian dirimu yang mana yang menurutmu geng ini belum sepenuhnya paham?",
      "Momen bareng seseorang di sini yang mana yang mengubah caramu melihat dirimu?",
      "Kalimat apa yang kamu butuh dengar dari geng ini tapi jarang diucapin?",
      "Apa yang kamu bangga berhasil kamu lewati, dengan bantuan seseorang di sini?",
      "Merasa benar-benar dikenal sama teman itu artinya apa buatmu?",
      "Sisi dirimu yang mana yang kamu takut akhirnya dilihat geng ini?",
      "Apa yang kamu harap geng ini ngerti soal isi kepalamu waktu lagi ribut?",
      "Apa yang kamu butuhin dari teman tapi lama baru berani minta?",
      "Kalau kata-kata nggak membantu, kamu pengin dihibur kayak gimana?",
      "Ketakutan soal masa depan pertemanan ini yang belum pernah kamu ucapin itu apa?",
      "Dukungan tanpa syarat itu kelihatan kayak gimana dalam keseharian?",
      "Luka apa yang masih kamu pulihkan dan kelihatan dari caramu berteman?",
      "Apa yang kamu pengin geng ini nggak pernah nyerah, bahkan waktu lagi susah?",
      "Kapan seseorang di sini bikin kamu merasa paling aman?",
      "Apa yang benar soal kamu yang cuma teman dekat yang benar-benar tahu?",
      "Masa sulit apa yang dibantu seseorang di sini tanpa dia sadar?",
    ],
  },
  memories: {
    shared: [
      "Hal paling spontan yang pernah kita lakuin bareng apa?",
      "Apa yang kamu pikirin soal aku waktu pertama kali lihat?",
      "Momen kecil dan biasa bareng aku yang mana yang masih kamu ingat?",
      "Perjalanan kita yang mana yang masih sering kamu pikirin?",
      "Perayaan terbaik kita itu yang mana?",
      "Apa yang dulu sering kita lakuin dan harus banget dihidupin lagi?",
      "Cerita soal kita yang paling kamu suka ceritain ke orang apa?",
      "Momen bareng aku yang mana yang pengin kamu ulang?",
      "Ingatan paling awalmu soal aku apa?",
      "Kenangan apa yang masih bikin kamu ngakak tiap kali ingat?",
      "Bau atau suara apa yang langsung bikin kamu ingat kenangan kita?",
      "Foto kita yang mana yang paling 'kita banget', dan kenapa?",
      "Kenangan apa yang baru terasa spesial belakangan?",
      "Apa yang pernah kita lakuin sekali dan nggak pernah dibahas lagi?",
      "Kenangan kita yang mana yang bakal bikin kaget orang yang baru kenal kita sekarang?",
      "Hal terakhir yang pengin kamu pikirin sebelum tidur malam ini apa?",
      "Kenangan soal aku yang belum pernah kamu ceritain ke aku itu apa?",
      "Masa kebersamaan kita yang mana yang pengin kamu ulang persis sama?",
    ],
    couples: [
      "Kenangan favoritmu dari beberapa bulan pertama kita apa?",
      "Foto favoritmu dari kita berdua yang mana?",
      "Ceritain kencan pertama kita — versimu.",
      "Hal paling berat yang pernah kita lewati apa?",
      "Berantem paling lucu yang pernah kita alami apa?",
      "Kado dari aku yang mana yang paling berarti buatmu?",
      "Kapan pertama kali kamu merasa kita beneran satu tim?",
      "Hal pertama yang kamu ceritain ke teman-temanmu soal aku apa?",
      "Kapan hubungan ini pertama kali terasa serius?",
      "Berantem yang mana yang sekarang bisa kamu ketawain?",
      "Kapan kamu paling deg-degan di depan pasanganmu?",
      "Kenangan soal pasanganmu yang belum pernah kamu ceritain ke siapa pun apa?",
      "Kejutan terbaik yang pernah pasanganmu kasih apa?",
      "Kapan pasanganmu membuktikan dia benar-benar kenal kamu?",
      "Hal paling konyol yang pernah kalian ributin apa?",
      "Masa sulit apa yang bikin kamu makin sayang sama pasanganmu?",
      "Hal paling spontan yang pernah kalian lakuin apa?",
      "Kenangan soal keluarga pasanganmu yang mana yang membekas?",
      "Pujian pertama yang pernah pasanganmu kasih apa?",
      "Kenangan apa yang masih bikin deg-degan sampai sekarang?",
      "Momen 'ini dia orangnya' terbesarmu sama pasanganmu kapan?",
      "Apa yang kamu ingat waktu kalian siap-siap mau kencan?",
      "Kejadian paling lucu yang salah waktu jalan-jalan bareng apa?",
      "Kapan kalian saling menghibur dengan cara yang bikin kamu bangga?",
      "Kapan kamu tahu teman-teman pasanganmu suka sama kamu?",
      "Apa yang kamu ingat waktu ketemu keluarga pasanganmu?",
      "Hari 'biasa aja' terbaik yang pernah kalian lewatin bareng apa?",
      "Kenangan apa yang masih terasa kayak adegan film?",
      "Kapan kamu sadar kamu bakal milih pasanganmu lagi dan lagi?",
      "Kapan pasanganmu bikin kamu kaget karena dia kenal kamu banget?",
      "Momen tukar kado favorit kalian berdua yang mana?",
      "Kenangan apa yang kamu nggak mau sampai lupa?",
      "Kenangan apa yang paling menggambarkan kenapa kamu sayang pasanganmu?",
      "Kenangan apa yang detailnya masih kalian perdebatkan sampai sekarang?",
    ],
    friends: [
      "Kenangan favoritmu sama seseorang di ruangan ini apa?",
      "Ceritain gimana kamu kenal seseorang di sini — versimu.",
      "Kejadian paling lucu yang pernah dialami geng ini apa?",
      "Ide paling buruk yang kita semua iyain itu apa?",
      "Foto kita yang mana yang nggak bakal pernah kamu hapus?",
      "Kapan pertama kali kamu merasa beneran jadi bagian geng ini?",
      "Apa pendapatmu soal aku sebelum benar-benar kenal?",
      "Malam apa yang harusnya kita semua nggak selamat?",
      "Kapan pertama kali kamu merasa pertemanan ini bakal awet?",
      "Ribut-ribut yang mana yang sekarang bisa kamu ketawain?",
      "Kapan kamu paling deg-degan waktu ketemu seseorang di sini?",
      "Kenangan soal seseorang di sini yang belum pernah kamu ceritain ke siapa pun apa?",
      "Kejutan terbaik yang pernah dibikin seseorang di sini apa?",
      "Kapan seseorang di sini membuktikan dia benar-benar kenal kamu?",
      "Hal paling konyol yang pernah diributin geng ini apa?",
      "Masa sulit apa yang bikin kamu makin menghargai geng ini?",
      "Hal paling spontan yang pernah dilakuin geng ini apa?",
      "Kenangan soal keluarga seseorang yang mana yang membekas?",
      "Pujian pertama yang pernah kamu dapat dari seseorang di sini apa?",
      "Kenangan apa yang masih bikin kamu senyum-senyum?",
      "Momen 'ini baru teman sejati' terbesarmu sama geng ini kapan?",
      "Apa yang kamu ingat waktu kalian siap-siap mau keluar malam bareng?",
      "Kejadian paling lucu yang salah waktu jalan-jalan sama geng ini apa?",
      "Kapan kalian saling menghibur dengan cara yang bikin kamu bangga?",
      "Kapan kamu tahu kamu benar-benar cocok di sini?",
      "Apa yang kamu ingat waktu pertama kali ketemu keluarga seseorang di sini?",
      "Hari 'biasa aja' terbaik yang pernah kamu lewatin sama geng ini apa?",
      "Kenangan apa yang masih terasa kayak adegan film?",
      "Kapan kamu sadar kamu bakal milih pertemanan ini lagi dan lagi?",
      "Kapan seseorang bikin kamu kaget karena dia kenal kamu banget?",
      "Momen tukar kado terbaik di geng ini yang mana?",
      "Kenangan apa yang kamu pengin geng ini nggak pernah lupa?",
      "Kenangan apa yang paling menggambarkan kenapa geng ini penting buatmu?",
      "Kenangan apa yang detailnya masih kalian perdebatkan sampai sekarang?",
    ],
  },
  home: {
    shared: [
      "Akhir pekan sempurna di rumah itu kayak gimana buatmu?",
      "Kerjaan rumah mana yang diam-diam nggak masalah buatmu?",
      "Tradisi masa kecil apa yang pengin terus kamu lanjutin?",
      "Apa dari caraku dibesarkan yang banyak menjelaskan diriku?",
      "Kalau besok kita bikin acara makan malam, siapa aja yang diundang?",
      "Pagi yang santai buatmu itu kayak gimana?",
      "Kalau bisa, apa yang pengin kamu ubah dari rutinitas harianmu?",
      "Kamu sebenarnya butuh waktu bareng orang sama waktu sendiri seberapa banyak?",
      "Bau apa yang langsung bikin kamu merasa 'ini rumah'?",
      "Aturan di rumah masa kecilmu yang mana yang masih kamu pegang — atau udah kamu langgar?",
      "Kamarmu paling berantakan pernah kayak gimana, dan kenapa?",
      "Gambarkan rumah impianmu dalam satu kalimat.",
      "Barang apa di tempatmu yang punya cerita di baliknya?",
      "Kebiasaanmu di rumah yang mana yang ternyata aneh setelah ada yang bilang?",
      "Merasa betah di suatu tempat itu sebenarnya kayak gimana buatmu?",
      "Rumah siapa yang pernah kamu kunjungi sekali dan masih kamu ingat terus?",
      "Rumahmu paling ramai itu kalau lagi ngeributin apa?",
      "Ritual kecil apa yang bikin tempat mana pun terasa kayak rumah?",
    ],
    couples: [
      "Gimana kita bagi kerjaan rumah yang nggak kelihatan?",
      "Apa yang bikin tempat tinggal kita terasa lebih 'kita'?",
      "Kamu pengin momen liburan hari raya kita terasa kayak gimana?",
      "Kalau salah satu dari kita butuh ruang sendiri, kita harus gimana?",
      "Apa yang kamu harap lebih sering kita lakuin di rumah?",
      "Di keluargaku, kamu paling dekat sama siapa?",
      "Batasan apa sama keluarga yang perlu kita pasang?",
      "Gimana kamu pengin kita terima tamu di tempat kita?",
      "Hal kecil apa di tempat kita yang bikin terasa 'punya kita'?",
      "Kerjaan rumah apa yang pengin kamu ambil alih dari aku selamanya?",
      "Jujur, menurutmu dekorasi tempat kita gimana?",
      "Ribut-ribut soal rumah yang mana yang sekarang kelihatan konyol?",
      "Kamu pengin tamu merasa gimana waktu main ke tempat kita?",
      "Gimana perasaanmu soal cara kita ngabisin malam di rumah?",
      "Kebiasaanku di rumah yang mana yang diam-diam menurutmu lucu?",
      "Apa yang pengin kamu ubah dari pagi-pagi kita bareng?",
      "Tradisi keluargaku yang mana yang udah kamu adopsi jadi punyamu?",
      "Hari hujan ideal di dalam rumah buat kita itu kayak gimana?",
      "Apa dari keluargaku yang bikin kamu lebih paham aku?",
      "Kamu pengin rumah kita terasa beda gimana dari rumah tempat kita tumbuh?",
      "Aturan rumah apa yang harus kita resmikan?",
      "Suara favoritmu di rumah kita apa?",
      "Apa yang harus lebih sering kita lakuin di rumah, berdua aja?",
      "Hari gabut terbaik yang pernah kita habisin di rumah yang mana?",
      "Kerjaan rumah apa yang diam-diam kamu kesel kalau ngerjain sendirian?",
      "Apa yang kamu suka — atau nggak suka — dari jadi tuan rumah bareng?",
      "Kenangan pindahan bareng yang masih bikin kamu ketawa apa?",
      "Kalau uang bukan masalah, satu hal apa yang pengin kamu perbaiki di rumah?",
      "Hal kecil apa yang aku lakuin di rumah yang bikin kamu merasa diurus?",
      "Seberapa jauh kamu pengin keluarga kita terlibat di urusan rumah kita?",
      "Batasan apa sama mertua yang harus kita pasang bareng?",
      "Minggu sempurna di rumah versimu itu kayak gimana?",
      "Apa dari caraku ngurus rumah yang pengin kamu ubah pelan-pelan?",
      "Sudut mana di tempat kita yang paling 'kamu banget'?",
    ],
    friends: [
      "Geng ini selalu ujung-ujungnya ngumpul di tempat siapa, dan kenapa?",
      "Keluargamu kayak gimana kalau semua lagi kumpul di satu ruangan?",
      "Apa yang kamu harap teman-temanmu tahu soal tempat kamu tumbuh?",
      "Kamu biasanya jadi tuan rumah atau tamu?",
      "Tradisi keluarga apa yang pengin kamu bawa ke geng ini?",
      "Siapa di keluargamu yang paling bakal cocok sama orang-orang di sini?",
      "Satu aturan rumah yang nggak bakal pernah kamu langgar apa?",
      "Hal kecil apa di tempat seseorang yang bikin 'dia banget'?",
      "Kerjaan rumah apa yang nggak bakal kamu tawarin waktu numpang di tempat orang?",
      "Jujur, menurutmu dekorasi tempat seseorang di sini gimana?",
      "Ribut-ribut di tempat bareng yang mana yang sekarang kelihatan konyol?",
      "Kamu pengin tempat teman terasa gimana waktu kamu main ke sana?",
      "Numpang nginep di tempat orang tanpa bilang-bilang — oke atau nggak?",
      "Kebiasaan teman sekos atau teman yang mana yang diam-diam menurutmu lucu?",
      "Apa yang pengin kamu ubah dari cara geng ini nongkrong di tempat seseorang?",
      "Tradisi keluargamu yang mana yang pengin kamu bagi sama geng ini?",
      "Hari hujan ideal di dalam ruangan buat geng ini itu kayak gimana?",
      "Apa dari keluarga seseorang yang bikin kamu lebih paham dia?",
      "Kamu pengin tongkrongan kita terasa beda gimana dari yang kamu alami waktu kecil?",
      "Aturan rumah apa yang harus diresmikan geng ini?",
      "Suara favoritmu dari tempat yang terasa kayak rumah apa?",
      "Apa yang harus lebih sering dilakuin geng ini — sekadar santai di tempat seseorang?",
      "Hari gabut terbaik yang pernah kamu habisin di tempat seseorang yang mana?",
      "Kerjaan apa yang diam-diam kamu kesel kalau lagi jadi tuan rumah?",
      "Apa yang kamu suka — atau nggak suka — dari jadi tuan rumah buat geng ini?",
      "Kenangan nginep atau nongkrong bareng yang masih bikin kamu ketawa apa?",
      "Kalau uang bukan masalah, satu hal apa yang pengin kamu perbaiki di rumah?",
      "Hal kecil apa yang dilakuin teman di tempatnya yang bikin kamu merasa diterima?",
      "Seberapa jauh kamu pengin keluargamu terlibat di pertemananmu?",
      "Batasan apa sama teman sekos atau keluarga yang harus dihormati geng ini?",
      "Minggu nongkrong sempurna versimu itu kayak gimana?",
      "Apa dari cara seseorang di sini ngurus tempatnya yang bikin kamu kaget?",
      "Sudut mana di tempat seseorang yang paling 'dia banget'?",
      "Kalau harus milih, tempat siapa yang paling bikin kamu males pulang?",
    ],
  },
  growth: {
    shared: [
      "Tahun ini kamu bangga sama dirimu karena apa?",
      "Gimana kamu berubah dalam lima tahun terakhir?",
      "Apa yang dulu bikin kamu takut tapi sekarang udah nggak?",
      "Setahun lagi, kamu pengin lebih jago di hal apa?",
      "Pendapat apa yang udah kamu ubah total?",
      "Di bagian mana kamu merasa lagi stuck sekarang?",
      "Sukses itu artinya apa buatmu akhir-akhir ini?",
      "Kebiasaan apa yang bakal bikin hidupmu jauh lebih baik kalau kamu konsisten?",
      "Apa yang pengin kamu coba tapi merasa udah ketuaan atau telat?",
      "Bagian mana dari kerjaanmu yang beneran bikin kamu semangat?",
      "Kapan terakhir kamu ngelakuin sesuatu yang bikin takut?",
      "Kamu perlu lebih sering bilang 'nggak' ke apa?",
      "Dirimu sepuluh tahun lalu bakal mikir apa soal kamu sekarang?",
      "Kesalahan apa yang ngajarin kamu lebih banyak dari kemenangan mana pun?",
      "Apa yang dulu bikin kamu malu tapi sekarang udah nggak?",
      "Versi lama dirimu yang mana yang kamu syukuri udah kamu tinggalin?",
      "Kebiasaan atau pola pikir apa yang paling susah kamu lepasin?",
      "Pujian soal perkembanganmu yang pengin banget kamu dengar sekarang apa?",
    ],
    couples: [
      "Masukan dari aku yang mana yang beneran membantu kamu?",
      "Masukan apa yang kamu harap aku sampaikan lebih lembut?",
      "Gimana kamu pengin aku bantu kamu tetap di jalur?",
      "Apa yang udah kamu ubah dari dirimu karena hubungan ini?",
      "Kebiasaan apa yang dibantu pasanganmu tanpa dia ceramah?",
      "Versi dirimu yang mana yang belum pernah ketemu pasanganmu — dan dia rugi nggak?",
      "Apa yang lagi kamu perbaiki yang belum sepenuhnya diketahui pasanganmu?",
      "Pasanganmu bikin kamu lebih sabar — atau malah kurang?",
      "Pujian soal perkembanganmu yang pengin banget kamu dengar dari pasanganmu apa?",
      "Apa yang sekarang bisa kamu hadapi lebih baik dibanding waktu kalian baru kenal?",
      "Ketakutan apa yang udah kamu lewati sebagian berkat pasanganmu?",
      "Gimana pasanganmu dorong kamu jadi lebih baik, walau kadang nyelekit?",
      "Apa yang dilakuin pasanganmu yang diam-diam bikin kamu jadi orang yang lebih baik?",
      "Keyakinan soal hubungan apa yang udah kamu lepasin sejak sama pasanganmu?",
      "Target apa yang kamu pasang karena pasanganmu yakin kamu bisa?",
      "Apa yang dulu bikin kamu kesulitan dan dibantu pasanganmu buat dilewati?",
      "Setahun ke depan, kamu pengin kita bertumbuh bareng kayak gimana?",
      "Kamu lagi berusaha jadi siapa, yang udah dilihat pasanganmu dalam dirimu?",
      "Kebenaran pahit apa dari pasanganmu yang akhirnya malah membantu?",
      "Apa yang kamu bangga nggak kamu tinggalin, berkat dukungan pasanganmu?",
      "Gimana hubungan ini bikin kamu jadi lebih dewasa?",
      "Skill apa yang kamu dapat cuma dari sering bareng pasanganmu?",
      "Soal berantem, sekarang kalian lebih jago di bagian apa?",
      "Gimana pasanganmu ngajak kamu keluar dari zona nyaman, ke arah yang baik?",
      "Apa yang masih kamu perbaiki dan butuh kesabaran pasanganmu?",
      "Kapan pasanganmu lihat potensimu sebelum kamu sendiri sadar?",
      "Kebiasaan apa yang udah kamu tinggalin yang diam-diam disyukuri pasanganmu?",
      "Apa yang pengin kamu perbaiki demi pasanganmu, bukan cuma demi dirimu?",
      "Gimana rasa disayang bikin kamu jadi lebih berani?",
      "Pencapaian pribadi apa yang disadari pasanganmu dan harusnya kamu rayain lebih?",
      "Apa yang udah kamu maafin dari dirimu sendiri, berkat bantuan pasanganmu?",
      "Gimana pasanganmu ngajarin kamu jadi lebih baik hati — bahkan ke diri sendiri?",
      "Kesalahan apa di hubungan ini yang paling bikin kamu bertumbuh?",
      "Tahun ini, kamu paling pengin kita bertumbuh bareng dalam hal apa?",
    ],
    friends: [
      "Hal paling berguna yang pernah dibilang teman soal dirimu apa?",
      "Siapa di sini yang bakal ngomong jujur ke kamu waktu yang lain diam?",
      "Kamu pengin teman-temanmu negur kamu soal apa?",
      "Apa yang udah kamu ubah dari dirimu karena geng ini?",
      "Kebiasaan apa yang dibantu teman tanpa dia ceramah?",
      "Versi dirimu yang mana yang belum pernah ketemu geng ini — dan mereka rugi nggak?",
      "Apa yang lagi kamu perbaiki yang belum sepenuhnya diketahui orang-orang di sini?",
      "Geng ini bikin kamu lebih sabar — atau malah kurang?",
      "Pujian soal perkembanganmu yang pengin banget kamu dengar dari seseorang di sini apa?",
      "Apa yang sekarang bisa kamu hadapi lebih baik dibanding waktu geng ini baru kenal?",
      "Ketakutan apa yang udah kamu lewati sebagian berkat seseorang di sini?",
      "Gimana geng ini dorong kamu jadi lebih baik, walau kadang nyelekit?",
      "Apa yang dilakuin teman yang diam-diam bikin kamu jadi orang yang lebih baik?",
      "Keyakinan soal pertemanan apa yang udah kamu lepasin gara-gara geng ini?",
      "Target apa yang kamu pasang karena seseorang di sini yakin kamu bisa?",
      "Apa yang dulu bikin kamu kesulitan dan dibantu geng ini buat dilewati?",
      "Setahun ke depan, kamu pengin bertumbuh bareng geng ini kayak gimana?",
      "Kamu lagi berusaha jadi siapa, yang udah dilihat geng ini dalam dirimu?",
      "Kebenaran pahit apa dari seseorang di sini yang akhirnya malah membantu?",
      "Apa yang kamu bangga nggak kamu tinggalin, berkat dukungan geng ini?",
      "Gimana pertemanan ini bikin kamu jadi lebih dewasa?",
      "Skill apa yang kamu dapat cuma dari sering nongkrong sama geng ini?",
      "Soal beda pendapat, sekarang kamu lebih jago di bagian apa, berkat geng ini?",
      "Gimana seseorang di sini ngajak kamu keluar dari zona nyaman, ke arah yang baik?",
      "Apa yang masih kamu perbaiki dan butuh kesabaran geng ini?",
      "Kapan seseorang di sini lihat potensimu sebelum kamu sendiri sadar?",
      "Kebiasaan apa yang udah kamu tinggalin yang diam-diam disyukuri geng ini?",
      "Apa yang pengin kamu perbaiki demi geng ini, bukan cuma demi dirimu?",
      "Gimana dikelilingi orang-orang ini bikin kamu jadi lebih berani?",
      "Pencapaian pribadi apa yang disadari seseorang di sini dan harusnya kamu rayain lebih?",
      "Apa yang udah kamu maafin dari dirimu sendiri, berkat bantuan geng ini?",
      "Gimana geng ini ngajarin kamu jadi lebih baik hati — bahkan ke diri sendiri?",
      "Kesalahan apa di pertemanan ini yang paling bikin kamu bertumbuh?",
      "Tahun ini, kamu paling pengin bertumbuh bareng geng ini dalam hal apa?",
    ],
  },
  gratitude: {
    shared: [
      "Hari ini kamu bersyukur buat apa?",
      "Siapa di luar ruangan ini yang kamu syukuri ada di hidupmu?",
      "Kejadian berat apa yang sekarang malah kamu syukuri?",
      "Apa dari tubuhmu yang kamu syukuri?",
      "Sebutin tiga hal baik yang terjadi minggu ini.",
      "Siapa yang ngajarin kamu sesuatu yang sampai sekarang kamu syukuri?",
      "Apa dari saat ini yang layak disyukuri?",
      "Bagian mana dari kepribadianku yang kamu senang aku punya?",
      "Apa yang kamu pelajari dari aku dan kamu syukuri?",
      "Hal sederhana apa yang paling bakal kamu kangenin kalau tiba-tiba hilang?",
      "Siapa yang belum pernah benar-benar kamu ucapin terima kasih?",
      "Kenyamanan apa di hidupmu yang sering kamu anggap biasa?",
      "Apa tepatnya dari hari ini yang kamu syukuri?",
      "Masa sulit apa yang akhirnya ngasih kamu sesuatu yang baik?",
      "Bakatmu yang mana yang diam-diam kamu syukuri?",
      "Hal kecil apa yang dilakuin orang buat kamu belakangan ini yang beneran kamu hargai?",
      "Tempat apa yang kamu syukuri ada di hidupmu?",
      "Apa dari ketangguhanmu sendiri yang kamu syukuri?",
    ],
    couples: [
      "Satu hal apa soal kita yang kamu syukuri sekarang?",
      "Apa yang aku lakuin yang belum pernah benar-benar kamu ucapin terima kasih?",
      "Kenyamanan kecil apa di hidup kita yang nggak mau kamu kehilangan?",
      "Apa yang aku lakuin minggu ini yang bikin hidupmu lebih gampang?",
      "Kebiasaanmu yang mana yang kamu syukuri masih ditoleransi pasanganmu?",
      "Apa di rumah kita yang paling kamu syukuri kita punya?",
      "Apa sebenarnya sisi baik dari cara kita berantem?",
      "Apa dari kesabaran pasanganmu yang kamu syukuri?",
      "Masa sulit bareng yang mana yang sekarang kamu syukuri pernah kita lewati?",
      "Apa yang dilakuin pasanganmu tiap hari yang belum pernah benar-benar kamu ucapin terima kasih?",
      "Gimana pasanganmu bikin kamu jadi orang yang lebih baik?",
      "Apa yang dikasih keluarga pasanganmu yang kamu syukuri?",
      "Kenyamanan apa dari pasanganmu yang bikin kamu bakal bingung tanpanya?",
      "Apa dari hubungan ini yang jarang kamu ucapin terima kasih?",
      "Pengorbanan apa dari pasanganmu yang bikin kamu bersyukur banget?",
      "Apa yang diajarin pasanganmu yang kamu senang udah kamu pelajari?",
      "Cara pasanganmu hadir yang mana yang nggak mau kamu anggap biasa?",
      "Kekurangan pasanganmu yang mana yang anehnya malah kamu syukuri?",
      "Kapan dukungan pasanganmu lebih berarti dari yang dia tahu?",
      "Momen hidup bareng yang mana yang pengin kamu bekukan saking bersyukurnya?",
      "Sifat pasanganmu yang mana yang pengin lebih sering kamu ucapin terima kasih?",
      "Apa dari cara pasanganmu berdebat yang diam-diam kamu syukuri?",
      "Gimana pasanganmu bikin keluargamu jadi lebih baik — atau sebaliknya?",
      "Pengorbanan soal uang apa dari pasanganmu yang kamu syukuri?",
      "Apa dari menua bareng pasanganmu yang udah kamu syukuri dari sekarang?",
      "Kebenaran pahit apa dari pasanganmu yang sekarang kamu syukuri?",
      "Apa di rumah yang paling kamu syukuri dibawa pasanganmu?",
      "Kebiasaan kecil harian pasanganmu yang mana yang kamu syukuri?",
      "Apa yang dimaafin pasanganmu dan sampai sekarang masih kamu syukuri?",
      "Gimana pasanganmu hadir buat keluargamu dengan cara yang kamu hargai?",
      "Apa dari selera humor pasanganmu yang bikin kamu kuat di hari-hari berat?",
      "Kapan kamu merasa beruntung banget punya pasangan kayak dia?",
      "Apa dari semangat pasanganmu yang kamu senang ketularan?",
      "Satu hal apa yang pengin kamu ucapin terima kasih ke pasanganmu sekarang?",
    ],
    friends: [
      "Apa yang pernah dilakuin seseorang di sini buat kamu yang belum pernah benar-benar kamu ucapin terima kasih?",
      "Kebiasaanmu yang mana yang kamu syukuri masih ditoleransi teman-temanmu?",
      "Hal kecil apa dari geng ini yang paling bakal kamu kangenin?",
      "Siapa di sini yang bikin masa sulit jadi lebih ringan tanpa dia sadar?",
      "Apa yang kamu pelajari dari seseorang di ruangan ini dan kamu syukuri?",
      "Apa sebenarnya sisi baik dari cara geng ini beda pendapat?",
      "Kesabaran siapa di sini yang kamu syukuri?",
      "Masa sulit bareng geng ini yang mana yang sekarang kamu syukuri pernah dilewati?",
      "Apa yang rutin dilakuin teman yang belum pernah benar-benar kamu ucapin terima kasih?",
      "Gimana geng ini bikin kamu jadi orang yang lebih baik?",
      "Apa yang dibagi keluarga seseorang ke kamu yang kamu syukuri?",
      "Kenyamanan apa dari teman yang bikin kamu bakal bingung tanpanya?",
      "Apa dari pertemanan ini yang jarang kamu ucapin terima kasih?",
      "Pengorbanan apa dari teman yang bikin kamu bersyukur banget?",
      "Apa yang diajarin teman yang kamu senang udah kamu pelajari?",
      "Cara seseorang di sini hadir yang mana yang nggak mau kamu anggap biasa?",
      "Kekurangan teman yang mana yang anehnya malah kamu syukuri?",
      "Kapan dukungan seseorang lebih berarti dari yang dia tahu?",
      "Momen bareng geng ini yang mana yang pengin kamu bekukan saking bersyukurnya?",
      "Sifat seseorang di sini yang mana yang pengin lebih sering kamu ucapin terima kasih?",
      "Apa dari cara seseorang di sini berdebat yang diam-diam kamu syukuri?",
      "Gimana geng ini bikin kehidupan keluargamu jadi lebih baik — atau sebaliknya?",
      "Pengorbanan teman — soal uang atau lainnya — yang mana yang kamu syukuri?",
      "Apa dari menua bareng geng ini yang udah kamu syukuri dari sekarang?",
      "Kebenaran pahit apa dari seseorang di sini yang sekarang kamu syukuri?",
      "Apa dari kehidupan sosialmu yang paling kamu syukuri dibawa geng ini?",
      "Kebiasaan kecil seseorang di sini yang mana yang kamu syukuri?",
      "Apa yang dimaafin teman dan sampai sekarang masih kamu syukuri?",
      "Gimana geng ini hadir buat keluargamu dengan cara yang kamu hargai?",
      "Apa dari humor geng ini yang bikin kamu kuat di hari-hari berat?",
      "Kapan kamu merasa beruntung banget punya teman-teman ini?",
      "Semangat siapa di sini yang kamu senang ketularan?",
      "Satu hal apa yang pengin kamu ucapin terima kasih ke seseorang di sini sekarang?",
      "Kenangan bareng geng ini yang mana yang diam-diam kamu syukuri pernah kamu alami?",
    ],
  },
  adventure: {
    shared: [
      "Hal terbesar apa yang bakal kamu coba kalau tahu pasti nggak bakal gagal?",
      "Gunung, pantai, atau kota — di mana kamu merasa paling hidup?",
      "Tempat mana yang belum pernah kita datangi dan harus banget kita kunjungi?",
      "Rencanain semua detail, atau berangkat aja tanpa rencana?",
      "Kalau mulai besok kita libur dua minggu, mau ngapain?",
      "Kegiatan alam apa yang harus kita coba bareng tahun ini?",
      "Makanan apa yang pengin kamu makan langsung di negara asalnya?",
      "Road trip atau naik pesawat — dan siapa yang nyetir?",
      "Tempat di dekat kita yang mana yang belum pernah kita datangi?",
      "Pindah ke tempat baru tiap tahun, atau menetap di satu tempat?",
      "Hal nekat apa yang pernah kamu lakuin sekali dan nggak mau lagi?",
      "Kalau kita libur setahun penuh bareng, mau ngapain?",
      "Suara, bau, atau tempat apa yang langsung bikin kamu merasa bebas?",
      "Petualangan kecil apa yang bisa kita lakuin akhir pekan ini?",
      "Petualangan apa yang ternyata jauh beda dari yang kamu bayangin?",
      "Keputusan paling spontan yang pernah kamu ambil waktu jalan-jalan apa?",
      "Tantangan fisik apa yang pengin kamu coba bareng?",
      "Kalau bisa teleportasi ke mana aja selama sejam, ke mana?",
    ],
    couples: [
      "Liburan terbaik yang pernah kamu jalanin sebelum kita ketemu apa?",
      "Liburan anniversary impian kita itu kayak gimana?",
      "Tempat paling liar yang pengin kamu datangi bareng di mana?",
      "Liburan santai menikmati pemandangan atau petualangan penuh aksi bareng pasanganmu?",
      "Kekacauan waktu liburan apa yang pernah kalian lewati dan sekarang bikin ketawa?",
      "Petualangan apa yang dibujuk pasanganmu dan sekarang kamu syukuri?",
      "Pemandangan paling romantis yang pernah kalian nikmati bareng di mana?",
      "Perjalanan apa yang mengubah cara kalian melihat satu sama lain?",
      "Apa yang nggak bakal kamu coba sendirian tapi mau kalau bareng pasanganmu?",
      "Hal paling menakutkan apa yang bakal kalian lakuin kalau sekarang sama-sama bilang iya?",
      "Negara mana yang pengin kalian tinggali bareng selama setahun?",
      "Penemuan tak terduga terbaik yang kalian temuin waktu jalan-jalan apa?",
      "Petualangan apa yang pengin kamu alami sebelum terlalu tua buat menikmatinya?",
      "Kemping di bawah bintang atau hotel mewah — berdua?",
      "Hal nekat apa yang bakal bikin orang kaget kalau pasanganmu mau ngelakuinnya?",
      "Liburan bareng yang mana yang pengin kamu ulang persis sama?",
      "Petualangan apa yang bakal menguji kalian sebagai pasangan — dalam arti yang baik?",
      "Cara paling 'kalian banget' buat ngabisin hari libur dadakan gimana?",
      "Bucket list apa yang pengin kamu lakuin dengan pasanganmu ada di sana?",
      "Kapan kalian paling deg-degan waktu nyoba hal baru bareng?",
      "Petualangan apa yang worth it banget, berapa pun biayanya?",
      "Skill apa yang pengin kalian pelajari bareng cuma demi serunya?",
      "Perjalanan terjauh yang pernah kalian lakuin bareng ke mana?",
      "Petualangan apa yang bakal jadi cerita seru buat cucu-cucu kalian?",
      "Jalan mana yang dari dulu pengin kalian susuri aja, tanpa tujuan?",
      "Hal paling nggak biasa yang pernah dilakuin pasanganmu waktu jalan-jalan apa?",
      "Petualangan apa yang pengin kamu ulang persis kayak waktu itu?",
      "Ketakutan apa yang pengin kalian hadapi bareng sekali, biar bisa bilang pernah?",
      "Oleh-oleh terbaik dari liburan bareng apa, dan kenapa?",
      "Petualangan apa yang dari dulu diinginkan pasanganmu tapi belum pernah kamu tanyain?",
      "'Iya' paling nekat yang pernah kalian ucapin satu sama lain waktu liburan apa?",
      "Liburan apa yang selalu hampir kalian rencanain tapi nggak pernah dipesan?",
      "Tempat paling indah yang pernah kamu lihat bareng pasanganmu di mana?",
      "Petualangan apa yang ngajarin kamu hal baru soal pasanganmu?",
    ],
    friends: [
      "Liburan terbaik yang pernah kamu jalanin tanpa ada orang dari sini apa?",
      "Siapa di ruangan ini yang paling enak diajak jalan-jalan? Jujur.",
      "Tempat paling liar yang harus didatangi geng ini bareng di mana?",
      "Liburan santai menikmati pemandangan atau petualangan penuh aksi bareng geng ini?",
      "Kekacauan waktu liburan apa yang pernah dilewati geng ini dan sekarang bikin ketawa?",
      "Petualangan apa yang dibujuk seseorang di sini dan sekarang kamu syukuri?",
      "Pemandangan paling berkesan yang pernah dinikmati geng ini bareng di mana?",
      "Perjalanan apa yang mengubah caramu melihat seseorang di sini?",
      "Apa yang nggak bakal kamu coba sendirian tapi mau kalau bareng geng ini?",
      "Hal paling menakutkan apa yang bakal dilakuin geng ini kalau sekarang semua bilang iya?",
      "Negara mana yang harus ditinggali geng ini bareng selama satu musim?",
      "Penemuan tak terduga terbaik yang ditemuin geng ini waktu jalan-jalan apa?",
      "Petualangan apa yang pengin kamu alami bareng geng ini sebelum terlalu tua?",
      "Kemping di bawah bintang atau villa mewah — bareng geng ini?",
      "Hal nekat apa yang bakal bikin orang kaget kalau seseorang di sini mau ngelakuinnya?",
      "Liburan bareng geng yang mana yang pengin kamu ulang persis sama?",
      "Petualangan apa yang bakal menguji pertemanan ini — dalam arti yang baik?",
      "Cara paling 'geng ini banget' buat ngabisin hari libur dadakan gimana?",
      "Bucket list apa yang pengin kamu lakuin dengan seseorang di sini ada di sana?",
      "Kapan kamu paling deg-degan waktu nyoba hal baru bareng geng ini?",
      "Petualangan apa yang worth it banget, berapa pun biayanya?",
      "Skill apa yang harus dipelajari geng ini bareng cuma demi serunya?",
      "Perjalanan terjauh yang pernah dilakuin geng ini bareng ke mana?",
      "Petualangan apa yang bakal jadi cerita seru buat cucu-cucumu?",
      "Jalan mana yang dari dulu pengin disusuri geng ini, tanpa tujuan?",
      "Hal paling nggak biasa yang pernah dilakuin seseorang di sini waktu jalan-jalan apa?",
      "Petualangan apa yang pengin kamu ulang persis kayak waktu itu?",
      "Ketakutan apa yang pengin kamu hadapi bareng geng ini sekali, biar bisa bilang pernah?",
      "Oleh-oleh terbaik dari liburan bareng geng ini apa, dan kenapa?",
      "Petualangan apa yang dari dulu diinginkan seseorang di sini tapi belum ada yang nanya?",
      "'Iya' paling nekat yang pernah diucapin geng ini waktu liburan apa?",
      "Liburan apa yang selalu hampir direncanain geng ini tapi nggak pernah dipesan?",
      "Tempat paling indah yang pernah kamu lihat bareng orang-orang dari geng ini di mana?",
      "Petualangan apa yang ngajarin kamu hal baru soal seseorang di sini?",
    ],
  },
  everyday: {
    shared: [
      "Bagian terbaik dari hari biasa buatmu apa?",
      "Kopi atau tehmu biasanya kayak gimana?",
      "Cara favoritmu buang-buang waktu sejam itu ngapain?",
      "Apa yang paling sering ada di pikiranmu belakangan ini?",
      "Kerjaan rumah apa yang rela kamu bayar orang buat ngerjain selamanya?",
      "Apa yang paling kamu tunggu-tunggu di hari kerja biasa?",
      "Makanan andalanmu kalau lagi bete apa?",
      "Kamu sebenarnya pengin dibangunin dengan cara gimana?",
      "Hal terakhir yang bikin kamu ketawa ngakak apa?",
      "HP-mu nyuri waktu dari hal apa?",
      "Hal favoritmu yang kita lakuin dan gratis itu apa?",
      "Kamu sebenarnya lagi gimana? Bukan jawaban basa-basi.",
      "Kebiasaan kecilku yang mana yang bikin kamu kesel? Jujur — tapi baik-baik.",
      "Ritual kecil harian apa yang nggak bakal kamu tinggalin?",
      "Kerjaan membosankan apa yang anehnya bikin kamu puas?",
      "Hal sederhana apa yang langsung bikin mood kamu naik?",
      "Jujur, energimu sekarang berapa dari 10?",
      "Hal kecil nyebelin apa yang tiap hari selalu bikin kamu kesel?",
    ],
    couples: [
      "Kamu pengin disambut kayak gimana waktu aku pulang?",
      "Kamu tipe bangun pagi atau begadang?",
      "Malam biasa yang enak bareng itu kayak gimana?",
      "Kebiasaan kecil harian pasanganmu yang mana yang diam-diam kamu suka?",
      "Hal paling 'kayak pasangan yang udah lama nikah' yang kalian lakuin apa?",
      "Kebiasaan chatting pasanganmu yang mana yang nunjukin banget sifatnya?",
      "Kerjaan membosankan apa yang malah kamu nikmatin kalau bareng pasanganmu?",
      "Apa dari rutinitas pagi pasanganmu yang bikin kamu kaget?",
      "Kombinasi makanan apa yang dimakan pasanganmu yang nggak bakal kamu pahami?",
      "Momen biasa banget terakhir bareng pasanganmu yang kamu suka itu apa?",
      "Kerjaan rumah apa yang diam-diam kalian sepakat nggak usah dibahas?",
      "Kata-kata andalan pasanganmu apa — lucu atau nyebelin?",
      "Bagian mana dari rutinitas pasanganmu yang mulai kamu tiru?",
      "Gimana cara pasanganmu nyelesaiin masalah yang bikin kamu kagum?",
      "Apa yang kalian lakuin berulang-ulang tapi nggak pernah bosan?",
      "Kebiasaan pasanganmu yang mana yang butuh waktu buat dibiasain?",
      "Urusan sehari-hari apa yang paling 'kalian banget' kalau dikerjain bareng?",
      "Apa dari energi harian pasanganmu yang nular ke kamu?",
      "Kenyamanan kecil apa yang kalian bagi tiap hari?",
      "Hal aneh apa yang jadi normal sejak kalian bareng?",
      "Jawaban andalan pasanganmu kalau ditanya 'mau makan apa?' itu apa?",
      "Perdebatan kecil apa yang terus kalian ulang tapi nggak pernah serius?",
      "Kebiasaan pasanganmu main HP nunjukin apa soal dia?",
      "Hal paling bisa ditebak yang dilakuin pasanganmu tiap hari apa?",
      "Kebiasaan Minggu pagi apa yang kalian lakuin bareng?",
      "Hal kecil apa dari pasanganmu yang langsung kamu sadari kalau tiba-tiba berhenti?",
      "Cara paling sederhana kalian nunjukin sayang di hari biasa itu gimana?",
      "Urusan harian apa yang diam-diam jadi bagian favoritmu dalam sehari?",
      "Bagian mana dari rutinitas pasanganmu yang anehnya menurutmu menggemaskan?",
      "Apa yang diucapin pasanganmu baru-baru ini yang masih nempel di kepala?",
      "Kegiatan Selasa biasa apa yang bakal kamu pilih dibanding hal yang 'seru'?",
      "Apa dari ritme harianmu yang cuma jalan karena ada pasanganmu?",
      "Lelucon kecil apa yang hampir tiap hari kalian ucapin tanpa sadar?",
      "Hal biasa banget apa dari pasanganmu yang bakal kamu kangenin banget?",
    ],
    friends: [
      "Grup chat kita sebenarnya buat apa, sih?",
      "Siapa di sini yang paling lama bales chat, dan alasannya apa?",
      "Malam biasa yang enak bareng teman-teman itu kayak gimana buatmu?",
      "Kebiasaan kecil harian seseorang di sini yang mana yang diam-diam kamu suka?",
      "Hal paling 'kayak kakek-nenek' yang dilakuin geng ini apa?",
      "Kebiasaan chatting seseorang di sini yang mana yang nunjukin banget sifatnya?",
      "Kerjaan membosankan apa yang malah kamu nikmatin kalau bareng geng ini?",
      "Apa dari rutinitas pagi seseorang yang bikin kamu kaget?",
      "Kombinasi makanan apa yang dimakan seseorang di sini yang nggak bakal kamu pahami?",
      "Momen biasa banget terakhir bareng geng ini yang kamu suka itu apa?",
      "Kebiasaan geng apa yang diam-diam kita sepakat nggak usah dibahas?",
      "Kata-kata andalan seseorang apa — lucu atau nyebelin?",
      "Bagian mana dari rutinitas seseorang yang mulai kamu tiru?",
      "Gimana cara seseorang di sini nyelesaiin masalah yang bikin kamu kagum?",
      "Apa yang kalian lakuin berulang-ulang tapi nggak pernah bosan?",
      "Kebiasaan seseorang di sini yang mana yang butuh waktu buat dibiasain?",
      "Urusan sehari-hari apa yang paling 'geng ini banget' kalau dikerjain bareng?",
      "Energi harian siapa di sini yang nular ke kamu?",
      "Kenyamanan kecil apa yang sering dibagi geng ini?",
      "Hal aneh apa yang jadi normal sejak kamu kenal geng ini?",
      "Siapa yang selalu jawab 'terserah' waktu kita milih mau makan apa?",
      "Perdebatan kecil apa yang terus diulang geng ini tapi nggak pernah serius?",
      "Kebiasaan seseorang main HP nunjukin apa soal dia?",
      "Hal paling bisa ditebak yang dilakuin seseorang di sini tiap hari apa?",
      "Kebiasaan akhir pekan pagi apa yang dilakuin geng ini bareng?",
      "Hal kecil apa dari seseorang di sini yang langsung kamu sadari kalau tiba-tiba berhenti?",
      "Cara paling sederhana geng ini nunjukin peduli di hari biasa itu gimana?",
      "Urusan harian apa yang diam-diam jadi bagian favoritmu dalam sehari?",
      "Bagian mana dari rutinitas seseorang yang anehnya menurutmu menggemaskan?",
      "Apa yang diucapin seseorang di sini baru-baru ini yang masih nempel di kepala?",
      "Kegiatan hari kerja biasa apa yang bakal kamu pilih dibanding hal yang 'seru'?",
      "Apa dari ritme harianmu yang cuma jalan karena ada geng ini?",
      "Lelucon kecil apa yang hampir tiap hari diucapin geng ini tanpa sadar?",
      "Hal biasa banget apa dari seseorang di sini yang bakal kamu kangenin banget?",
    ],
  },
};
