// Indonesian question bank. Same shape as QUESTIONS in data.js, and every
// list is a line-for-line translation of the English one: same length, same
// order. That's what lets the language change mid-game — the used-question
// indexes a game keeps (state.usedQuestions) point at the same question in
// either language. If you add a question to one bank, add its twin here at
// the same position.
//
// Every line follows the owner's brief: "Tulis ulang teks ini pakai bahasa
// Indonesia yang santai, asyik dibaca, dan nggak kaku, kayak lagi ngobrol sama
// teman." Everyday spoken Indonesian ("kamu", "nggak", "bareng", -in verbs),
// never the formal register — friends chatting, not a survey.
// Like data.js, no module system: QUESTIONS_ID is a global script.js reads.
const QUESTIONS_ID = {
  general: {
    shared: [
      "Oke, satu skill apa yang wajib banget kita pelajarin bareng?",
      "Bulan ini enaknya kita maraton nonton apa bareng, nih?",
      "Kalau kita tukeran hidup sehari, hal pertama yang bakal kamu lakuin apa?",
      "Dari semua inside joke kita, mana yang paling kamu suka?",
      "Apa yang bikin kamu kaget soal aku waktu kita pertama kenal?",
      "Lagu apa yang 'kita banget' menurutmu?",
      "Makanan terenak yang pernah kita makan bareng — sebutin!",
      "Kebiasaanku yang mana yang udah kamu tiru tanpa sadar?",
      "Satu hal kecil apa yang bisa aku lakuin minggu ini biar kamu happy seharian?",
      "Kiamat zombie: siapa yang bakal bertahan paling lama, dan kenapa?",
      "Hal kecil apa yang langsung bikin mood kamu bagus?",
      "Kalau bisa ngulang satu hari yang biasa-biasa aja, kamu bakal pilih yang mana?",
      "Satu aturan hidup apa yang menurutmu wajib dipegang semua orang?",
      "Hal terakhir yang kamu pelajarin dan bikin kamu 'wah' itu apa?",
      "Kalau hari ini kamu dapet bonus satu jam, mau dipakai buat apa?",
      "Hal apa soal kamu yang selalu disalahpahamin orang?",
      "Pertanyaan apa yang kamu pengin lebih sering ditanyain orang?",
      "Saran terbaik yang malah kamu cuekin itu apa?",
    ],
    couples: [
      "Hal kecil apa dari pasanganmu yang selalu bikin kamu senyum?",
      "Kalau sekarang bisa kencan ke mana aja, kita ke mana?",
      "Apa yang menurutmu lucu banget tapi pasanganmu nggak nangkep?",
      "Kalau besok kita pelihara hewan, mau kita kasih nama apa?",
      "Kalau hidup kita jadi film, genrenya apa?",
      "Sudut favoritmu di rumah kita di mana?",
      "Kebiasaan pasanganmu yang mana yang nggak disangka malah bikin kamu jatuh hati?",
      "Apa yang sering kalian ributin, tapi sebenernya lucu juga?",
      "Aturan apa yang kalian punya yang orang lain nggak bakal ngerti?",
      "Kalau hubungan kita hari ini itu ramalan cuaca, bunyinya gimana?",
      "Sejak sama pasanganmu, hal apa yang sekarang kamu lakuin beda?",
      "Kerjaan rumah mana yang diam-diam udah kamu klaim jadi 'punyamu'?",
      "Apa yang pasanganmu lakuin belakangan ini yang masih kamu pikirin terus?",
      "Kalau pasanganmu jadi narator hidupmu, kalimat pembukanya apa?",
      "Makanan apa yang cuma pasanganmu yang bisa bujuk kamu buat nyoba?",
      "Tradisi kecil apa yang cuma kalian berdua yang punya?",
      "Menurut pasanganmu, kebiasaanmu yang paling nyebelin apa? Jujur, ya.",
      "Hal apa yang dulu bikin kalian beda pendapat, tapi sekarang malah sepakat banget?",
      "Hal paling aneh yang bikin kalian makin dekat itu apa?",
      "Kalau bisa bekuin satu momen biasa bareng pasanganmu, kamu pilih yang mana?",
      "Pujian apa buat pasanganmu yang selalu tulus tiap kali kamu bilang?",
      "Karakter TV siapa yang paling ngingetin kamu sama pasanganmu?",
      "Pasanganmu jago banget di hal apa, tapi dia sendiri nggak sadar?",
      "Hal paling 'kalian banget' yang pernah kalian lakuin apa?",
      "Kalau hubungan kita punya lagu tema, lagunya apa?",
      "Hal kecil nyebelin apa yang rela kamu terima selamanya demi pasanganmu?",
      "Apa yang belum pernah kamu bilang ke pasanganmu, padahal kayaknya perlu?",
      "Panggilan apa yang diam-diam kamu pakai buat pasanganmu dalam hati?",
      "Apa enaknya bener-bener nggak ngapa-ngapain bareng?",
      "Rencana apa yang terus kalian omongin tapi nggak pernah beneran jadi?",
      "Apa yang pasanganmu ajarin ke kamu tanpa dia sengaja?",
      "Minggu santai bareng yang paling kamu suka itu kayak gimana?",
      "Inside joke apa di antara kalian yang orang lain nggak pernah ngerti?",
      "Satu hal apa yang pengin kamu kasih tahu ke pasanganmu sebelum game ini selesai?",
    ],
    friends: [
      "Bakat paling nggak bergunamu apa? Tunjukin, dong.",
      "Kalau darurat, siapa di sini yang pertama kamu telepon, dan kenapa?",
      "Tontonan apa yang bakal kamu paksa semua orang di sini nonton?",
      "Kalau besok kita bikin band, siapa main apa?",
      "Gosip soal kamu yang ternyata beneran itu apa?",
      "Siapa di sini yang paling berubah sejak kamu kenal dia?",
      "Aturan apa di geng ini yang pasti dianggap aneh sama orang luar?",
      "Siapa di sini yang paling parah kasih arah jalan — dan kok kita masih ngikut?",
      "Rencana paling kacau apa yang beneran berhasil dijalanin geng ini?",
      "Kalau geng ini bikin nama grup chat, namanya apa?",
      "Makanan apa yang selalu bikin kita semua ribut?",
      "Siapa yang paling mungkin bales chat grup jam 3 pagi?",
      "Apa yang cuma pernah kamu ketawain bareng orang-orang di ruangan ini?",
      "Kalau kita semua ikut acara kuis bareng, acara apa?",
      "Jujur aja, siapa di sini yang selera musiknya paling parah?",
      "Tradisi apa yang harusnya beneran dibikin geng ini?",
      "Siapa yang diam-diam ditiru semua orang tapi nggak ada yang ngaku?",
      "Hal paling 'kita banget' yang pernah geng ini lakuin apa?",
      "Kalau ada film tentang geng ini, genrenya apa?",
      "Kebiasaan kecil siapa di sini yang selalu bikin kamu ngakak?",
      "Siapa di sini yang paling lama tahan tanpa HP?",
      "Siapa di sini yang butuh nama panggilan, dan enaknya apa?",
      "Motto nggak resmi geng ini apa?",
      "Siapa yang selalu telat, dan alasan andalannya apa?",
      "Bagian terbaik dari gabut bareng geng ini apa?",
      "Rencana apa yang terus kita omongin tapi nggak pernah beneran jadi?",
      "Siapa di sini yang ngajarin kamu sesuatu tanpa dia sadar?",
      "Cara favoritmu ngabisin hari mager bareng geng ini gimana?",
      "Candaan andalan apa di sini yang orang luar nggak bakal ngerti?",
      "Satu hal apa yang pengin kamu kasih tahu ke geng ini sebelum malam ini kelar?",
      "Siapa yang jadi tukang atur rencana di sini, suka nggak suka?",
      "Geng ini pernah kena masalah paling gede apa?",
      "Kalau geng ini punya maskot, apa maskotnya?",
      "Siapa yang jadi penengah kalau geng ini mulai ribut?",
    ],
  },
  love: {
    shared: [
      "Kalau lagi sedih, apa yang beneran bikin kamu ngerasa lebih baik?",
      "Apa yang belum pernah kamu ucapin, tapi kamu pengin aku tahu?",
      "Kasih pujian beneran ke salah satu orang di sini. Sekarang.",
      "Biasanya kita baikan abis berantem itu gimana?",
      "Satu hal apa yang kamu nggak mau kita berhenti lakuin bareng?",
      "Apa yang bikin kamu ngerasa disayang, yang kebanyakan orang nggak bakal nyangka?",
      "Cinta itu kayak gimana di hari Selasa yang biasa-biasa aja?",
      "Siapa yang nunjukin ke kamu cinta itu harusnya terasa kayak apa?",
      "Perhatian kecil yang manis apa yang nggak pernah bikin kamu bosan?",
      "Hal aneh apa yang kamu kaitin sama kata 'cinta'?",
      "Gimana kamu tahu seseorang beneran peduli, bukan cuma basa-basi?",
      "Bahasa cinta apa yang ternyata kamu punya, tapi baru kamu sadarin belakangan ini?",
      "Dicintai sama dimengerti itu beda nggak, sih? Bedanya di mana?",
      "Kapan terakhir kali kamu ngerasa disayang banget, tanpa perlu penjelasan apa-apa?",
      "Apa yang bikin kamu ngerasa agak nggak layak disayang, walau cuma sebentar?",
      "Cara kamu nunjukin sayang yang sering nggak disadari orang itu apa?",
      "Apa hal paling berani yang pernah kamu lakuin demi cinta?",
      "Buatmu, sayang sama seseorang di hari terburuknya itu kayak gimana?",
    ],
    couples: [
      "Apa yang awalnya bikin kamu jatuh hati sama pasanganmu?",
      "Gambarin pasanganmu dalam tiga kata — ucapin langsung.",
      "Hal kecil apa yang bikin kamu ngerasa paling disayang?",
      "Apa yang paling kamu suka dari cara pasanganmu nge-treat kamu?",
      "Kapan kamu ngerasa paling dekat sama pasanganmu?",
      "Satu janji apa yang pengin kalian bikin buat satu sama lain malam ini?",
      "Kapan kamu sadar kamu sayang sama aku?",
      "Apa hal terbaik dari kita sebagai pasangan?",
      "Sayang sama aku bikin kamu berubah gimana?",
      "Kalau cinta kita itu warna, warnanya apa dan kenapa?",
      "Rasanya disayang sama aku itu kayak gimana?",
      "Kapan kamu sadar hubungan ini beda dari yang lain?",
      "Menurutmu, pasanganmu perlu lebih sering denger kalimat apa?",
      "Hal paling romantis apa yang pernah pasanganmu lakuin, sekecil apa pun?",
      "Gimana cara pasanganmu bikin hari-hari berat jadi lebih ringan?",
      "Apa yang bikin kamu kaget dari rasanya sayang sama pasanganmu?",
      "Soal rasa sayangmu, hal apa yang nggak mau sampai diraguin pasanganmu?",
      "Ketakutan soal cinta apa yang udah pasanganmu bantu kamu lewatin?",
      "Gimana pandanganmu soal cinta berubah sejak bareng pasanganmu?",
      "Sisi lembut pasanganmu yang mana yang cuma kamu yang bisa lihat?",
      "Apa yang pasanganmu lakuin yang bikin kamu ngerasa dipilih?",
      "Gimana kalian nunjukin sayang tanpa ngomong sepatah kata pun?",
      "Kalau bisa ngulang satu hal dari caramu sayang sama pasanganmu, apa itu?",
      "Bagian mana dari kisah cinta kalian yang masih bikin kamu deg-degan?",
      "Hal paling berani apa yang pernah diminta cinta dari kamu di hubungan ini?",
      "Kalau lagi ada masalah, kamu pengin disayang dengan cara gimana?",
      "Cara diam-diam pasanganmu sayang sama kamu yang belum pernah kamu bahas itu apa?",
      "'Selamanya' itu artinya apa buatmu di hubungan ini?",
      "Apa yang kamu suka dari rasanya sayang sama pasanganmu — bukan cuma soal dia?",
      "Kapan pasanganmu sayang sama kamu apa adanya, lengkap sama kekuranganmu?",
      "Sepuluh tahun lagi, kamu pengin cinta kita terasa kayak gimana?",
      "Gimana pasanganmu sayang sama kamu lebih baik dari siapa pun sebelumnya?",
      "Apa yang kamu harap nggak pernah dilupain pasanganmu soal seberapa sayangnya kamu sama dia?",
      "Sayang sama pasanganmu ngajarin kamu apa soal dirimu sendiri?",
    ],
    friends: [
      "Kapan kamu mutusin kalau aku ini teman beneran, bukan cuma kenalan?",
      "Gambarin aku pakai tiga kata — ucapin langsung.",
      "Apa yang kamu butuhin dari teman tapi susah buat kamu minta?",
      "Kapan kamu ngerasa paling diperhatiin sama seseorang di sini?",
      "Apa yang kamu hargai dari aku yang mungkin aku nggak tahu?",
      "Menurutmu, teman yang baik itu yang kayak gimana?",
      "Siapa di sini yang kamu pengin ada di sampingmu pas hari terburukmu?",
      "Hal paling baik yang pernah seseorang di sini lakuin buat kamu apa?",
      "Kapan kamu sadar pertemanan ini beda dari yang lain?",
      "Menurutmu, aku perlu lebih sering denger kalimat apa?",
      "Hal paling baik apa yang pernah dilakuin seseorang di sini tanpa diminta?",
      "Gimana geng ini bikin hari-hari berat jadi lebih ringan?",
      "Apa yang bikin kamu kaget dari rasanya peduli sama orang-orang di sini?",
      "Soal kesetiaanmu, apa yang kamu nggak mau sampai diraguin orang-orang di sini?",
      "Ketakutan soal pertemanan apa yang udah berhasil kamu lewatin berkat seseorang di sini?",
      "Gimana pandanganmu soal teman yang baik berubah dari tahun ke tahun?",
      "Sisi lembutmu yang mana yang cuma bisa dilihat teman dekat?",
      "Apa yang dilakuin orang-orang di sini yang bikin kamu ngerasa dipilih?",
      "Gimana cara teman nunjukin kalau mereka peduli tanpa harus ngomong?",
      "Kalau bisa ngulang satu hal dari caramu ada buat teman, kamu pengin ngulang apa?",
      "Kenangan pertemanan apa yang masih bikin hatimu hangat?",
      "Hal paling berani apa yang pernah diminta pertemanan dari kamu?",
      "Kalau lagi ada masalah, kamu pengin teman-temanmu ada buat kamu kayak gimana?",
      "Cara diam-diam seseorang di sini peduli sama kamu yang belum pernah kamu bahas itu apa?",
      "'Susah senang bareng' itu artinya apa di geng ini?",
      "Apa yang kamu suka dari rasanya peduli sama orang — bukan cuma dari orangnya?",
      "Kapan seseorang di sini nerima kamu apa adanya, lengkap sama kekuranganmu?",
      "Sepuluh tahun lagi, kamu pengin pertemanan ini terasa kayak gimana?",
      "Gimana seseorang di sini ada buat kamu, lebih baik dari siapa pun sebelumnya?",
      "Apa yang kamu harap nggak pernah dilupain geng ini soal seberapa pedulinya kamu?",
      "Pertemanan ini ngajarin kamu apa soal dirimu sendiri?",
      "Siapa di sini yang kamu percaya buat nyimpen hal yang belum pernah kamu ceritain ke siapa pun?",
      "Gimana geng ini ngajarin kamu buat lebih sayang sama orang?",
      "Apa yang kamu hargai tapi belum pernah diucapin siapa pun di sini?",
    ],
  },
  money: {
    shared: [
      "Kebiasaan soal uang dari keluargamu mana yang mau kamu terusin, dan mana yang harus dibuang?",
      "Ngerasa aman soal uang itu kayak gimana buatmu?",
      "Besok kamu dapat uang banyak: ditabung, dibelanjain, atau dibagi?",
      "Hal seru apa yang rela kamu boros-borosin?",
      "Keputusan soal uang terbaik yang pernah kamu ambil apa?",
      "Obrolan soal uang apa yang terus kamu tunda-tunda?",
      "Skill apa yang beneran rela kamu bayar mahal buat dipelajarin?",
      "Barang mahal apa yang kamu beli dan nggak nyesel sama sekali?",
      "Buatmu, uang itu lebih soal kebebasan atau rasa aman?",
      "Kebiasaan soal uang apa yang kamu dapat dari ngelihat orang lain kesusahan?",
      "Sekarang ini, kamu mending punya lebih banyak waktu atau lebih banyak uang?",
      "Barang paling impulsif yang pernah kamu beli apa?",
      "Langganan apa yang terus pengin kamu berhentiin tapi belum juga?",
      "'Kaya' itu sebenernya artinya apa buatmu, selain angkanya?",
      "Pengeluaran apa yang nggak bakal kamu potong, apa pun yang terjadi?",
      "Pelajaran soal uang apa yang kamu dapat dari pengalaman pahit?",
      "Tajir tapi diam-diam, atau hidup nyaman yang kelihatan — pilih mana?",
      "Barang paling murah apa yang bikin kamu bahagia banget?",
    ],
    couples: [
      "Satu target soal uang apa yang harus kita pasang tahun ini?",
      "Kalau bulan ini kita dapet tambahan 5 juta, mau kita pakai buat apa?",
      "Kebiasaan pasanganmu soal uang yang mana yang sebenernya kamu suka?",
      "Jujur, gimana perasaanmu soal rencana tabungan kita?",
      "Hal gede apa yang harus mulai kita tabungin?",
      "Kita udah sepakat belum soal bagi-bagi tagihan?",
      "Pengeluaran apa yang bisa kita kurangin biar bisa nabung buat hal yang lebih gede?",
      "Lima tahun lagi, kondisi keuangan kita kamu bayangin kayak gimana?",
      "Kita udah cukup nabung buat seneng-seneng, atau terlalu mikirin nanti?",
      "Perlu nggak kita masing-masing punya uang jajan 'bebas tanpa ditanya'?",
      "Barang apa yang kamu beli yang sampai sekarang pasanganmu masih nggak ngerti?",
      "Kalau tiba-tiba ada pengeluaran gede, gimana kita ngadepinnya bareng?",
      "Urusan uang apa yang bikin kamu bangga karena berhasil kita beresin bareng?",
      "Soal uang, kita udah ngerasa satu tim belum, atau masih meraba-raba?",
      "Obrolan soal uang apa yang selama ini kita hindarin?",
      "Kalau besok semua uang kita digabung, apa yang bakal kamu lakuin beda?",
      "Barang mahal apa yang pengin banget kamu tabungin bareng sebagai pasangan?",
      "Gimana perasaanmu soal kado kejutan yang harganya lumayan?",
      "Reaksi jujur: aku beli barang mahal tanpa nanya kamu dulu?",
      "Kebiasaanku soal uang yang mana yang pengin kamu ubah pelan-pelan?",
      "Target uang bersama apa yang bakal bikin kamu bangga banget sama kita?",
      "Pensiun dini dan hidup sederhana, atau kerja lebih lama dan hidup mewah?",
      "Apa hal paling dermawan yang pernah kamu lihat aku lakuin pakai uang?",
      "Gimana kalau salah satu dari kita ternyata penghasilannya jauh lebih gede?",
      "Pengeluaran kita yang mana yang worth it banget?",
      "Apa yang bikin kamu khawatir soal uang yang mungkin belum aku tahu?",
      "Pencapaian soal uang apa yang harusnya kita rayain lebih heboh?",
      "Gimana kita mau ngajarin diri kita nanti — atau anak-anak — soal uang?",
      "Soal uang, apa yang rela kamu korbanin demi kita, tanpa mikir dua kali?",
      "Barang apa yang harusnya kita beli bareng, bukan sendiri-sendiri?",
      "Utang: harus dihindarin mati-matian, atau cuma alat biasa?",
      "Kebiasaan soal uang apa yang lagi kamu coba hilangin demi kita?",
      "Uang yang 'cukup' buat hidup kita bareng itu kayak gimana?",
      "Menurutmu, hal paling romantis yang pernah dilakuin orang pakai uang itu apa?",
    ],
    friends: [
      "Patungan bayar bill bareng teman: gampang, atau diam-diam agak canggung?",
      "Kamu mau minjemin uang ke teman nggak?",
      "Paling banyak kamu pernah ngabisin uang berapa buat hal yang orang lain nggak ngerti?",
      "Teman-temanmu kira-kira tahu nggak penghasilanmu berapa?",
      "Kalau besok ada uang jatuh dari langit, kita liburan ke mana?",
      "Waktu umur 20, kamu buang-buang uang buat apa yang sekarang nggak bakal kamu beli lagi?",
      "Kamu pernah beli apa yang sampai sekarang teman-temanmu masih nggak ngerti?",
      "Kamu ngerasa gimana kalau ada teman yang tiba-tiba jauh lebih kaya dari kamu?",
      "Soal uang, apa yang kamu bangga bisa beresin sendiri?",
      "Obrolan soal uang apa yang pernah kamu hindarin sama teman?",
      "Kamu mau nggak minjemin uang dalam jumlah gede ke salah satu orang di ruangan ini?",
      "Kamu pengin nabung bareng orang-orang di sini buat beli barang mahal apa?",
      "Patungan kado bareng-bareng — suka banget atau males banget?",
      "Reaksi jujurmu gimana waktu teman beli barang mahal yang kamu sendiri nggak bakal beli?",
      "Kebiasaan ngatur uang siapa di antara teman-temanmu yang pengin kamu ubah pelan-pelan?",
      "Target bareng geng ini apa yang butuh modal beneran buat diwujudin?",
      "Pensiun dini terus hidup sederhana, atau kerja lebih lama tapi hidup mewah?",
      "Hal paling dermawan soal uang yang pernah kamu lihat dilakuin orang di sini apa?",
      "Enaknya gimana kalau ada satu teman yang penghasilannya jauh lebih gede dari yang lain?",
      "Geng ini ngeluarin uang buat apa yang worth it banget?",
      "Kamu punya kekhawatiran soal uang apa yang mungkin orang-orang di sini belum tahu?",
      "Pencapaian soal uangmu yang mana yang harusnya dirayain lebih heboh?",
      "Soal uang, apa yang rela kamu korbanin buat teman, tanpa banyak tanya?",
      "Barang apa yang cuma bakal kamu beli kalau dibujuk sama orang di sini?",
      "Utang: pokoknya harus dihindarin, atau ya alat biasa aja?",
      "Kebiasaan soal uang apa yang sekarang lagi kamu coba hilangin?",
      "Uang yang 'cukup' buat hidupmu itu kayak gimana?",
      "Kado paling royal yang pernah kamu kasih ke orang di ruangan ini apa?",
      "Siapa di sini yang paling mungkin jadi kaya, dan caranya gimana?",
      "Kesalahan soal uang apa yang bakal kamu wanti-wanti ke semua orang di sini?",
      "Semua orang di sini tahu gajimu, atau nggak ada yang bakal tahu selamanya — pilih salah satu.",
      "Hal gratisan paling seru yang pernah geng ini lakuin apa?",
      "Foya-foya apa yang cuma bakal kamu anggap wajar kalau bareng geng ini?",
      "Kalau geng ini bikin usaha, siapa yang pegang uangnya?",
    ],
  },
  dreams: {
    shared: [
      "Skill apa yang pengin banget kamu jagoin sebelum umur 60?",
      "Kalau uang bukan masalah, tahun depan mau kamu habisin gimana?",
      "Hari Selasa yang sempurna tapi biasa aja itu kayak gimana buatmu?",
      "Mimpi apa yang dulu kamu lepasin dan pengin kamu kejar lagi?",
      "Petualangan apa yang belum pernah kita coba, padahal kamu pengin banget?",
      "Kalau kita bisa tinggal setahun di negara lain, di mana dan kenapa?",
      "Ada apa di daftarmu yang harus kita lakuin bareng tahun ini?",
      "Kalau kita bikin usaha bareng, usaha apa?",
      "Mimpi apa yang belum pernah kamu ceritain ke siapa pun?",
      "Kalau bisa jago satu skill dalam semalam, kamu pilih apa?",
      "Versi dirimu di masa depan yang bikin kamu excited itu kayak gimana?",
      "Apa yang bakal bikin kamu nyesel kalau nggak pernah dicoba?",
      "Kalau seharian kamu super berani, mau ngapain?",
      "Mimpi apa yang bikin kamu agak takut justru karena itu penting banget?",
      "Bucket list apa yang beneran bisa kamu wujudin tahun ini?",
      "Apa yang bakal kamu lakuin kalau nggak takut gagal?",
      "Mimpi masa kecil apa yang diam-diam masih penting buatmu?",
      "Kalau sukses udah pasti, apa yang akhirnya bakal kamu kejar?",
    ],
    couples: [
      "Kamu pengin kita liburan impian ke mana suatu hari nanti?",
      "Sepuluh tahun lagi, kamu bayangin kita tinggal di mana?",
      "Hidup impianmu bareng pasanganmu itu kayak gimana?",
      "Tradisi apa yang harus kita mulai sebagai pasangan?",
      "Apa yang kamu harap nggak pernah berubah dari kita?",
      "Target apa yang lagi kamu kejar dan pengin dibantu pasanganmu?",
      "Kamu pengin kita jadi pasangan tua yang kayak gimana?",
      "Tiga puluh tahun lagi, kamu pengin orang ngomong apa soal kita?",
      "Mimpi apa yang belum sepenuhnya kamu ceritain ke pasanganmu?",
      "Gimana pasanganmu bisa dukung target yang lagi kamu kejar sekarang?",
      "Apa yang kamu mimpiin buat kita bangun bareng, bukan cuma buat dirasain?",
      "Kalau kita desain rumah impian dari nol, apa yang wajib ada?",
      "Versi 'kita' sepuluh tahun lagi yang paling bikin kamu semangat itu kayak gimana?",
      "Mimpi apa yang pernah kamu lepas, yang bisa pasanganmu bantu kejar lagi?",
      "Kamu pengin kita berdua ninggalin jejak apa?",
      "Kamu pengin kita nyapai apa bareng sebelum umur tertentu?",
      "Mimpi kita berdua yang mana yang sekarang rasanya masih agak jauh?",
      "Realistisnya, kamu pengin kita tua bareng kayak gimana?",
      "Mimpi pasanganmu yang mana yang pengin banget kamu bantu wujudin?",
      "Kalau nggak mungkin gagal, risiko apa yang bakal kita ambil bareng?",
      "Pensiun idealmu bareng pasanganmu itu kayak gimana?",
      "Skill apa yang kamu pengin kalian berdua pelajari bareng?",
      "Kamu mimpiin kita punya rumah bareng di mana suatu hari nanti?",
      "Apa soal masa depan kita yang belum pernah kamu bilang terang-terangan?",
      "Rangkum mimpi kita berdua dalam satu kalimat.",
      "Target pasanganmu yang mana yang paling kamu dukung diam-diam?",
      "Mimpi apa buat hubungan ini yang belum berani kamu bilang?",
      "Kalau uang sama waktu nggak jadi masalah, kita bakal bangun apa bareng?",
      "Petualangan kayak gimana yang pengin kamu jalanin bareng pasanganmu?",
      "Kalau kamu lagi lupa sama mimpimu, pasanganmu harus ngingetin kamu kayak gimana?",
      "Dua puluh tahun lagi, kamu harap kita masih mimpiin apa bareng?",
      "Mimpi apa yang sebenarnya kamu pengin tapi takut buat diakui?",
      "Janji apa soal masa depan kita yang bakal kamu bikin sekarang juga?",
      "Satu hal apa yang harus kita lakuin bareng sebelum telat?",
    ],
    friends: [
      "Sepuluh tahun lagi kamu pengin tinggal di mana — dan siapa aja yang tinggal deket kamu?",
      "Liburan ke mana yang harusnya beneran di-booking geng ini, bukan cuma jadi wacana?",
      "Kamu pengin dikenal karena apa sama orang-orang yang kenal kamu?",
      "Target apa yang lagi kamu kejar dan bisa dibantu sama orang di sini?",
      "Nanti pas udah tua, kamu pengin jadi orang yang kayak gimana?",
      "Tradisi apa yang harusnya mulai dibikin geng ini?",
      "Apa yang kamu harap nggak pernah berubah dari teman-temanmu?",
      "Mimpi apa yang belum sepenuhnya kamu ceritain ke siapa pun di sini?",
      "Gimana caranya geng ini bisa dukung target yang lagi kamu kejar sekarang?",
      "Apa yang pengin kamu bangun bareng orang-orang di sini, bukan cuma dijalanin?",
      "Kalau geng ini bikin proyek dari nol, bakal bikin apa?",
      "Kamu paling semangat ngebayangin geng ini sepuluh tahun lagi jadi kayak gimana?",
      "Mimpi apa yang udah kamu lepas, yang bisa dibantu orang di sini biar kamu kejar lagi?",
      "Kamu pengin geng ini ninggalin jejak apa?",
      "Apa yang pengin kamu capai sebelum umur tertentu, sambil disorakin geng ini?",
      "Mimpi bareng geng ini apa yang sekarang rasanya masih agak jauh buat digapai?",
      "Gimana caranya kamu pengin tetap dekat sama geng ini pas makin tua nanti?",
      "Mimpi siapa di sini yang pengin banget kamu bantu wujudin?",
      "Kalau gagal itu nggak mungkin, risiko apa yang bakal kamu ambil bareng geng ini?",
      "Reuni ideal kamu sama geng ini 20 tahun lagi tuh kayak gimana?",
      "Kamu pengin geng ini belajar skill apa bareng-bareng?",
      "Suatu hari nanti, kamu pengin ngumpulin satu geng ini di mana?",
      "Hal apa soal masa depanmu yang belum pernah kamu ceritain ke siapa pun di sini?",
      "Rangkum mimpi terbesarmu dalam satu kalimat aja.",
      "Target siapa di sini yang diam-diam paling kamu dukung?",
      "Mimpi apa buat pertemanan ini yang belum berani kamu ucapin?",
      "Kalau duit dan waktu nggak jadi masalah, kamu bakal bangun apa bareng geng ini?",
      "Petualangan kayak gimana yang pengin kamu jalanin bareng orang-orang di sini?",
      "Kalau kamu lagi lupa sama mimpimu, geng ini harus ngingetin kamu kayak gimana?",
      "Dua puluh tahun lagi, kamu berharap masih ngapain aja bareng geng ini?",
      "Mimpi apa yang sebenarnya kamu pengin, tapi takut buat ngakuin?",
      "Janji apa soal masa depan yang bakal kamu bikin ke geng ini sekarang juga?",
      "Satu hal apa yang wajib kamu lakuin bareng geng ini sebelum telat?",
      "Mimpi siapa di sini yang pantas dapat dukungan jauh lebih banyak dari sekarang?",
    ],
  },
  dare: {
    shared: [
      "Selfie paling konyol bareng. Sekarang juga.",
      "Tukeran HP, terus gantiin wallpaper HP satu sama lain.",
      "Nyanyiin reff lagu yang semua orang di sini tahu.",
      "Ngomong 30 detik soal hal yang kamu suka. Nggak boleh 'eee'.",
      "Ngomong pakai logat daerah sampai giliranmu berikutnya.",
      "Keluarin jurus joget terbaikmu selama 10 detik. Nggak pakai alasan.",
      "Sebutin alfabet dari belakang. Semua lagi ngeliatin, nih.",
      "Biarin yang lain kasih kamu julukan konyol sampai game selesai.",
      "Coba jilat sikumu sendiri. Coba aja.",
      "Tiruin gaya artis sampai ada yang bisa nebak siapa.",
      "Taruh sesuatu di atas kepala, jaga biar nggak jatuh selama 15 detik.",
      "Kirim emoji random ke orang terakhir yang kamu chat. Nggak pakai jelasin.",
      "Plank 20 detik sambil ngelawak.",
      "Biarin orang lain nata rambutmu buat ronde berikutnya.",
      "Cuma boleh ngomong pakai kalimat tanya sampai giliranmu berikutnya.",
      "Peragain gimana kamu bangun tidur tadi pagi.",
      "Tunjukin foto paling aneh di galerimu.",
      "Diem di pose dramatis selama 10 detik. Nggak boleh ketawa.",
    ],
    couples: [
      "Peluk pasanganmu 10 detik. Sekarang juga.",
      "Tiruin gaya pasanganmu semirip mungkin.",
      "Bilang 'aku sayang kamu' pakai logat yang paling konyol.",
      "Bisikin sesuatu yang manis di telinga pasanganmu.",
      "Dansa pelan 15 detik. Musik boleh ada, boleh nggak.",
      "Suapin pasanganmu camilan atau kasih dia seteguk minumanmu.",
      "Peragain gimana kalian pertama ketemu, kayak adegan film.",
      "Pegangan tangan terus saling tatap 20 detik. Jangan ketawa.",
      "Puji pasanganmu cuma pakai gerakan tangan. Nggak boleh ngomong.",
      "Pijitin bahu pasanganmu 30 detik.",
      "Bikin pasanganmu ketawa dalam 15 detik tanpa nyentuh dia.",
      "Nyanyiin reff lagu 'kalian' bareng-bareng.",
      "Gambarin sesuatu di telapak tangan pasanganmu pakai jari. Dia yang nebak.",
      "Sebutin tiga hal yang kamu suka dari pasanganmu — nggak boleh ada kata yang diulang.",
      "Bikin ulang foto pertama kalian berdua, lengkap sama posenya.",
      "Tulisin nama pasanganmu di punggungnya pakai jari. Dia harus nebak.",
      "Kasih pasanganmu julukan berdasarkan kelakuannya hari ini.",
      "Ceritain ke pasanganmu momen persis waktu kamu sadar pengin jadian sama dia.",
      "Peragain ulang momen kalian pertama ketemu versi slow-mo, 10 detik.",
      "Biarin pasanganmu milihin baju kamu buat besok, nggak boleh protes.",
      "Nyanyiin lagu paling jelek yang kepikiran buat pasanganmu. Pasang muka datar.",
      "Tatap mata pasanganmu terus bilang satu hal yang kamu suka banget dari dia.",
      "Gambarin hati di tanganmu terus 'kasih' ke pasanganmu.",
      "Bisikin kenangan favoritmu soal pasanganmu di telinganya.",
      "Peragain rutinitas pagi pasanganmu — lebayin aja.",
      "Tatap mata pasanganmu tiga detik, terus cium tangannya.",
      "Tebak keras-keras apa yang lagi dipikirin pasanganmu sekarang.",
      "Bilang ke pasanganmu satu hal lucu, satu hal seksi, dan satu hal yang bikin kamu ngerasa 'pulang' dari dia.",
      "Tiruin ekspresi muka khas pasanganmu.",
      "Kasih pasanganmu pidato yang tulus, kayak di acara nikahan.",
      "Biarin pasanganmu milih topik pertanyaan berikutnya buat kalian berdua.",
      "Tiruin ketawa pasanganmu semirip mungkin.",
      "Pegangan tangan, terus gambarin tangan pasanganmu. Yang manis, ya.",
      "Bilang ke pasanganmu apa yang paling bakal kamu kangenin dari dia kalau pisah seminggu.",
    ],
    friends: [
      "Tiruin salah satu orang di ruangan ini, semirip mungkin.",
      "Tunjukin foto terakhir di galerimu terus jelasin.",
      "Sebutin tiga hal tulus soal pemain di sebelah kananmu. Nggak boleh diulang.",
      "Bacain pesan terakhir yang kamu kirim keras-keras, sedramatis mungkin.",
      "Push-up 10 kali atau ceritain pengalaman yang malu-maluin. Pilih sekarang.",
      "Biarin salah satu orang di sini milih lagu berikutnya. Nggak boleh protes.",
      "Bikin satu geng ketawa dalam 15 detik tanpa ngomong apa-apa.",
      "Biarin pemain di sebelah kirimu ngasih julukan baru buatmu sampai game selesai.",
      "Peragain gimana kamu pertama kenal pemain di sebelah kananmu, dilebay-lebayin ya.",
      "Tebak apa yang terakhir dicari salah satu orang di sini di HP-nya.",
      "Kasih pemain di depanmu julukan dari kejadian malam ini.",
      "Peragain gimana reaksi salah satu orang di sini kalau lagi kalah.",
      "Ceritain ke geng alasan sebenarnya kamu telat terakhir kali.",
      "Biarin geng milihin foto profilmu selama seminggu.",
      "Tiruin si paling drama di geng ini, semaksimal mungkin.",
      "Tebak persis gimana reaksi salah satu orang kalau kamu ceritain rahasia ke dia sekarang.",
      "Gambarin orang di depanmu dalam 15 detik.",
      "Bisikin hal paling manis yang kepikiran ke orang di sebelah kirimu.",
      "Peragain gimana salah satu orang di sini mesen makanan di restoran.",
      "Kasih toast yang tulus buat geng ini, kayak lagi reunian.",
      "Tebak keras-keras apa yang lagi dipikirin salah satu orang di sini sekarang.",
      "Ceritain satu hal soal kamu yang nggak bakal ketebak sama geng ini.",
      "Tiruin kata-kata andalan seseorang, sepersis mungkin.",
      "Biarin geng milihin julukanmu sampai malam ini selesai.",
      "Tiruin ketawa paling heboh dari salah satu orang di ruangan ini.",
      "Sodorin tanganmu terus biarin salah satu orang di sini 'ngeramal' garis tanganmu. Asal-asalan aja.",
      "Bilang ke geng apa yang paling bakal kamu kangenin dari mereka kalau pisah sebulan.",
      "Pilih satu orang terus sebutin kata pertama yang muncul di kepalamu soal dia.",
      "Tiruin dirimu sendiri sejelek mungkin.",
      "Biarin salah satu orang di sini jawabin pertanyaanmu berikutnya.",
      "Tunjukin galeri fotomu dari 24 jam terakhir ke geng.",
      "Kasih toast satu kalimat buat orang di sebelah kananmu.",
      "Peragain adu mulut terakhirmu sama siapa aja, dibikin lucu.",
      "Biarin geng voting julukan baru buatmu. Nggak boleh nolak.",
    ],
  },
  deep: {
    shared: [
      "'Rumah' itu sebenarnya artinya apa buatmu?",
      "Bagian mana dari dirimu yang masih kamu perbaiki?",
      "Kalau lagi stres, kamu sebenarnya pengin dibantu kayak gimana?",
      "Maafin seseorang itu artinya apa buatmu?",
      "Kalau kamu bikin salah, kamu pengin orang nyikapin kamu kayak gimana?",
      "Apa yang lagi berat buatmu belakangan ini?",
      "Apa yang pengin kamu ingat dari fase hidupmu yang sekarang?",
      "Kapan terakhir kali kamu ngerasa beneran dimengerti?",
      "Beban apa yang kamu bawa tapi nggak ada yang tahu?",
      "Rasa tenang itu kerasa kayak apa di badanmu?",
      "Anggapan apa soal dirimu yang lagi kamu coba lepasin?",
      "Kapan kamu ngerasa paling jadi dirimu sendiri?",
      "Waktu kecil, kamu sebenarnya butuh dengar apa, tapi nggak pernah ada yang bilang?",
      "Ketakutan apa yang belum pernah kamu omongin?",
      "Percaya sepenuhnya sama seseorang itu artinya apa buatmu?",
      "Apa yang lagi diam-diam bikin kamu berduka sekarang?",
      "Kamu pengin orang ngerti apa soal cara kerja pikiranmu?",
      "Momen apa yang ngubah caramu ngelihat dirimu sendiri?",
    ],
    couples: [
      "Apa yang lagi berat buat kamu belakangan ini yang bisa aku bantu?",
      "Ada yang kamu khawatirin nggak soal kita?",
      "Belakangan ini kamu butuh apa lebih banyak dari aku?",
      "Gimana kamu berkembang sejak kita jadian?",
      "Ada hal yang belum pernah kita omongin yang pengin kamu bahas?",
      "Bareng aku, kamu jadi belajar apa soal cinta?",
      "Apa yang kamu takut minta dari aku?",
      "Apa dari masa lalumu yang masih ngebentuk caramu mencintai?",
      "Kalau suatu saat kita berantem parah banget, apa yang harus aku inget?",
      "Bagian dirimu yang mana yang cuma pernah kamu tunjukin ke pasanganmu?",
      "Apa yang kamu takut hilang dari hubungan ini?",
      "Gimana pasanganmu bantu kamu lebih ngerti dirimu sendiri?",
      "Luka lama apa dari sebelum ada kita yang kadang masih suka muncul?",
      "Di hari terburukmu, kamu butuh apa dari aku?",
      "Apa yang udah kamu maafin dari aku tapi nggak pernah kita bahas?",
      "Ngerasa aman sama aku itu sebenarnya rasanya kayak gimana?",
      "Apa soal dirimu yang masih takut kamu ceritain ke aku?",
      "Kalau kamu lagi berduka, kamu pengin aku nemenin kamu kayak gimana?",
      "Apa soal cinta yang sampai sekarang masih bikin kamu takut?",
      "Bagian dirimu yang mana yang menurutmu masih belum aku pahami sepenuhnya?",
      "Momen bareng aku yang mana yang ngubah caramu ngelihat dirimu sendiri?",
      "Kamu butuh dengar apa dari aku yang jarang aku bilang?",
      "Apa yang kamu bangga bisa lewatin, berkat bantuanku?",
      "Buatmu, ngerasa bener-bener dikenal sama seseorang itu artinya apa?",
      "Sisi dirimu yang mana yang kamu takut suatu saat bakal aku lihat?",
      "Apa yang kamu harap aku ngerti soal isi kepalamu waktu kita lagi berantem?",
      "Apa yang kamu butuhin dari pasangan tapi lama banget baru berani kamu minta?",
      "Kalau kata-kata nggak ngebantu, kamu pengin dihibur kayak gimana?",
      "Ketakutan apa soal masa depan kita yang belum pernah kamu omongin?",
      "'Tanpa syarat' itu wujudnya kayak gimana sehari-hari?",
      "Luka apa yang masih dalam proses sembuh dan kebawa ke caramu mencintai?",
      "Apa yang kamu pengin terus aku perjuangin tanpa nyerah, bahkan pas lagi susah?",
      "Kapan aku bikin kamu ngerasa paling aman?",
      "Hal apa soal kamu yang cuma aku yang bener-bener tahu?",
    ],
    friends: [
      "Ada yang belum sempat diomongin antara kamu sama seseorang di sini?",
      "Akhir-akhir ini kamu butuh lebih banyak apa dari teman-temanmu?",
      "Kamu takut minta apa ke orang lain?",
      "Kamu udah berubah kayak gimana sejak geng ini kenal kamu?",
      "Pertemanan apa yang udah hilang tapi masih suka kamu pikirin?",
      "Apa yang paling susah buat kamu ucapin langsung?",
      "Kapan kamu ngerasa kesepian padahal lagi rame?",
      "Kalau ada yang di sini bikin kamu kesel, dia harus ngapain?",
      "Bagian dirimu yang mana yang cuma kamu tunjukin ke teman dekat?",
      "Kamu takut kehilangan apa dari pertemanan ini?",
      "Gimana pertemanan ini bantu kamu lebih ngerti diri sendiri?",
      "Luka lama apa dari sebelum kenal geng ini yang kadang masih suka muncul?",
      "Di hari terburukmu, kamu butuh apa dari teman?",
      "Apa yang udah kamu maafin dari seseorang di sini tapi nggak pernah dibahas?",
      "Ngerasa aman sama orang-orang di sini tuh sebenernya rasanya kayak gimana?",
      "Apa soal dirimu yang masih takut kamu ceritain ke geng ini?",
      "Kalau kamu lagi berduka, kamu pengin orang-orang di sini ada buat kamu kayak gimana?",
      "Apa soal pertemanan yang sampai sekarang masih bikin kamu takut?",
      "Menurutmu, bagian dirimu yang mana yang belum bener-bener dingertiin geng ini?",
      "Momen apa bareng seseorang di sini yang ngubah caramu mandang diri sendiri?",
      "Kalimat apa yang kamu butuh denger dari geng ini tapi jarang diucapin?",
      "Apa yang kamu bangga bisa lewatin berkat bantuan seseorang di sini?",
      "Ngerasa bener-bener dikenal sama teman itu artinya apa buatmu?",
      "Sisi dirimu yang mana yang kamu takut suatu saat bakal dilihat geng ini?",
      "Kamu pengin geng ini ngerti apa soal isi kepalamu waktu lagi ribut?",
      "Apa yang kamu butuhin dari teman tapi lama baru berani kamu minta?",
      "Kalau kata-kata nggak ngebantu, kamu pengin dihibur kayak gimana?",
      "Ketakutan soal masa depan pertemanan ini yang belum pernah kamu ucapin itu apa?",
      "Dukungan tanpa syarat itu wujudnya kayak gimana sehari-hari?",
      "Luka apa yang masih lagi kamu sembuhin dan kebawa ke caramu berteman?",
      "Kamu pengin geng ini nggak pernah nyerah soal apa, bahkan pas lagi susah?",
      "Kapan seseorang di sini bikin kamu ngerasa paling aman?",
      "Hal apa soal kamu yang cuma teman dekat yang bener-bener tahu?",
      "Masa berat apa yang bisa kamu lewatin berkat seseorang di sini, tanpa dia sadar?",
    ],
  },
  memories: {
    shared: [
      "Hal paling spontan yang pernah kita lakuin bareng apa?",
      "Waktu pertama kali banget lihat aku, kamu mikir apa?",
      "Momen kecil dan biasa bareng aku yang mana yang masih kamu ingat?",
      "Trip kita yang mana yang masih suka kamu pikirin?",
      "Perayaan kita yang paling seru sepanjang masa yang mana?",
      "Apa yang dulu sering kita lakuin dan harus banget dihidupin lagi?",
      "Cerita soal kita yang paling kamu suka ceritain ke orang apa?",
      "Momen bareng aku yang mana yang pengin banget kamu ulang?",
      "Hal paling awal yang kamu ingat soal aku apa?",
      "Kenangan apa yang masih bikin kamu ngakak tiap kali ingat?",
      "Bau atau suara apa yang langsung bikin kamu keinget kenangan kita?",
      "Foto kita yang mana yang paling 'kita banget', dan kenapa?",
      "Kenangan apa yang baru kerasa spesial belakangan?",
      "Apa yang pernah kita lakuin sekali dan nggak pernah dibahas lagi?",
      "Kenangan kita yang mana yang bakal bikin kaget orang yang baru kenal kita sekarang?",
      "Hal terakhir yang pengin kamu pikirin sebelum tidur malam ini apa?",
      "Kenangan soal aku apa yang sebenernya belum pernah kamu ceritain ke aku?",
      "Masa-masa kita bareng yang mana yang pengin kamu ulang persis kayak dulu?",
    ],
    couples: [
      "Kenangan favoritmu dari beberapa bulan pertama kita apa?",
      "Foto favoritmu dari kita berdua yang mana?",
      "Ceritain kencan pertama kita — versimu.",
      "Hal paling berat yang pernah kita lewatin apa?",
      "Berantem paling lucu yang pernah kita alamin apa?",
      "Kado dari aku yang mana yang paling berarti buatmu?",
      "Kapan pertama kali kamu ngerasa kita beneran satu tim?",
      "Hal pertama yang kamu ceritain ke teman-temanmu soal aku apa?",
      "Kapan hubungan ini pertama kali kerasa serius?",
      "Berantem yang mana yang sekarang bisa kamu ketawain?",
      "Kapan kamu paling deg-degan di depan pasanganmu?",
      "Kenangan soal pasanganmu yang belum pernah kamu ceritain ke siapa pun apa?",
      "Kejutan terbaik yang pernah pasanganmu kasih apa?",
      "Kapan pasanganmu ngebuktiin kalau dia beneran kenal kamu?",
      "Hal paling konyol yang pernah kalian ributin apa?",
      "Masa sulit apa yang bikin kamu makin sayang sama pasanganmu?",
      "Hal paling spontan yang pernah kalian lakuin apa?",
      "Kenangan soal keluarga pasanganmu yang mana yang masih kamu inget terus?",
      "Pujian pertama yang pernah pasanganmu kasih apa?",
      "Kenangan apa yang masih bikin kamu deg-degan sampai sekarang?",
      "Momen 'ini dia orangnya' yang paling kerasa sama pasanganmu kapan?",
      "Apa yang kamu inget waktu kalian siap-siap mau kencan bareng?",
      "Kejadian apes paling lucu waktu jalan-jalan bareng apa?",
      "Kapan kalian saling ngehibur dengan cara yang bikin kamu bangga?",
      "Kapan kamu tahu teman-teman pasanganmu suka sama kamu?",
      "Apa yang kamu inget waktu ketemu keluarga pasanganmu?",
      "Hari 'biasa aja' terbaik yang pernah kalian lewatin bareng apa?",
      "Kenangan apa yang masih kerasa kayak adegan film?",
      "Kapan kamu sadar kamu bakal milih pasanganmu lagi dan lagi?",
      "Kapan pasanganmu bikin kamu kaget karena dia kenal kamu banget?",
      "Momen ngasih kado favoritmu di antara kalian berdua yang mana?",
      "Kenangan apa yang kamu nggak mau sampai lupa?",
      "Kenangan apa yang paling ngegambarin kenapa kamu sayang pasanganmu?",
      "Kenangan apa yang detailnya masih kalian debatin sampai sekarang?",
    ],
    friends: [
      "Kenangan favoritmu sama seseorang di ruangan ini apa?",
      "Ceritain gimana kamu kenalan sama seseorang di sini — versi kamu.",
      "Kejadian paling lucu yang pernah dialami geng ini apa?",
      "Ide paling parah yang kita semua iyain apa?",
      "Foto kita yang mana yang nggak bakal pernah kamu hapus?",
      "Kapan pertama kali kamu ngerasa beneran jadi bagian geng ini?",
      "Dulu kamu mikir aku orangnya kayak gimana sebelum beneran kenal?",
      "Malam mana yang harusnya nggak bisa kita lewatin hidup-hidup?",
      "Kapan pertama kali kamu ngerasa pertemanan ini bakal awet?",
      "Berantem yang mana yang sekarang bisa kamu ketawain?",
      "Kapan kamu paling deg-degan pas ketemu seseorang di sini?",
      "Kenangan apa soal seseorang di sini yang belum pernah kamu ceritain ke siapa-siapa?",
      "Kejutan terbaik yang pernah dibikin seseorang di sini apa?",
      "Kapan seseorang di sini ngebuktiin dia beneran kenal kamu?",
      "Hal paling konyol yang pernah diributin geng ini apa?",
      "Masa-masa sulit apa yang bikin kamu makin ngehargain geng ini?",
      "Hal paling spontan yang pernah dilakuin geng ini apa?",
      "Kenangan apa soal keluarga seseorang yang masih nempel di ingatanmu?",
      "Pujian pertama yang pernah kamu dapet dari seseorang di sini apa?",
      "Kenangan apa yang masih bikin kamu senyum-senyum?",
      "Apa momen paling 'ini baru teman sejati' yang pernah kamu alamin bareng geng ini?",
      "Apa yang kamu inget soal siap-siap bareng sebelum keluar malam?",
      "Kejadian apes paling lucu pas jalan-jalan bareng geng ini apa?",
      "Kapan kalian saling ngehibur dengan cara yang bikin kamu bangga?",
      "Kapan kamu tahu kamu beneran cocok di sini?",
      "Apa yang kamu inget pas pertama kali ketemu keluarga seseorang di sini?",
      "Hari 'biasa aja' terbaik yang pernah kamu lewatin bareng geng ini apa?",
      "Kenangan apa yang masih kerasa kayak adegan film?",
      "Kapan kamu sadar kamu bakal tetap milih pertemanan ini kalau diulang dari awal?",
      "Kapan seseorang bikin kamu kaget karena ternyata dia kenal kamu banget?",
      "Momen kasih kado terbaik di geng ini yang mana?",
      "Kenangan apa yang kamu pengin nggak pernah dilupain geng ini?",
      "Kenangan apa yang paling ngegambarin kenapa geng ini penting buat kamu?",
      "Kenangan apa yang detailnya masih kalian ributin sampai sekarang?",
    ],
  },
  home: {
    shared: [
      "Weekend yang sempurna di rumah itu kayak gimana buatmu?",
      "Diam-diam, kerjaan rumah apa yang kamu nggak keberatan ngerjain?",
      "Tradisi masa kecil apa yang pengin terus kamu lanjutin?",
      "Hal apa dari caraku dibesarin yang ngejelasin banyak soal aku?",
      "Kalau besok kita bikin acara makan malam, siapa aja yang diundang?",
      "Pagi yang santai buatmu itu kayak gimana?",
      "Kalau bisa, apa yang pengin kamu ubah dari rutinitas harianmu?",
      "Sebenarnya kamu butuh seberapa banyak waktu bareng orang dibanding waktu sendiri?",
      "Bau apa yang langsung bikin kamu ngerasa 'ini rumah'?",
      "Aturan apa dari rumah masa kecilmu yang masih kamu pegang — atau udah kamu langgar?",
      "Kamarmu pernah berantakan separah apa, dan kenapa?",
      "Gambarin rumah impianmu dalam satu kalimat.",
      "Barang apa di tempatmu yang punya cerita di baliknya?",
      "Kebiasaanmu di rumah apa yang ternyata aneh begitu ada yang ngasih tahu?",
      "Ngerasa betah di suatu tempat itu sebenarnya kayak gimana buatmu?",
      "Rumah siapa yang cuma sekali kamu datangin tapi masih kepikiran sampai sekarang?",
      "Rumahmu pernah seberisik apa, dan gara-gara apa?",
      "Ritual kecil apa yang bikin tempat mana pun kerasa kayak rumah?",
    ],
    couples: [
      "Gimana kita bagi kerjaan rumah yang sering nggak ada yang sadar?",
      "Apa yang bakal bikin tempat kita kerasa lebih 'kita'?",
      "Kamu pengin momen liburan kita kerasa kayak gimana?",
      "Kalau salah satu dari kita butuh waktu sendiri, kita mesti gimana?",
      "Kamu pengin kita lebih sering ngapain di rumah?",
      "Di keluargaku, kamu paling dekat sama siapa?",
      "Batasan apa sama keluarga yang perlu kita bikin?",
      "Kamu pengin kita gimana kalau ada tamu di tempat kita?",
      "Hal kecil apa di tempat kita yang bikin kerasa 'punya kita'?",
      "Kalau bisa, kerjaan rumah apa yang pengin kamu ambil alih dari aku selamanya?",
      "Jujur, menurutmu dekorasi tempat kita gimana?",
      "Ribut-ribut kita soal rumah yang mana yang sekarang kerasa konyol?",
      "Kamu pengin tamu ngerasa gimana waktu main ke tempat kita?",
      "Kamu ngerasa gimana soal cara kita ngabisin malam di rumah?",
      "Kebiasaanku di rumah yang mana yang diam-diam menurutmu lucu?",
      "Apa yang pengin kamu ubah dari pagi-pagi kita bareng?",
      "Tradisi keluargaku yang mana yang udah jadi tradisimu juga?",
      "Hari hujan ideal buat kita di rumah itu kayak gimana?",
      "Apa dari keluargaku yang bikin kamu jadi lebih paham aku?",
      "Kamu pengin rumah kita beda kayak gimana dari rumah tempat kita dibesarin dulu?",
      "Aturan rumah apa yang mesti kita resmiin?",
      "Suara favoritmu di rumah kita apa?",
      "Kita mesti lebih sering ngapain di rumah, berdua aja?",
      "Hari gabut paling asyik yang pernah kita lewatin di rumah itu yang mana?",
      "Kerjaan rumah apa yang diam-diam bikin kamu kesel kalau harus ngerjain sendirian?",
      "Apa yang kamu suka — atau nggak suka — dari jadi tuan rumah bareng?",
      "Kenangan pindahan bareng apa yang masih bikin kamu ketawa?",
      "Kalau uang bukan masalah, satu upgrade apa yang pengin kamu bikin buat rumah?",
      "Hal kecil apa yang aku lakuin di rumah yang bikin kamu ngerasa diperhatiin?",
      "Seberapa jauh kamu pengin keluarga kita terlibat di urusan rumah kita?",
      "Batasan apa sama mertua yang perlu kita pasang bareng?",
      "Hari Minggu sempurna di rumah versimu itu kayak gimana?",
      "Apa dari caraku ngurus rumah yang pengin kamu ubah, tapi pelan-pelan?",
      "Sudut mana di tempat kita yang paling 'kamu banget'?",
    ],
    friends: [
      "Geng ini selalu ujung-ujungnya ngumpul di tempat siapa, dan kenapa?",
      "Keluargamu kayak gimana kalau semua lagi kumpul di satu ruangan?",
      "Soal tempat kamu dibesarin, apa yang kamu pengin teman-temanmu tahu?",
      "Kamu biasanya jadi tuan rumah atau tamu?",
      "Tradisi keluarga apa yang pengin kamu bawa ke geng ini?",
      "Siapa di keluargamu yang bakal paling nyambung sama orang-orang di sini?",
      "Satu aturan rumah yang nggak bakal pernah kamu langgar apa?",
      "Hal kecil apa di tempat seseorang yang bikin tempatnya 'dia banget'?",
      "Pas numpang di tempat orang, kerjaan rumah apa yang nggak bakal kamu tawarin buat bantuin?",
      "Jujur, menurutmu dekorasi tempat seseorang di sini gimana?",
      "Ribut soal apa di tempat tinggal bareng yang sekarang kerasa konyol?",
      "Kamu pengin suasana tempat teman kerasa gimana waktu kamu main ke sana?",
      "Numpang nginep di tempat orang tanpa bilang-bilang — oke atau nggak?",
      "Kebiasaan teman sekos atau teman apa yang diam-diam menurutmu lucu?",
      "Apa yang pengin kamu ubah dari cara geng ini nongkrong di tempat seseorang?",
      "Tradisi keluargamu yang mana yang pengin kamu bagiin ke geng ini?",
      "Kalau hujan dan harus di dalam aja, hari ideal buat geng ini kayak gimana?",
      "Apa dari keluarga seseorang yang bikin kamu jadi lebih ngerti dia?",
      "Kamu pengin tongkrongan kita kerasa beda gimana dari yang kamu alamin waktu kecil?",
      "Aturan rumah apa yang wajib diresmiin geng ini?",
      "Suara favoritmu dari tempat yang kerasa kayak rumah itu apa?",
      "Apa yang harusnya lebih sering dilakuin geng ini — cuma nyantai di tempat seseorang?",
      "Hari gabut paling enak yang pernah kamu lewatin di tempat seseorang kayak gimana?",
      "Kerjaan apa yang diam-diam bikin kamu kesel kalau lagi jadi tuan rumah?",
      "Apa yang kamu suka — atau benci — dari jadi tuan rumah buat geng ini?",
      "Kenangan nginep atau nongkrong apa yang masih bikin kamu ketawa sampai sekarang?",
      "Kalau duit bukan masalah, satu hal apa di rumah yang pengin kamu upgrade?",
      "Hal kecil apa yang dilakuin teman di tempatnya yang bikin kamu ngerasa disambut?",
      "Seberapa jauh kamu pengin keluargamu ikut terlibat di pertemananmu?",
      "Batasan apa sama teman sekos atau keluarga yang harus dihargai geng ini?",
      "Nongkrong hari Minggu yang sempurna versimu itu kayak gimana?",
      "Apa dari cara seseorang di sini ngurus tempatnya yang bikin kamu kaget?",
      "Sudut mana di tempat seseorang yang paling kerasa 'dia banget'?",
      "Kalau harus milih, tempat siapa yang paling bikin kamu males pulang?",
    ],
  },
  growth: {
    shared: [
      "Tahun ini kamu bangga sama diri sendiri karena apa?",
      "Lima tahun terakhir ini, kamu berubah kayak gimana?",
      "Apa yang dulu bikin kamu takut tapi sekarang udah nggak?",
      "Setahun lagi, kamu pengin lebih jago di hal apa?",
      "Kamu udah berubah pikiran total soal apa?",
      "Sekarang kamu ngerasa lagi stuck di bagian mana?",
      "Akhir-akhir ini, sukses itu artinya apa buat kamu?",
      "Kebiasaan apa yang bakal bikin hidupmu jauh lebih baik kalau kamu beneran konsisten?",
      "Apa yang pengin kamu coba tapi ngerasa udah ketuaan atau telat?",
      "Bagian mana dari kerjaanmu yang beneran bikin kamu semangat?",
      "Kapan terakhir kali kamu ngelakuin hal yang bikin kamu takut?",
      "Kamu perlu lebih sering bilang 'nggak' ke apa?",
      "Kamu sepuluh tahun lalu bakal mikir apa soal kamu yang sekarang?",
      "Kesalahan apa yang ngajarin kamu lebih banyak daripada kemenangan mana pun?",
      "Apa yang dulu bikin kamu malu tapi sekarang udah nggak?",
      "Versi lama dirimu yang mana yang untungnya udah kamu tinggalin?",
      "Kebiasaan atau pola pikir apa yang paling susah buat kamu lepasin?",
      "Sekarang kamu pengin banget denger pujian apa soal perkembanganmu?",
    ],
    couples: [
      "Masukan dari aku yang mana yang beneran ngebantu kamu?",
      "Masukan apa yang kamu harap bisa aku omongin agak lebih lembut?",
      "Kamu pengin aku bantu kayak gimana biar kamu tetap on track?",
      "Apa yang udah kamu ubah dari dirimu gara-gara hubungan ini?",
      "Kebiasaan apa yang berhasil kamu bangun berkat pasanganmu, tanpa diceramahin?",
      "Versi dirimu yang mana yang belum pernah dilihat pasanganmu — dan dia rugi nggak?",
      "Apa yang lagi kamu usahain yang pasanganmu belum tahu sepenuhnya?",
      "Pasanganmu bikin kamu lebih sabar — atau malah kurang?",
      "Pujian apa soal perkembanganmu yang pengin banget kamu dengar dari pasanganmu?",
      "Sekarang kamu bisa ngadepin apa dengan lebih baik dibanding waktu kalian baru kenal?",
      "Ketakutan apa yang udah bisa kamu lewatin, sebagian berkat pasanganmu?",
      "Gimana pasanganmu ngedorong kamu jadi lebih baik, walaupun kadang nyelekit?",
      "Apa yang dilakuin pasanganmu yang diam-diam bikin kamu jadi orang yang lebih baik?",
      "Keyakinan soal hubungan apa yang udah kamu lepasin sejak sama pasanganmu?",
      "Target apa yang kamu pasang karena pasanganmu yakin kamu bisa?",
      "Apa yang dulu bikin kamu kesulitan, terus pasanganmu bantu kamu ngelewatinnya?",
      "Setahun ke depan, kamu pengin kita tumbuh bareng kayak gimana?",
      "Kamu lagi berusaha jadi sosok kayak apa yang sebenarnya udah dilihat pasanganmu dalam dirimu?",
      "Kebenaran pahit apa dari pasanganmu yang akhirnya malah ngebantu kamu?",
      "Kamu bangga nggak nyerah soal apa, berkat dukungan pasanganmu?",
      "Gimana hubungan ini bikin kamu jadi lebih dewasa?",
      "Skill apa yang kamu dapet cuma dari sering bareng pasanganmu?",
      "Soal berantem, sekarang kalian lebih jago di bagian apa?",
      "Gimana pasanganmu ngajak kamu keluar dari zona nyaman, dan ternyata itu bagus buat kamu?",
      "Apa yang masih kamu perbaiki dan butuh kesabaran pasanganmu?",
      "Kapan pasanganmu ngelihat potensimu sebelum kamu sendiri sadar?",
      "Kebiasaan apa yang udah kamu tinggalin dan diam-diam bikin pasanganmu bersyukur?",
      "Kamu pengin makin jago soal apa demi pasanganmu, bukan cuma buat dirimu sendiri?",
      "Gimana ngerasa disayang bikin kamu jadi lebih berani?",
      "Pencapaian pribadi apa yang diperhatiin pasanganmu dan harusnya kamu rayain lebih heboh?",
      "Apa yang udah kamu maafin dari dirimu sendiri, berkat bantuan pasanganmu?",
      "Gimana pasanganmu ngajarin kamu jadi lebih baik hati — bahkan ke diri sendiri?",
      "Kesalahan apa di hubungan ini yang paling bikin kamu tumbuh?",
      "Tahun ini, kamu paling pengin kita tumbuh bareng dalam hal apa?",
    ],
    friends: [
      "Hal paling berguna yang pernah dibilang teman soal dirimu apa?",
      "Siapa di sini yang bakal ngomong jujur ke kamu pas nggak ada orang lain yang mau?",
      "Kamu pengin teman-temanmu negur kamu soal apa?",
      "Apa yang udah kamu ubah dari dirimu karena geng ini?",
      "Kebiasaan apa yang kamu bangun berkat bantuan teman, tanpa diceramahin?",
      "Versi dirimu yang mana yang belum pernah ketemu geng ini — dan mereka rugi nggak?",
      "Kamu lagi ngusahain apa yang orang-orang di sini belum tahu sepenuhnya?",
      "Geng ini bikin kamu lebih sabar — atau malah kurang?",
      "Pujian soal perkembanganmu apa yang pengin banget kamu dengar dari seseorang di sini?",
      "Apa yang sekarang bisa kamu hadapi lebih baik dibanding pas geng ini baru kenalan?",
      "Ketakutan apa yang udah berhasil kamu lewatin, sebagian berkat seseorang di sini?",
      "Gimana geng ini ngedorong kamu jadi lebih baik, walau kadang nyelekit?",
      "Apa yang dilakuin teman yang diam-diam bikin kamu jadi orang yang lebih baik?",
      "Keyakinan soal pertemanan apa yang udah kamu lepasin gara-gara geng ini?",
      "Target apa yang kamu pasang karena seseorang di sini yakin kamu bisa?",
      "Apa yang dulu bikin kamu kesusahan dan akhirnya bisa kamu lewatin berkat geng ini?",
      "Setahun ke depan, kamu pengin bertumbuh bareng geng ini kayak gimana?",
      "Kamu lagi berusaha jadi orang kayak gimana, yang sebenarnya udah dilihat geng ini dari kamu?",
      "Kebenaran pahit apa dari seseorang di sini yang akhirnya malah ngebantu kamu?",
      "Kamu bangga nggak nyerah soal apa, berkat dukungan geng ini?",
      "Gimana pertemanan ini bikin kamu jadi lebih dewasa?",
      "Skill apa yang kamu dapet cuma dari nongkrong bareng geng ini?",
      "Soal beda pendapat, sekarang kamu jadi lebih jago di bagian apa, berkat geng ini?",
      "Gimana seseorang di sini ngajak kamu keluar dari zona nyaman, dan hasilnya malah bagus?",
      "Apa yang masih kamu perbaiki dan butuh kesabaran geng ini?",
      "Kapan seseorang di sini ngelihat potensimu sebelum kamu sendiri sadar?",
      "Kebiasaan apa yang udah kamu tinggalin dan diam-diam bikin geng ini bersyukur?",
      "Apa yang pengin kamu perbaiki demi geng ini, bukan cuma demi dirimu sendiri?",
      "Gimana punya orang-orang ini di sekitarmu bikin kamu jadi lebih berani?",
      "Pencapaian pribadi apa yang disadari seseorang di sini dan harusnya lebih kamu rayain?",
      "Apa yang udah kamu maafin dari dirimu sendiri, berkat bantuan geng ini?",
      "Gimana geng ini ngajarin kamu jadi lebih baik hati — bahkan ke diri sendiri?",
      "Kesalahan apa di pertemanan ini yang paling bikin kamu bertumbuh?",
      "Tahun ini, kamu paling pengin bertumbuh bareng geng ini dalam hal apa?",
    ],
  },
  gratitude: {
    shared: [
      "Hari ini kamu bersyukur buat apa?",
      "Siapa di luar ruangan ini yang bikin kamu bersyukur?",
      "Kejadian berat apa yang sekarang malah kamu syukuri?",
      "Apa dari badanmu yang kamu syukuri?",
      "Sebutin tiga hal baik yang kejadian minggu ini.",
      "Siapa yang ngajarin kamu sesuatu yang sampai sekarang masih kamu syukuri?",
      "Apa sih dari momen sekarang ini yang patut disyukuri?",
      "Sifatku yang mana yang bikin kamu seneng aku punya?",
      "Kamu belajar apa dari aku yang bikin kamu bersyukur?",
      "Hal sehari-hari apa yang paling bakal kamu kangenin kalau tiba-tiba hilang?",
      "Kamu belum pernah bener-bener bilang makasih ke siapa?",
      "Kenyamanan apa di hidupmu yang sering kamu anggap biasa aja?",
      "Spesifiknya, apa dari hari ini yang bikin kamu bersyukur?",
      "Masa-masa berat apa yang ujung-ujungnya ngasih kamu hal baik?",
      "Bakatmu yang mana yang diem-diem kamu syukuri?",
      "Hal kecil apa yang belakangan ini dilakuin orang buat kamu dan bener-bener kamu hargai?",
      "Tempat apa yang kamu syukuri ada di hidupmu?",
      "Apa dari kemampuanmu buat bangkit lagi yang bikin kamu bersyukur?",
    ],
    couples: [
      "Apa satu hal soal kita yang lagi kamu syukuri sekarang?",
      "Hal apa yang aku lakuin tapi belum pernah beneran kamu bilang makasih?",
      "Kenyamanan kecil apa di hidup kita yang kamu nggak mau sampai hilang?",
      "Apa yang aku lakuin minggu ini yang bikin hidupmu jadi lebih gampang?",
      "Apa dari dirimu yang kamu syukuri masih dimaklumin sama pasanganmu?",
      "Apa yang ada di rumah kita yang paling bikin kamu bersyukur?",
      "Sebenernya apa sisi baik dari cara kita berantem?",
      "Apa dari kesabaran pasanganmu yang bikin kamu bersyukur?",
      "Masa-masa berat apa yang kita lewatin bareng dan sekarang kamu syukuri?",
      "Apa yang dilakuin pasanganmu tiap hari tapi belum pernah beneran kamu bilang makasih?",
      "Gimana pasanganmu bikin kamu jadi orang yang lebih baik?",
      "Apa yang udah dikasih keluarga pasanganmu yang bikin kamu bersyukur?",
      "Rasa nyaman apa dari pasanganmu yang kalau nggak ada, kamu bakal kelimpungan?",
      "Hal apa di hubungan ini yang masih jarang kamu bilang makasih?",
      "Pengorbanan apa dari pasanganmu yang bikin kamu bersyukur banget?",
      "Apa yang diajarin pasanganmu yang bikin kamu senang udah belajar itu?",
      "Cara pasanganmu selalu ada buat kamu yang mana yang nggak pengin kamu anggap sepele?",
      "Kekurangan pasanganmu yang mana yang anehnya malah kamu syukuri?",
      "Kapan dukungan pasanganmu lebih berarti daripada yang dia kira?",
      "Momen apa di hidup kalian bareng yang bikin kamu pengin waktu berhenti saking bersyukurnya?",
      "Sifat pasanganmu yang mana yang pengin lebih sering kamu makasihin?",
      "Apa dari cara pasanganmu berdebat yang diam-diam kamu syukuri?",
      "Gimana pasanganmu bikin keluargamu jadi lebih baik — atau sebaliknya?",
      "Pengorbanan soal duit apa dari pasanganmu yang kamu syukuri?",
      "Soal jadi tua bareng pasanganmu, apa yang udah kamu syukuri dari sekarang?",
      "Kejujuran pahit apa dari pasanganmu yang sekarang kamu syukuri?",
      "Hal apa yang dibawa pasanganmu di rumah yang paling kamu syukuri?",
      "Kebiasaan kecil harian pasanganmu yang mana yang kamu syukuri?",
      "Kesalahan apa yang udah dimaafin pasanganmu dan sampai sekarang masih kamu syukuri?",
      "Gimana pasanganmu pernah ada buat keluargamu dengan cara yang kamu hargai?",
      "Apa dari selera humor pasanganmu yang bikin kamu kuat di hari-hari berat?",
      "Kapan kamu ngerasa beruntung banget punya pasangan kayak dia?",
      "Apa dari semangat pasanganmu yang bikin kamu senang ikut ketularan?",
      "Apa satu hal yang pengin kamu makasihin ke pasanganmu sekarang juga?",
    ],
    friends: [
      "Apa yang pernah dilakuin seseorang di sini buat kamu, tapi belum pernah kamu bilang makasih dengan bener?",
      "Apa dari dirimu yang kamu syukuri masih dimaklumin sama teman-temanmu?",
      "Hal kecil apa dari geng ini yang paling bakal kamu kangenin?",
      "Siapa di sini yang bikin masa sulit jadi lebih ringan, bahkan tanpa dia sadar?",
      "Apa yang kamu pelajarin dari seseorang di ruangan ini yang bikin kamu bersyukur?",
      "Sebenarnya apa sih sisi baik dari cara geng ini kalau lagi beda pendapat?",
      "Kesabaran siapa di sini yang kamu syukuri?",
      "Masa sulit bareng geng ini yang mana yang sekarang malah kamu syukuri pernah kamu lewatin?",
      "Apa yang rutin dilakuin teman, tapi belum pernah kamu bilang makasih dengan bener?",
      "Gimana geng ini bikin kamu jadi orang yang lebih baik?",
      "Apa yang pernah dibagi keluarga seseorang ke kamu yang bikin kamu bersyukur?",
      "Kenyamanan apa dari teman yang kalau nggak ada, kamu bakal bingung?",
      "Apa dari pertemanan ini yang masih kurang sering kamu bilang makasih?",
      "Pengorbanan apa dari teman yang bikin kamu bersyukur banget?",
      "Apa yang diajarin teman yang kamu senang udah kamu pelajarin?",
      "Cara seseorang di sini selalu ada yang mana yang nggak pengin kamu anggap biasa aja?",
      "Kekurangan teman yang mana yang anehnya malah kamu syukuri?",
      "Kapan dukungan seseorang ternyata lebih berarti dari yang dia kira?",
      "Momen bareng geng ini yang mana yang pengin kamu bekuin saking bersyukurnya?",
      "Sifat seseorang di sini yang mana yang kamu pengin lebih sering bilang makasih buatnya?",
      "Apa dari cara seseorang di sini berdebat yang diam-diam kamu syukuri?",
      "Gimana geng ini bikin kehidupan keluargamu jadi lebih baik — atau sebaliknya?",
      "Pengorbanan teman — soal duit atau lainnya — yang mana yang kamu syukuri?",
      "Apa dari tambah tua bareng geng ini yang udah kamu syukuri dari sekarang?",
      "Kebenaran pahit apa dari seseorang di sini yang sekarang kamu syukuri?",
      "Apa dari kehidupan sosialmu yang paling kamu syukuri berkat geng ini?",
      "Kebiasaan kecil seseorang di sini yang mana yang kamu syukuri?",
      "Kesalahanmu yang mana yang pernah dimaafin teman dan sampai sekarang masih kamu syukuri?",
      "Gimana geng ini pernah ada buat keluargamu dengan cara yang kamu hargai?",
      "Apa dari humor geng ini yang bikin kamu kuat ngelewatin hari-hari berat?",
      "Kapan kamu ngerasa beruntung banget punya teman-teman ini?",
      "Semangat siapa di sini yang kamu senang bisa ketularan?",
      "Satu hal apa yang pengin kamu bilang makasih ke seseorang di sini sekarang juga?",
      "Kenangan bareng geng ini yang mana yang diam-diam kamu syukuri pernah kamu alamin?",
    ],
  },
  adventure: {
    shared: [
      "Hal terbesar apa yang bakal kamu coba kalau tahu pasti nggak bakal gagal?",
      "Gunung, pantai, atau kota — di mana kamu ngerasa paling hidup?",
      "Tempat mana yang belum pernah kita datengin sama sekali, padahal wajib banget didatengin?",
      "Rencanain semua detail, atau berangkat aja tanpa rencana?",
      "Kalau mulai besok kita libur dua minggu, mau ngapain?",
      "Kegiatan outdoor apa yang wajib kita coba bareng tahun ini?",
      "Makanan apa yang pengin kamu makan langsung di negara asalnya?",
      "Road trip atau naik pesawat — dan siapa yang nyetir?",
      "Tempat deket sini mana yang belum pernah kita samperin?",
      "Pindah ke tempat baru tiap tahun, atau menetap di satu tempat?",
      "Hal nekat apa yang pernah kamu lakuin sekali terus kapok?",
      "Kalau kita libur setahun penuh bareng, mau ngapain?",
      "Suara, bau, atau tempat apa yang langsung bikin kamu ngerasa bebas?",
      "Petualangan kecil apa yang bisa kita lakuin weekend ini?",
      "Petualangan apa yang ternyata jauh beda dari yang kamu bayangin?",
      "Keputusan paling spontan apa yang pernah kamu ambil waktu jalan-jalan?",
      "Tantangan fisik apa yang pengin banget kamu coba bareng?",
      "Kalau bisa teleport ke mana aja selama sejam, kamu mau ke mana?",
    ],
    couples: [
      "Liburan terbaik yang pernah kamu jalanin sebelum kita ketemu apa?",
      "Liburan anniversary impian kita itu kayak gimana?",
      "Tempat paling liar yang pengin kamu datengin bareng di mana?",
      "Liburan santai sambil lihat pemandangan atau petualangan penuh aksi bareng pasanganmu?",
      "Liburan kacau apa yang pernah kalian lewatin dan sekarang malah bikin ketawa?",
      "Petualangan apa hasil bujukan pasanganmu yang sekarang bikin kamu seneng udah ikut?",
      "Pemandangan paling romantis yang pernah kalian lihat bareng di mana?",
      "Perjalanan apa yang bikin cara kalian mandang satu sama lain jadi berubah?",
      "Apa yang nggak bakal kamu coba sendirian tapi mau kalau bareng pasanganmu?",
      "Hal paling serem apa yang bakal kalian lakuin bareng kalau sekarang juga sama-sama bilang iya?",
      "Negara mana yang pengin kalian tinggalin bareng selama setahun?",
      "Hal random paling seru apa yang nggak sengaja kalian temuin waktu jalan-jalan?",
      "Petualangan apa yang pengin kamu cobain sebelum kita ketuaan buat nikmatinnya?",
      "Kemping di bawah bintang atau hotel mewah — berdua?",
      "Hal nekat apa yang bakal bikin orang kaget kalau pasanganmu mau ngelakuinnya?",
      "Liburan bareng mana yang pengin kamu ulang persis kayak dulu?",
      "Petualangan apa yang bakal nguji kalian sebagai pasangan — tapi dalam arti yang positif?",
      "Cara paling 'kalian banget' buat ngabisin hari libur dadakan gimana?",
      "Bucket list apa yang pengin kamu coret pas pasanganmu ada di sana?",
      "Kapan kalian paling deg-degan waktu nyoba hal baru bareng?",
      "Petualangan apa yang worth it banget, berapa pun biayanya?",
      "Skill apa yang pengin kalian pelajari bareng cuma demi serunya?",
      "Perjalanan terjauh yang pernah kalian jalanin bareng ke mana?",
      "Petualangan apa yang bakal jadi cerita seru buat cucu-cucu kalian?",
      "Jalan mana yang dari dulu pengin kalian susurin aja, nyetir tanpa tujuan?",
      "Hal paling 'bukan dia banget' yang pernah dilakuin pasanganmu waktu jalan-jalan apa?",
      "Petualangan apa yang pengin kamu alamin lagi persis kayak waktu itu?",
      "Ketakutan apa yang pengin kalian hadapi bareng sekali, biar bisa bilang pernah?",
      "Oleh-oleh terbaik dari liburan bareng apa, dan kenapa?",
      "Petualangan apa yang dari dulu pengin dicoba pasanganmu tapi belum pernah kamu tanyain?",
      "'Iya' paling nekat yang pernah kalian bilang ke satu sama lain waktu liburan apa?",
      "Liburan apa yang terus-terusan hampir kalian rencanain tapi nggak pernah di-booking?",
      "Tempat paling indah yang pernah kamu lihat bareng pasanganmu di mana?",
      "Petualangan apa yang ngajarin kamu hal baru soal pasanganmu?",
    ],
    friends: [
      "Liburan terbaik yang pernah kamu jalanin tanpa ada satu pun orang dari sini apa?",
      "Siapa di ruangan ini yang paling asyik diajak jalan-jalan? Jujur, ya.",
      "Tempat paling gila yang harus didatengin geng ini bareng di mana?",
      "Liburan santai sambil nikmatin pemandangan atau petualangan penuh aksi bareng geng ini?",
      "Liburan kacau apa yang pernah dilewatin geng ini dan sekarang malah bikin ketawa?",
      "Petualangan apa hasil bujukan seseorang di sini yang sekarang bikin kamu seneng udah ikut?",
      "Pemandangan paling berkesan yang pernah dinikmatin geng ini bareng apa?",
      "Perjalanan apa yang bikin kamu ngelihat seseorang di sini dengan cara yang beda?",
      "Apa yang nggak bakal kamu coba sendirian tapi mau kalau bareng geng ini?",
      "Hal paling serem apa yang bakal dilakuin geng ini kalau sekarang semua langsung bilang iya?",
      "Geng ini harus tinggal bareng di negara mana selama satu musim panas?",
      "Temuan random paling seru yang nggak sengaja ditemuin geng ini waktu jalan-jalan apa?",
      "Petualangan apa yang wajib kamu jalanin bareng geng ini sebelum kita ketuaan?",
      "Kemping di bawah bintang atau villa mewah — bareng geng ini?",
      "Hal nekat apa yang bakal bikin orang kaget kalau diiyain sama seseorang di sini?",
      "Liburan bareng geng yang mana yang pengin kamu ulang persis sama kayak dulu?",
      "Petualangan apa yang bakal nguji pertemanan ini — tapi dalam arti yang positif?",
      "Cara paling 'geng ini banget' buat ngabisin hari libur dadakan gimana?",
      "Bucket list apa yang pengin kamu wujudin pas ada seseorang dari sini yang nemenin?",
      "Kapan kamu paling deg-degan waktu nyoba hal baru bareng geng ini?",
      "Petualangan apa yang pasti worth it, berapa pun duit yang keluar?",
      "Skill apa yang harus dipelajarin geng ini bareng, cuma demi serunya petualangan?",
      "Perjalanan paling jauh yang pernah dijalanin geng ini bareng ke mana?",
      "Petualangan apa yang bakal jadi cerita seru buat cucu-cucumu?",
      "Jalan mana yang dari dulu pengin disusurin geng ini naik mobil, tanpa tujuan?",
      "Hal paling 'bukan dia banget' yang pernah dilakuin seseorang di sini waktu jalan-jalan apa?",
      "Petualangan apa yang pengin kamu alamin lagi persis kayak waktu itu?",
      "Ketakutan apa yang mau kamu hadapin sekali bareng geng ini, biar bisa bilang pernah?",
      "Oleh-oleh terbaik dari liburan bareng geng ini apa, dan kenapa?",
      "Petualangan apa yang dari dulu pengin dijalanin seseorang di sini tapi belum ada yang nanyain?",
      "'Iya' paling nekat yang pernah diucapin geng ini waktu liburan apa?",
      "Liburan apa yang udah berkali-kali hampir direncanain geng ini tapi nggak pernah di-booking?",
      "Tempat paling indah yang pernah kamu lihat bareng orang-orang dari geng ini di mana?",
      "Petualangan apa yang ngajarin kamu hal baru soal seseorang di sini?",
    ],
  },
  everyday: {
    shared: [
      "Bagian terbaik dari hari biasa buatmu apa?",
      "Kopi atau tehmu biasanya kayak gimana?",
      "Kalau mau buang-buang waktu sejam, kamu paling suka ngapain?",
      "Belakangan ini kamu paling sering kepikiran apa?",
      "Kerjaan rumah apa yang kamu rela bayar orang buat ngerjain selamanya?",
      "Apa yang paling kamu tunggu-tunggu di hari kerja biasa?",
      "Comfort food andalanmu kalau hari lagi kacau apa?",
      "Sebenarnya kamu paling suka dibangunin kayak gimana?",
      "Hal terakhir yang bikin kamu ketawa ngakak apa?",
      "Waktu buat apa yang paling banyak kesita gara-gara HP?",
      "Kegiatan gratis favoritmu yang biasa kita lakuin apa?",
      "Kamu beneran lagi gimana sih? Jangan jawab basa-basi.",
      "Kebiasaan kecilku apa yang bikin kamu kesel? Jujur ya — tapi yang halus.",
      "Ritual kecil sehari-hari apa yang ogah banget kamu tinggalin?",
      "Kerjaan ngebosenin apa yang anehnya malah bikin kamu puas?",
      "Hal biasa apa yang langsung bikin mood kamu naik?",
      "Jujur, energimu sekarang berapa dari 10?",
      "Hal kecil sehari-hari apa yang tiap kali pasti bikin kamu kesel?",
    ],
    couples: [
      "Kamu pengin disambut kayak gimana pas aku pulang?",
      "Kamu tipe bangun pagi atau begadang?",
      "Menurutmu, malam biasa yang asyik bareng itu kayak gimana?",
      "Kebiasaan kecil pasanganmu sehari-hari yang diam-diam kamu suka apa?",
      "Hal paling 'kayak pasangan yang udah lama nikah' yang kalian lakuin apa?",
      "Kebiasaan chat pasanganmu yang mana yang nunjukin banget sifatnya?",
      "Kerjaan ngebosenin apa yang malah kamu nikmatin kalau bareng pasanganmu?",
      "Apa dari rutinitas pagi pasanganmu yang bikin kamu kaget?",
      "Kombinasi makanan apa yang suka dimakan pasanganmu yang nggak bakal pernah kamu ngerti?",
      "Momen biasa banget terakhir bareng pasanganmu yang kamu suka itu apa?",
      "Kerjaan rumah apa yang diam-diam kalian sepakat buat nggak pernah dibahas?",
      "Kata-kata andalan pasanganmu apa — lucu atau nyebelin?",
      "Bagian mana dari rutinitas pasanganmu yang mulai kamu tiru?",
      "Gimana cara pasanganmu nyelesaiin masalah yang bikin kamu kagum?",
      "Apa yang kalian lakuin berulang-ulang tapi nggak pernah bikin bosen?",
      "Kebiasaan pasanganmu yang mana yang butuh waktu buat kamu biasain?",
      "Urusan sehari-hari apa yang paling 'kalian banget' kalau dikerjain bareng?",
      "Apa dari energi harian pasanganmu yang nular ke kamu?",
      "Hal kecil apa yang bikin nyaman dan kalian nikmatin bareng tiap hari?",
      "Hal aneh apa yang jadi normal sejak kalian jadian?",
      "Jawaban andalan pasanganmu kalau ditanya 'mau makan apa?' itu apa?",
      "Debat kecil apa yang terus kalian ulang tapi nggak pernah jadi serius?",
      "Kebiasaan pasanganmu main HP nunjukin apa soal dia?",
      "Hal paling gampang ditebak yang dilakuin pasanganmu tiap hari apa?",
      "Kebiasaan Minggu pagi apa yang kalian lakuin bareng?",
      "Hal kecil apa yang dilakuin pasanganmu yang bakal langsung kamu sadar kalau dia berhenti?",
      "Cara paling simpel kalian nunjukin sayang di hari biasa itu gimana?",
      "Urusan harian apa yang diam-diam jadi bagian favoritmu dalam sehari?",
      "Bagian mana dari rutinitas pasanganmu yang anehnya malah bikin gemes?",
      "Omongan pasanganmu akhir-akhir ini yang masih nempel di kepalamu apa?",
      "Kegiatan Selasa biasa apa yang bakal kamu pilih daripada hal yang 'seru'?",
      "Apa dari ritme harianmu yang cuma jalan karena ada pasanganmu?",
      "Candaan kecil apa yang hampir tiap hari kalian bikin tanpa sadar?",
      "Hal biasa banget apa dari pasanganmu yang bakal kamu kangenin banget?",
    ],
    friends: [
      "Grup chat kita sebenarnya buat apa, sih?",
      "Siapa di sini yang paling lama bales chat, dan alasannya apa?",
      "Buatmu, nongkrong malam yang asyik tapi biasa aja bareng teman-teman itu kayak gimana?",
      "Kebiasaan kecil sehari-hari siapa di sini yang diam-diam kamu suka?",
      "Hal paling 'kayak anak kos jompo' yang dilakuin geng ini apa?",
      "Kebiasaan chat siapa di sini yang nunjukin banget sifatnya?",
      "Kerjaan ngebosenin apa yang malah kamu nikmatin kalau bareng geng ini?",
      "Hal apa dari rutinitas pagi seseorang yang bikin kamu kaget?",
      "Kombinasi makanan apa yang dimakan seseorang di sini yang sampai kapan pun nggak bakal kamu ngerti?",
      "Momen biasa banget terakhir bareng geng ini yang kamu suka itu apa?",
      "Kebiasaan geng apa yang diam-diam kita sepakat buat nggak pernah dibahas?",
      "Kata andalan seseorang apa nih — lucu atau nyebelin?",
      "Bagian mana dari rutinitas seseorang yang mulai kamu tiru?",
      "Gimana cara seseorang di sini nyelesaiin masalah yang bikin kamu kagum?",
      "Apa yang kalian lakuin berulang-ulang tapi nggak pernah bosen?",
      "Kebiasaan siapa di sini yang butuh waktu buat kamu biasain?",
      "Urusan sehari-hari apa yang paling 'geng ini banget' kalau dikerjain bareng?",
      "Energi harian siapa di sini yang nular ke kamu?",
      "Hal kecil yang bikin nyaman apa yang selalu dibagi-bagi di geng ini?",
      "Hal aneh apa yang jadi normal sejak kamu kenal geng ini?",
      "Siapa yang selalu jawab 'terserah, apa aja boleh' waktu kita milih mau makan apa?",
      "Debat kecil apa yang terus kejadian di geng ini tapi nggak pernah jadi serius?",
      "Kebiasaan main HP seseorang nunjukin apa soal dia?",
      "Hal paling gampang ditebak yang dilakuin seseorang di sini tiap hari apa?",
      "Kebiasaan pagi pas weekend apa yang sama-sama dilakuin geng ini?",
      "Hal kecil apa yang dilakuin seseorang di sini yang bakal langsung kamu sadar kalau dia berhenti?",
      "Cara paling low-key geng ini nunjukin kalau peduli di hari biasa itu gimana?",
      "Urusan harian apa yang diam-diam jadi momen favoritmu tiap hari?",
      "Bagian mana dari rutinitas seseorang yang anehnya malah gemesin buatmu?",
      "Omongan siapa di sini akhir-akhir ini yang masih nempel di kepalamu?",
      "Kegiatan biasa di hari kerja apa yang bakal kamu pilih daripada hal yang 'seru'?",
      "Apa dari ritme harianmu yang cuma bisa jalan karena ada geng ini?",
      "Candaan kecil apa yang hampir tiap hari dibikin geng ini tanpa sadar?",
      "Hal biasa banget apa dari seseorang di sini yang bakal kamu kangenin banget?",
    ],
  },
};
